/* ---------- Law and standards notes for scenario steps ---------- */
// Keyed by scenario id, then step index. Applied after all scenarios are loaded.
const STEP_LAW = {
  challenge:{0:"The UK Online Safety Act lists content encouraging dangerous stunts and challenges as “priority content” harmful to children. Services likely to be accessed by children must protect them from it.",
             3:"For very large platforms, the EU Digital Services Act (Articles 34 and 35) requires yearly systemic-risk assessments covering harm to minors. Post-incident reviews feed directly into them."},
  rfi:{0:"Under the EU Digital Services Act (Article 67), the European Commission can send formal requests for information to very large platforms. Supplying incorrect, incomplete or misleading information can be fined up to 1% of annual worldwide turnover.",
       1:"Supplying misleading information to a DSA request is itself a finable breach, separate from any underlying risk.",
       2:"DSA Article 28 requires platforms accessible to minors to ensure a high level of privacy, safety and security; Article 35 requires very large platforms to mitigate systemic risks."},
  vip:{1:"The EU Digital Services Act (Article 14) requires platforms to apply their terms diligently, objectively and proportionately. Slower, softer enforcement for high-profile accounts can breach this.",
       3:"DSA transparency reports (Articles 15 and 24) must describe how moderation works. Disclosing special review programs protects you when they come to light."},
  counterfeit:{0:"Notice-and-action rules (EU DSA Article 16) require timely, diligent and objective decisions on notices, not blanket removal. In the US, trademark takedowns aren't covered by the DMCA's safe harbor, so an accurate, documented process matters.",
               3:"Under the DSA (Article 22), notices from officially designated trusted flaggers get priority, but the platform still makes the decision."},
  offplatform:{0:"Fraud is a priority illegal harm under the UK Online Safety Act, so platforms must assess and reduce scam risk proactively, not only respond to reports."},
  mules:{0:"In the US, the Bank Secrecy Act generally requires a suspicious activity report within 30 days of detecting suspicious activity. The UK and EU have equivalent reporting duties, and tipping off the subject can be an offence.",
         3:"Regulators expect transaction monitoring proportionate to your risk, for example under FinCEN rules in the US and the UK Money Laundering Regulations 2017."},
  impersonation:{2:"Since October 2024, UK payment firms must reimburse most authorised push payment scam victims up to £85,000, splitting the cost 50:50 between sending and receiving firms. There's an exception for gross negligence by the customer.",
                 3:"Caller authentication programs such as STIR/SHAKEN in the US, and similar schemes elsewhere, help carriers block spoofed calls that impersonate trusted brands."},
  gifting:{0:"US law (18 U.S.C. § 2258A) requires reporting apparent child sexual exploitation to NCMEC's CyberTipline. The 2024 REPORT Act added online enticement to the reporting duty and extended evidence preservation to one year.",
           3:"In 2022 the FTC fined Epic Games $275 million under COPPA, citing voice and text chat switched on by default for children. The UK Age Appropriate Design Code also expects high-privacy defaults for children."},
  swatting:{1:"US law (18 U.S.C. § 2702(b)(8)) lets providers disclose data to law enforcement when they believe in good faith that an emergency involves danger of death or serious injury. Many other countries have similar emergency provisions."},
  assault:{0:"In the US, law enforcement can ask providers to preserve records for 90 days, renewable (18 U.S.C. § 2703(f)). For serious offline harm, preserve evidence proactively instead of waiting to be asked.",
           1:"Platforms can enforce their own safety policies without a criminal conviction, as long as the terms are clear and applied consistently."},
  romance:{0:"Romance fraud falls under fraud, a priority illegal harm in the UK Online Safety Act. Ofcom's codes expect proactive measures such as detecting fake and scam accounts.",
           3:"Sharing threat indicators with industry groups and law enforcement is how cross-platform scam networks get disrupted."},
  deepfake:{2:"The C2PA content-credentials standard lets platforms and newsrooms verify where media came from and whether AI generated it.",
            3:"From August 2026, the EU AI Act (Article 50) requires AI-generated content to be marked in a machine-readable way, and deployers to disclose deepfakes of real people."},
  companion:{1:"California's companion chatbot law (SB 243, 2025) requires protocols for responding to suicidal ideation, referrals to crisis services, and clear reminders to known minors that they're talking to an AI.",
             3:"AI companion rules are emerging state by state in the US, and the EU AI Act adds transparency duties for chatbots from August 2026."},
  courier:{2:"The EU Platform Work Directive, which countries must apply by December 2026, requires human review of significant automated decisions such as deactivations, with a right to an explanation."},
  camera:{1:"Hidden recording in private spaces is a criminal offence in many places, including under US and UK voyeurism laws. Privacy law also generally expects affected people to be told when their data or images may have been captured."},
  classroom:{0:"Reporting duties for apparent child sexual abuse material apply even when the sender is a minor (in the US, 18 U.S.C. § 2258A).",
             1:"NCMEC's Take It Down lets minors create a digital fingerprint of an image so participating platforms can find and remove it, without the image itself being shared.",
             3:"Schools must meet their own duties when using edtech: FERPA and COPPA in the US, and the Keeping Children Safe in Education guidance in England."},
  comments:{1:"The UK Online Safety Act's children's codes and the EU DSA (Article 28) both expect recommender systems to be adjusted to protect children."},
  recall:{2:"The EU General Product Safety Regulation (applied since December 2024) requires online marketplaces to act on authorities' orders about dangerous products within two working days. In the US, the Consumer Product Safety Commission coordinates recalls and can pursue sellers of recalled products."},
  reviews:{3:"The US FTC's 2024 rule on consumer reviews bans fake reviews and review suppression, with civil penalties. The UK's Digital Markets, Competition and Consumers Act (fake-review rules in force from April 2025) and EU consumer law also ban fake reviews."},
  sanctions:{0:"US sanctions administered by OFAC are strict liability: violations can be penalized even without intent. Blocked or rejected transactions must generally be reported to OFAC within 10 business days."},
  coerced:{1:"In the US, the Senior Safe Act (2018) protects trained financial staff who report suspected elder financial exploitation in good faith, and many states require or allow reports to adult protective services.",
           3:"The UK Financial Conduct Authority's Consumer Duty expects firms to identify customers in vulnerable circumstances and adapt how they treat them."},
  ugcextremism:{1:"GIFCT's hash-sharing database and Content Incident Protocol help platforms block copies of attack-related content quickly. In the EU, the Terrorist Content Online Regulation requires removal within one hour of an authority's order."},
  lootbox:{1:"The FTC's 2022 settlement with Epic Games included $245 million in refunds for design that let children make purchases without parental consent.",
           2:"Belgium treats paid loot boxes as gambling, Australia rates games with paid loot boxes at least M (from September 2024), and Brazil's ECA Digital bans loot boxes for minors."},
  minor:{1:"Adults who pursue a user they know is a minor may be committing enticement offences, which US providers must report to NCMEC under the 2024 REPORT Act.",
         3:"Ofcom does not consider self-declaration of age to be effective age assurance under the UK Online Safety Act."},
  location:{2:"Under the GDPR, a personal data breach must be reported to the regulator within 72 hours, and to affected people without undue delay when the risk is high. Sexual orientation is special-category data needing extra protection."},
  jailbreak:{3:"The EU AI Act requires providers of general-purpose AI models with systemic risk to run adversarial testing and report serious incidents to the EU AI Office."},
  voiceclone:{3:"In 2024 the US FCC ruled that AI-generated voices in robocalls fall under the Telephone Consumer Protection Act. The EU AI Act requires AI-generated or manipulated audio to be disclosed."},
  partyhouse:{2:"Cities increasingly regulate short-term rentals. The EU Short-Term Rental Regulation (applying from May 2026) requires platforms to share activity data with local authorities."},
  fakelisting:{3:"The EU Short-Term Rental Regulation (applying from May 2026) requires hosts to show a registration number and platforms to check it, which is a useful signal against fake listings."},
  ato:{2:"Under the GDPR (Article 33), a personal data breach likely to pose risk must be reported to the regulator within 72 hours. Credential stuffing can count. Most US states also have breach-notification laws with their own triggers."},
  insider:{1:"GDPR breach-notification rules apply to unauthorized access by staff or contractors: 72 hours to notify the regulator, and prompt notice to affected people when the risk is high.",
           3:"The GDPR (Article 28) requires contracts with processors, such as moderation vendors, to include security obligations and audit rights."},
  emergency:{1:"US law (18 U.S.C. § 2702(b)(8)) allows emergency disclosure when there's a good-faith belief of danger of death or serious injury. In the EU, the GDPR permits processing to protect someone's vital interests."},
  bots:{3:"Investors and regulators increasingly scrutinize reported user numbers. Counting fake accounts as real users can become a disclosure problem."},
  vendor:{1:"Courts in Kenya, the US and Europe have heard cases brought by content moderators about working conditions and exposure to traumatic content."},
  bias:{3:"The EU Digital Services Act (Article 34) requires very large platforms to assess risks to fundamental rights, including non-discrimination. The EU AI Act treats some automated decisions, such as creditworthiness, as high-risk."}
};
SCENARIOS.forEach(sc => { const notes = STEP_LAW[sc.id]; if(notes) Object.keys(notes).forEach(i => { if(sc.steps[i] && !sc.steps[i].law) sc.steps[i].law = notes[i]; }); });
