NEW_SCENARIOS.push(
{ id:"emergency", types:ALL_TYPES, tailored:true, title:"The Saturday night emergency", platform:"{platform}", severity:"Sev 1",
  blurb:"Late on a Saturday, {event}. Police then call asking for data without a warrant.",
  vars:{
    all:{platform:"Any platform", event:"a user tells another user they plan to end their life tonight, and it's reported to you"},
    social:{platform:"Social network", event:"a teenager posts that they will end their life tonight, in a post seen only by a few friends"},
    marketplace:{platform:"Online marketplace", event:"a seller messages support saying they've lost everything and plan to end their life tonight"},
    fintech:{platform:"Payments app", event:"a customer who just lost their savings to a scam tells your chat agent they plan to end their life tonight"},
    gaming:{platform:"Online game", event:"a player tells their squad in voice chat that they'll end their life after the match, and a squadmate reports it"},
    dating:{platform:"Dating app", event:"a member tells their match they plan to end their life tonight, and the match reports it"},
    genai:{platform:"AI assistant", event:"a user tells your chatbot they have pills in front of them and plan to take them tonight"},
    gig:{platform:"Delivery platform", event:"a courier messages support after being deactivated, saying they plan to end their life tonight"},
    kids:{platform:"Kids' learning platform", event:"a 13-year-old writes in a class chat that they plan to end their life tonight"}
  },
  steps:[
    { t:"Sat 23:10", h:"A report of imminent risk",
      s:"It's late on a Saturday: {event}. You only know the person's location to city level.",
      o:[ op("Follow your imminent-risk protocol: show crisis resources, escalate to your on-call lead, and refer to emergency services with the information you hold.", "Police carry out a welfare check within the hour. The person is safe and gets support.", [15,8,8,-5], true),
          op("Log it for the Monday queue.", "By Monday, it's too late to help.", [-20,-15,-8,3]),
          op("Suspend the account for breaking the self-harm policy.", "The person loses a connection to help at the worst possible moment.", [-10,-8,0,0]) ],
      lesson:"Imminent-risk reports need a 24/7 protocol. Suspending the person at risk removes help, not harm." },
    { t:"Sat 23:40", h:"Police want more",
      s:"Police call your emergency line asking for the account's phone number, IP address and recent location data, without a warrant.",
      o:[ op("Refuse everything without a court order.", "Police lose valuable time trying to find the person.", [-12,-5,0,0]),
          op("Use your emergency disclosure procedure: verify the officer, share only what's needed to find the person, and document the decision.", "Police find the address quickly, and the disclosure holds up to later review.", [12,5,8,-3], true),
          op("Hand over everything on the account, including message history.", "You disclose far more than needed, which raises privacy and legal problems later.", [5,-5,-8,0]) ],
      lesson:"Most laws allow emergency disclosure when a life is at risk. Verify the request, share the minimum and document everything." },
    { t:"Sun 10:00", h:"Looking after your team",
      s:"The agent who handled the case is shaken. It's their third serious case this month.",
      o:[ op("Thank them and put them back on the queue.", "They go on sick leave two weeks later.", [0,0,0,-10]),
          op("Move all imminent-risk cases to your legal team.", "Lawyers aren't trained for it, and response times slow.", [-8,0,0,-3]),
          op("Offer a debrief and counseling, give them time away from high-severity queues, and check exposure across the team.", "They're back on full duties after a week, and two colleagues take up counseling too.", [3,3,0,8], true) ],
      lesson:"People who handle crisis cases need structured support. It protects them and keeps response quality high." },
    { t:"Week 2", h:"Making the protocol real",
      s:"Your review finds the protocol worked, but only because a senior person happened to be online.",
      o:[ op("Set up a staffed 24/7 on-call rotation, train agents to spot imminent risk, and register an emergency contact channel with police in advance.", "The next case is handled in minutes, on a holiday weekend.", [12,5,8,-5], true),
          op("Write the protocol down in a document.", "Nobody can find it the next time it's needed.", [-3,0,0,0]),
          op("Leave it to whoever is online at the time.", "The next case is missed on a holiday weekend.", [-12,-5,-5,3]) ],
      lesson:"A protocol isn't real until it's staffed, trained and tested outside office hours." }
  ]},
{ id:"bots", types:ALL_TYPES, tailored:true, title:"The bot army", platform:"{platform}", severity:"Sev 2",
  blurb:"40,000 fake accounts sign up overnight to {goal}.",
  vars:{
    all:{platform:"Any consumer platform", goal:"spam and scam your users", harm:"thousands of spam and scam messages", reward:"rewards and messaging"},
    social:{platform:"Social network", goal:"push coordinated political spam", harm:"thousands of posts pushing the same narrative", reward:"reach"},
    marketplace:{platform:"Online marketplace", goal:"post fake reviews and counterfeit listings", harm:"fake five-star reviews on counterfeit goods", reward:"visibility for fake listings"},
    fintech:{platform:"Payments app", goal:"farm $50 sign-up bonuses", harm:"sign-up bonuses paid out to fake accounts", reward:"bonus payouts"},
    gaming:{platform:"Online game", goal:"farm in-game currency and spam sales links", harm:"bots farming currency and spamming sales links in chat", reward:"currency earnings"},
    dating:{platform:"Dating app", goal:"run fake profiles that message members with scam links", harm:"fake profiles messaging members with scam links", reward:"messaging"},
    genai:{platform:"AI platform", goal:"turn free-tier credits into spam and scam content", harm:"millions of AI-written spam messages on your free credits", reward:"free credits"},
    gig:{platform:"Delivery platform", goal:"create fake couriers and customers to farm referral rewards", harm:"fake deliveries claiming referral rewards", reward:"referral payouts"},
    kids:{platform:"Kids' game", goal:"send children links to scam “free currency” sites", harm:"scam links sent to children", reward:"messaging and rewards"}
  },
  steps:[
    { t:"Tue 02:00", h:"A sign-up spike",
      s:"Sign-ups jumped tenfold overnight: 40,000 new accounts from rotating IP addresses, many with similar names. By morning they're being used to {goal}.",
      o:[ op("Delete all 40,000 accounts.", "About 3,000 real people who signed up overnight are deleted too.", [8,-8,0,-3]),
          op("Add bot checks at sign-up now (challenge suspicious traffic, block disposable emails) and quarantine the new accounts pending review.", "Fake sign-ups drop by 90%, and quarantined accounts can't cause harm.", [12,5,3,-5], true),
          op("Wait to see what the accounts do.", "By lunchtime there are {harm}.", [-12,-8,-3,3]) ],
      lesson:"Stop the inflow first with checks at sign-up, then sort real accounts from fake ones before acting." },
    { t:"Tue 11:00", h:"Separating real from fake",
      s:"Your team needs to work out which of the 40,000 accounts are real.",
      o:[ op("Group accounts by device, network, sign-up timing and behavior, remove confirmed bot clusters, and give real people an easy way to verify.", "37,000 bot accounts are removed in a day, and real people verify in seconds.", [12,5,5,-3], true),
          op("Review every account by hand.", "It takes three weeks, and the bots keep going in the meantime.", [-5,0,0,-12]),
          op("Remove every account created from a data-center IP address.", "Many bots get through on residential proxies, and some real people on VPNs are removed.", [5,-5,0,-3]) ],
      lesson:"Bots come in clusters, so signal-based clustering scales. Always give real people a way back." },
    { t:"Wed 10:00", h:"They adapt",
      s:"The attackers switch to slower sign-ups through residential proxies and pay humans to solve your challenges.",
      o:[ op("Put the hardest possible challenge in front of every new user.", "Bots still get through with paid solvers, and real sign-ups fall 20%.", [3,-8,0,0]),
          op("Accept that some bots are inevitable.", "Fake accounts grow back within the month.", [-10,-5,0,3]),
          op("Focus on behavior after sign-up: limit what new accounts can do until they act normally, and tie {reward} to genuine use.", "Bots can still sign up, but they can't do much. The attack stops paying.", [12,5,3,-3], true) ],
      lesson:"When checks at the door stop working, make abuse unprofitable: limit new accounts and reward only genuine use." },
    { t:"Week 2", h:"Counting the cost",
      s:"Finance wants to know the damage, and marketing wants to know why its growth numbers were wrong.",
      o:[ op("Leave the bot accounts in the user numbers.", "Investors later question the numbers.", [0,-10,-5,0]),
          op("Blame the growth team for the promotion that attracted the bots.", "The two teams stop working together.", [0,-3,0,-8]),
          op("Report the full cost, remove bot accounts from growth metrics, and set up a shared dashboard of fake-account rates.", "Leadership now watches fake-account rates alongside growth.", [5,8,5,-3], true) ],
      lesson:"Fake accounts distort every metric. Make the fake-account rate something leadership watches." }
  ]}
);
