/* ---------- Why each scenario: public evidence that the problem is real and common ---------- */
// One fact per scenario, from a primary or authoritative public source, checked against the source page.
// Universal scenarios can carry a company-type fact in byType. Review the list when TT_EVIDENCE_REVIEWED gets old.
const TT_EVIDENCE_REVIEWED = "October 2026";
const TT_EVIDENCE = {
  challenge:{claim:"In Ofcom's late-2025 survey, 30% of UK 11-17-year-olds said they had seen content encouraging them to do dangerous stunts and challenges in the previous four weeks.",
    source:"Ofcom, Children's Online Experiences", url:"https://www.ofcom.org.uk/siteassets/resources/documents/online-safety/research-statistics-and-data/protecting-children/childrens-online-experiences-research-report.pdf", published:"2026-05"},
  gifting:{claim:"In a 2024 Thorn survey of 1,200 US 13-20-year-olds, 1 in 4 said that while under 18 they had been asked online for a sexual image or interaction in exchange for something of value.",
    source:"Thorn, Commodified Sexual Interactions Involving Minors", url:"https://info.thorn.org/hubfs/Research/Thorn_CommodifiedSexualInteractionsInvolvingMinors_Apr2025.pdf", published:"2025-04"},
  companion:{claim:"In Thorn's late-2025 survey of US 9-17-year-olds, 1 in 9 of those who had used an AI chatbot or companion said they had used it for flirty, romantic or sexual conversations.",
    source:"Thorn, Youth Perspectives on Online Safety", url:"https://info.thorn.org/hubfs/Research/Thorn_2025YouthPerspectives_Report.pdf", published:"2026-07"},
  classroom:{claim:"In Thorn's late-2025 survey of US 9-17-year-olds, roughly 1 in 6 (16%) said they had been sent or shown another minor's nude image without that person's consent.",
    source:"Thorn, Youth Perspectives on Online Safety", url:"https://info.thorn.org/hubfs/Research/Thorn_2025YouthPerspectives_Report.pdf", published:"2026-07"},
  comments:{claim:"Meta reported that in 2025 its specialist teams removed nearly 135,000 Instagram accounts for leaving sexualized comments on, or requesting sexual images from, adult-managed accounts featuring children under 13.",
    source:"Meta newsroom", url:"https://about.fb.com/news/2025/07/expanding-teen-account-protections-child-safety-features/", published:"2025-07"},
  minor:{claim:"In Thorn's late-2025 survey of US 9-17-year-olds, about 1 in 6 (16%) said they had used a dating app, though these apps are built for adults.",
    source:"Thorn, Youth Perspectives on Online Safety", url:"https://info.thorn.org/hubfs/Research/Thorn_2025YouthPerspectives_Report.pdf", published:"2026-07"},
  lootbox:{claim:"In January 2025 a popular game's maker agreed to pay $20 million and block under-16s from in-game purchases without parental consent, settling FTC allegations it deceived children about in-game costs and rare-prize odds.",
    source:"US Federal Trade Commission", url:"https://www.ftc.gov/news-events/news/press-releases/2025/01/genshin-impact-game-developer-will-be-banned-selling-lootboxes-teens-under-16-without-parental", published:"2025-01"},
  mules:{claim:"UK banks and payment firms surveyed by the Financial Conduct Authority closed the accounts of 238,396 suspected money mules in 2025, up from 184,935 in 2023; 85,425 were customers aged 25 and under.",
    source:"UK Financial Conduct Authority", url:"https://www.fca.org.uk/news/press-releases/firms-crack-down-money-mules-need-do-more", published:"2026-09"},
  impersonation:{claim:"Americans reported losing nearly $1 billion to business impersonators in 2025, with bank impersonators causing the highest losses. The FTC says the costliest impersonation scams often start with a fake security alert from a bank.",
    source:"US Federal Trade Commission", url:"https://www.ftc.gov/news-events/news/press-releases/2026/06/ftc-data-show-people-reported-losing-3-point-5-billion-imposter-scams-2025", published:"2026-06"},
  sanctions:{claim:"In September 2025, OFAC settled with a crypto exchange that had no program to screen users or transactions for sanctions links. It had made 17,183 exchanges worth $12,570,956 with users in sanctioned countries.",
    source:"US Treasury, OFAC enforcement release", url:"https://ofac.treasury.gov/media/934641/download?inline=", published:"2025-09"},
  coerced:{claim:"US financial institutions filed 155,415 elder financial exploitation reports in one year (June 2022 to June 2023), covering roughly $27 billion in suspicious activity. About 20% involved theft by a trusted person, FinCEN found.",
    source:"FinCEN, elder financial exploitation analysis", url:"https://www.fincen.gov/news/news-releases/fincen-issues-analysis-elder-financial-exploitation", published:"2024-04"},
  romance:{claim:"Cryptocurrency investment fraud cost Americans $7.2 billion in 2025, the largest source of losses the FBI recorded. Scammers often make first contact through dating apps or social media, then move victims to messaging apps.",
    source:"FBI IC3 Annual Report", url:"https://www.ic3.gov/AnnualReport/Reports/2025_IC3Report.pdf", published:"2026-04"},
  offplatform:{claim:"Purchase scams, where buyers pay for goods that never arrive, made up 71% of all authorised push payment scam cases UK banks reported in 2025, with record losses of £118.1 million.",
    source:"UK Finance Annual Fraud Report", url:"https://www.ukfinance.org.uk/system/files/2026-06/UK%20Finance%20Fraud%20Report%202026.pdf", published:"2026-06"},
  voiceclone:{claim:"Victims told the FBI they lost over $5 million in 2025 to 'distress' scams, where voice cloning mimics a loved one in trouble.",
    source:"FBI IC3 Annual Report", url:"https://www.ic3.gov/AnnualReport/Reports/2025_IC3Report.pdf", published:"2026-04"},
  ato:{claim:"In June 2025 the UK's data regulator fined a genetic-testing firm £2.31 million after a credential-stuffing attack, using passwords stolen in unrelated breaches, exposed data on 155,592 UK residents.",
    source:"UK Information Commissioner's Office", url:"https://ico.org.uk/about-the-ico/media-centre/news-and-blogs/2025/06/23andme-fined-for-failing-to-protect-uk-users-genetic-data/", published:"2025-06",
    byType:{
      fintech:{claim:"The FBI logged about 4,700 account takeover complaints with $359.7 million in losses in 2025. It says a single takeover can send 50 or more transfers to accounts at several banks at the same time.",
        source:"FBI IC3 Annual Report", url:"https://www.ic3.gov/AnnualReport/Reports/2025_IC3Report.pdf", published:"2026-04"},
      marketplace:{claim:"UK fraud-prevention body Cifas recorded more than 78,000 account takeover cases in 2025, up 6% on 2024. Online retail accounts were the second most-targeted product, after mobile phones.",
        source:"Cifas, Fraudscape", url:"https://www.cifas.org.uk/newsroom/fraudscape2026", published:"2026-03"}}},
  counterfeit:{claim:"The OECD and EUIPO estimate that trade in counterfeit goods was worth about USD 467 billion in 2021, or 2.3% of global imports. This is their latest estimate, published in 2025.",
    source:"OECD and EUIPO, Mapping Global Trade in Fakes", url:"https://www.oecd.org/content/dam/oecd/en/publications/reports/2025/05/mapping-global-trade-in-fakes-2025_5c812e3c/94d3b29f-en.pdf", published:"2025-05"},
  recall:{claim:"In 2025 the EU's eSurveillance web crawler scanned over 1.6 million websites and found more than 20,800 products for sale online that were already listed as dangerous in the EU Safety Gate alert system.",
    source:"European Commission, Safety Gate report", url:"https://ec.europa.eu/commission/presscorner/detail/en/ip_26_537", published:"2026-03"},
  reviews:{claim:"In December 2025 the FTC warned 10 companies about possible violations of its Consumer Review Rule on deceptive reviews. Each violation can bring a civil penalty of up to $53,088.",
    source:"US Federal Trade Commission", url:"https://www.ftc.gov/news-events/news/press-releases/2025/12/ftc-warns-10-companies-about-possible-violations-agencys-new-consumer-review-rule", published:"2025-12"},
  courier:{claim:"The UK Home Office said in July 2025 that delivery platforms' crackdown on illegal account sharing had already led to thousands being offboarded. It also announced a deal for the platforms to detect shared accounts and suspend them faster.",
    source:"UK Home Office", url:"https://www.gov.uk/government/news/new-operational-partnership-with-delivery-giants-to-combat-illegal-working", published:"2025-07"},
  camera:{claim:"In May 2025 a US House Oversight subcommittee held a hearing on covert surveillance in private spaces. It said these include hotel rooms and short-term rentals.",
    source:"US House Oversight Committee", url:"https://oversight.house.gov/release/hearing-wrap-up-action-needed-to-prevent-covert-surveillance-in-private-spaces", published:"2025-05"},
  partyhouse:{claim:"Airbnb says its anti-party defenses blocked or redirected over 20,000 people from booking entire homes in the US over the July 4 holiday weekend in 2025.",
    source:"Airbnb newsroom", url:"https://news.airbnb.com/airbnbs-anti-party-system-returns-for-july-4-weekend", published:"2026-06"},
  fakelisting:{claim:"UK victims made 6,066 reports of holiday fraud to Action Fraud in 2024 and lost £11,183,957. Police advise that a request to pay by bank transfer can be a sign of fraud.",
    source:"Action Fraud (City of London Police)", url:"https://www.atol.org/news-and-blogs/2025/02/24/dont-let-fraudsters-trip-you-up-this-summer-new-alert-issued-as-people-look-to-snap-up-online-holiday-deals/", published:"2025-02"},
  assault:{claim:"A peer-reviewed study of 3,413 sexual assault forensic exam records from one US state (2017-2020) found that assaults after a dating-app meeting made up 8.02% of all cases and 13.92% of acquaintance assaults.",
    source:"Journal of Interpersonal Violence", url:"https://doi.org/10.1177/08862605221130390", published:"2022-10"},
  location:{claim:"Peer-reviewed security researchers who tested 15 location-based dating apps found that 6 of them let someone pinpoint a user's exact location (USENIX Security 2024).",
    source:"USENIX Security Symposium", url:"https://www.usenix.org/conference/usenixsecurity24/presentation/dhondt", published:"2024-08"},
  rfi:{claim:"In February 2026 the European Commission preliminarily found a major video platform in breach of the EU Digital Services Act over addictive design, including its personalised recommender system; confirmed breaches can bring fines up to 6% of worldwide annual turnover.",
    source:"European Commission", url:"https://ec.europa.eu/commission/presscorner/detail/en/ip_26_312", published:"2026-02"},
  vip:{claim:"The Oversight Board reported in 2022 that, under a major social network's cross-check program for high-profile users, decisions on flagged content took about 12 days on average for US users; one item waited 222 days.",
    source:"Oversight Board", url:"https://www.oversightboard.com/wp-content/uploads/2026/03/512630074120983.pdf", published:"2022-12"},
  swatting:{claim:"A California teenager sentenced in February 2025 made over 375 swatting and threat calls between August 2022 and January 2024 and advertised swatting-for-a-fee on social media, the US Justice Department said.",
    source:"US Department of Justice", url:"https://www.justice.gov/opa/pr/california-teenager-sentenced-48-months-prison-nationwide-swatting-spree", published:"2025-02"},
  ugcextremism:{claim:"In a November 2025 action on gaming and gaming-related platforms, Europol and eight countries referred about 5,408 jihadist and 1,070 violent right-wing extremist links; Europol says perpetrators re-enact terrorist attacks and school shootings in 3D gameplay.",
    source:"Europol", url:"https://www.europol.europa.eu/media-press/newsroom/news/europol-and-partner-countries-combat-online-radicalisation-gaming-platforms", published:"2025-11"},
  deepfake:{claim:"OpenAI estimated that in the month before the 2024 US presidential election, ChatGPT rejected over 250,000 requests to generate DALL-E images of the presidential and vice-presidential candidates and President Biden.",
    source:"OpenAI", url:"https://openai.com/index/how-openai-is-approaching-2024-worldwide-elections/", published:"2024-11"},
  jailbreak:{claim:"The UK AI Security Institute, which has studied more than 30 frontier AI systems, reported in December 2025 that it had found universal jailbreaks, which reliably extract policy-violating information, for every system it tested.",
    source:"UK AI Security Institute", url:"https://www.aisi.gov.uk/frontier-ai-trends-report", published:"2025-12"},
  insider:{claim:"In 2023 the FTC charged a home security camera company with letting any employee or contractor access customers' private videos; one employee viewed thousands of recordings from bedrooms and bathrooms. The order required $5.8 million in refunds.",
    source:"US Federal Trade Commission", url:"https://www.ftc.gov/news-events/news/press-releases/2023/05/ftc-says-ring-employees-illegally-surveilled-customers-failed-stop-hackers-taking-control-users", published:"2023-05",
    byType:{
      fintech:{claim:"In May 2025 a major US crypto exchange disclosed that criminals had paid support contractors and employees outside the US to pull customer data from internal systems; it estimated costs of $180 million to $400 million.",
        source:"Coinbase SEC filing", url:"https://www.sec.gov/Archives/edgar/data/1679788/000167978825000094/coin-20250514.htm", published:"2025-05"}}},
  emergency:{claim:"In the second half of 2025, Snapchat received 3,081 emergency disclosure requests from US law enforcement and produced some data in 67.7% of them.",
    source:"Snap transparency report", url:"https://values.snap.com/privacy/transparency/legal-requests-h2-2025", published:"2026"},
  bots:{claim:"Between April 2024 and April 2025, Microsoft blocked about 1.6 million bot sign-up attempts per hour across its services.",
    source:"Microsoft Cyber Signals", url:"https://www.microsoft.com/en-us/security/blog/2025/04/16/cyber-signals-issue-9-ai-powered-deception-emerging-fraud-threats-and-countermeasures/", published:"2025-04",
    byType:{
      social:{claim:"Meta took action on 1.1 billion fake Facebook accounts in Q4 2025, up from 692 million in Q3, and estimates fake accounts were about 5% of Facebook's worldwide daily active people in Q4 2025.",
        source:"Meta, EU disinformation code report", url:"https://disinfocode.eu/reports/meta/8?commitmentId=388&chapterId=80", published:"2026-03"},
      dating:{claim:"Match Group's dating apps in the EU banned or suspended 6,962,890 spam, inauthentic and ineligible accounts in 2025, 94% detected proactively, with about 18 million monthly users in the region.",
        source:"Match Group, EU DSA transparency report", url:"https://cdn.prod.website-files.com/67c577f5d5cf176437c09b66/69a37a67639b2e8238609323_MG-DSA%20Safe%20Dating%20Report%20-%202025%20-%20FINAL.pdf", published:"2026-02"}}},
  vendor:{claim:"When the pandemic cut human review capacity in 2020, YouTube relied on automated systems: removals more than doubled versus the prior quarter, and the share of appealed videos reinstated rose from 25% to 50%.",
    source:"YouTube Official Blog", url:"https://blog.youtube/inside-youtube/responsible-policy-enforcement-during-covid-19/", published:"2020-08",
    byType:{
      social:{claim:"Meta reported that after sending content reviewers home in March 2020, it took action on fewer pieces of suicide and self-injury content on Facebook and Instagram, and less child nudity and sexual exploitation on Instagram.",
        source:"Meta Community Standards Enforcement Report", url:"https://about.fb.com/news/2020/08/community-standards-enforcement-report-aug-2020/", published:"2020-08"}}},
  bias:{claim:"NIST's test of 189 face recognition algorithms from 99 developers found higher false-positive rates for Asian and African American faces in one-to-one matching, often by a factor of 10 to 100, depending on the algorithm.",
    source:"NIST face recognition test", url:"https://www.nist.gov/news-events/news/2019/12/nist-study-evaluates-effects-race-age-sex-face-recognition-software", published:"2019-12",
    byType:{
      social:{claim:"A 2019 peer-reviewed study found that hate speech detection models labeled tweets written in African American English, and tweets by self-identified African Americans, as offensive up to two times more often than others.",
        source:"ACL 2019, Sap et al.", url:"https://aclanthology.org/P19-1163/", published:"2019-07"},
      genai:{claim:"A 2025 peer-reviewed study found that reward models used to align large language models were 4% less accurate on average with African American Language than with White Mainstream English, and often dispreferred AAL texts.",
        source:"NAACL Findings 2025, Mire et al.", url:"https://aclanthology.org/2025.findings-naacl.417/", published:"2025"},
      gig:{claim:"In 2024 the UK's equality regulator announced a financial settlement for a food delivery courier who alleged racially discriminatory facial recognition checks; he had been removed from the platform after a failed check and an automated process.",
        source:"UK Equality and Human Rights Commission", url:"https://www.equalityhumanrights.com/news/news/uber-eats-courier-wins-payout-help-equality-watchdog-after-facing-problematic-ai-checks", published:"2024-03"}}},
  takedown:{claim:"Freedom on the Net 2025 found people in at least 57 of 72 countries were arrested or imprisoned for online expression, a record high, and 69% of internet users live where political, social or religious content was blocked.",
    source:"Freedom House, Freedom on the Net", url:"https://freedomhouse.org/sites/default/files/2025-11/Freedom_on_the_Net_2025_Digital.pdf", published:"2025-11",
    byType:{
      genai:{claim:"Freedom House reports that AI governance frameworks in China and Vietnam require generative AI chatbots to follow the Communist Party line on sensitive topics.",
        source:"Freedom House, Freedom on the Net", url:"https://freedomhouse.org/sites/default/files/2025-11/Freedom_on_the_Net_2025_Digital.pdf", published:"2025-11"}}},
  newlaw:{claim:"In 2025, over 45 US states and Puerto Rico introduced more than 300 bills on social media and children, and at least 20 states enacted new laws, according to the National Conference of State Legislatures.",
    source:"National Conference of State Legislatures", url:"https://www.ncsl.org/technology-and-communication/social-media-and-children-2025-legislation", published:"2025-10",
    byType:{
      social:{claim:"From 25 July 2025, the UK Online Safety Act requires age checks such as facial scans or photo ID before children reach the most harmful content; fines reach 10% of global revenue or 18 million pounds, whichever is greater.",
        source:"GOV.UK", url:"https://www.gov.uk/government/news/whats-changing-for-children-on-social-media-from-25-july-2025", published:"2025-07"},
      dating:{claim:"Under the UK Online Safety Act, in-scope services had to finish illegal-content risk assessments by 16 March 2025, and companies can be fined up to 18 million pounds or 10% of qualifying worldwide revenue, whichever is greater.",
        source:"GOV.UK, Online Safety Act explainer", url:"https://www.gov.uk/government/publications/online-safety-act-explainer/online-safety-act-explainer", published:"2025-04"},
      genai:{claim:"The EU AI Act's transparency rules, which the European Commission said would take effect in August 2026, require that people using AI systems such as chatbots be told they are interacting with a machine.",
        source:"European Commission, AI Act", url:"https://digital-strategy.ec.europa.eu/en/policies/regulatory-framework-ai", published:"2026"},
      kids:{claim:"The FTC's January 2025 update to the COPPA Rule requires separate verifiable parental consent before sharing children's data with third parties for targeted advertising, limits data retention, and gives companies one year to comply.",
        source:"US Federal Trade Commission", url:"https://www.ftc.gov/news-events/news/press-releases/2025/01/ftc-finalizes-changes-childrens-privacy-rule-limiting-companies-ability-monetize-kids-data", published:"2025-01"},
      fintech:{claim:"Since October 2025, EU instant payment rules require payment providers to offer payee verification, so a payee's name must match the IBAN; the European Commission says this helps prevent mistakes and scams.",
        source:"European Commission", url:"https://finance.ec.europa.eu/news/new-eu-rules-make-instant-euro-payments-faster-and-safer-2025-10-10_en", published:"2025-10"},
      marketplace:{claim:"The EU General Product Safety Regulation requires online marketplaces active in the EU to register in the Safety Gate Portal and name a single point of contact; more than 1,200 had registered by the end of 2025.",
        source:"European Commission", url:"https://commission.europa.eu/news-and-media/news/increased-action-against-dangerous-products-eu-2025-2026-03-09_en", published:"2026-03"},
      gaming:{claim:"Brazil's Digital Statute of Children and Adolescents (ECA Digital) bans loot boxes in games for children and teenagers, the Brazilian Senate's news service reported in March 2026.",
        source:"Brazilian Senate news service", url:"https://www12.senado.leg.br/radio/1/noticia/2026/03/27/eca-digital-proibe-rolagem-infinita-e-caixa-de-recompensa-em-games-infantojuvenis", published:"2026-03"},
      gig:{claim:"The EU Platform Work Directive, adopted in 2024, gives people working through platforms the right to an explanation of any decision taken or supported by an automated system, without undue delay.",
        source:"EU Platform Work Directive", url:"https://data.consilium.europa.eu/doc/document/PE-89-2024-INIT/en/pdf", published:"2024-10"}}}
};
function ttWhy(sc, type){ const e = sc && TT_EVIDENCE[sc.id]; if(!e) return null; return (e.byType && e.byType[type]) || e; }
