NEW_SCENARIOS.push(
{ id:"takedown", types:ALL_TYPES, tailored:true, title:"The takedown order", platform:"{platform}", severity:"Sev 2",
  blurb:"A government orders you to {demand} within 24 hours, citing a vague national security law.",
  vars:{
    all:{platform:"Any global platform", demand:"remove content criticizing its officials", item:"content"},
    social:{platform:"Social network", demand:"remove posts by journalists criticizing a government minister", item:"posts"},
    marketplace:{platform:"Online marketplace", demand:"remove listings for T-shirts with protest slogans", item:"listings"},
    fintech:{platform:"Payments app", demand:"freeze the accounts of a protest group's organizers", item:"accounts"},
    gaming:{platform:"Game with user-built worlds", demand:"remove a player-built memorial to protesters", item:"player creations"},
    dating:{platform:"Dating app", demand:"remove profiles that identify as LGBTQ", item:"profiles"},
    genai:{platform:"AI assistant", demand:"stop the model discussing a historical massacre", item:"answers"},
    gig:{platform:"Rides and delivery platform", demand:"block drivers' in-app messages about a planned strike", item:"messages"},
    kids:{platform:"Kids' learning platform", demand:"remove lessons about climate change for students in the country", item:"lessons"}
  },
  steps:[
    { t:"Tue 09:00", h:"An official order arrives",
      s:"A ministry in a country where you have local staff orders you to {demand} within 24 hours. It cites a broadly worded national security law and hints at “consequences” for your staff.",
      o:[ op("Comply immediately and in full to protect your staff.", "The demands expand the following week, and users learn you complied quietly.", [-8,-12,-3,5]),
          op("Have lawyers review the order's legal basis and scope, assess the human-rights impact, and work out what the law strictly requires.", "Your lawyers find the order goes further than the law allows. You have options.", [5,5,8,-5], true),
          op("Ignore it.", "Your local office is raided and staff are questioned.", [0,-3,-10,-15]) ],
      lesson:"Handle government orders through a consistent process: check the legal basis and scope, and assess the human-rights impact before acting.",
      law:"The Global Network Initiative Principles and the UN Guiding Principles on Business and Human Rights expect companies to read government demands narrowly and challenge overbroad ones. Under the EU Digital Services Act (Article 9), orders from EU authorities must state their legal basis and territorial scope." },
    { t:"Tue 16:00", h:"Protecting people",
      s:"Legal says the order is overbroad, but your local staff face real risk.",
      o:[ op("Remove it worldwide to avoid trouble.", "People everywhere lose access to legitimate {item}, and you're criticized for censorship.", [-5,-12,-3,3]),
          op("Pull your local staff out of the country overnight.", "Staff lose their jobs, and some can't leave safely.", [0,-5,0,-10]),
          op("Restrict access only in that country and only where the law clearly applies, and formally challenge the rest.", "The {item} stay available elsewhere, staff are protected, and you keep your legal position.", [8,5,8,-3], true) ],
      lesson:"Restrict only what you're legally required to, only where it's required, and keep staff safety central to the plan.",
      law:"Restricting content in one country, rather than removing it globally, is standard practice for local-law demands. Record these restrictions in your transparency reporting." },
    { t:"Wed 10:00", h:"Telling the people affected",
      s:"The people whose {item} are affected don't know about the order.",
      o:[ op("Tell them what was restricted and why, unless the law forbids it, and explain how they can challenge it.", "They can challenge the decision, and trust holds.", [5,10,5,-3], true),
          op("Say nothing, to avoid provoking the government.", "People assume arbitrary censorship, and trust falls.", [0,-10,0,0]),
          op("Post the order publicly on social media.", "The government retaliates against your staff.", [0,3,-5,-10]) ],
      lesson:"Tell affected people where the law allows. It's a core part of accountability for government demands.",
      law:"The EU Digital Services Act (Article 17) requires a statement of reasons whenever content or accounts are restricted, including restrictions made because of a government order." },
    { t:"Month 2", h:"Being accountable",
      s:"Civil-society groups ask how you handle government demands.",
      o:[ op("Keep government requests confidential.", "A leak reveals both the requests and your silence.", [0,-12,-3,0]),
          op("Publish government requests in a transparency report, including how many you complied with, narrowed or refused.", "Researchers and advocates cite your report as a model.", [3,10,8,-3], true),
          op("Say you never comply with government requests.", "It isn't true, and it's quickly disproved.", [0,-15,-5,0]) ],
      lesson:"Transparency reporting on government demands builds trust and discourages overreach.",
      law:"The EU Digital Services Act (Articles 15 and 24) requires transparency reports that include the orders received from authorities." }
  ]},
{ id:"newlaw", types:ALL_TYPES, tailored:true, title:"The new law", platform:"{platform}", severity:"Sev 3",
  blurb:"You launch in a market covered by {law} in 90 days, and nobody has started on compliance.",
  vars:{
    all:{platform:"Any platform", law:"a new online safety law", duty:"assess risks to users and put proportionate protections in place", change:"new safety defaults", regulator:"The regulator",
      lawnote:"Most new online safety laws are enforced by a dedicated regulator that can fine a percentage of global turnover."},
    social:{platform:"Social network", law:"the UK Online Safety Act's children's safety duties", duty:"complete a children's risk assessment and use highly effective age assurance to keep children away from the most harmful content", change:"age checks and safer feeds for teens", regulator:"Ofcom",
      lawnote:"Ofcom's children's safety codes have applied since July 2025. Breaches of the Online Safety Act can be fined up to £18 million or 10% of qualifying worldwide revenue, whichever is higher."},
    marketplace:{platform:"Online marketplace", law:"the EU General Product Safety Regulation", duty:"register a single contact point for product safety, act on authorities' orders within two working days, and make sellers show safety information on listings", change:"mandatory product-safety fields on listings", regulator:"Market surveillance authorities",
      lawnote:"The EU General Product Safety Regulation has applied since December 2024. Online marketplaces must act on authorities' orders about dangerous products within two working days."},
    fintech:{platform:"Payments app", law:"the EU Instant Payments Regulation's Verification of Payee rules", duty:"check the payee's name against the account before every euro transfer and show the customer the result", change:"a name check before every transfer", regulator:"Your financial regulator",
      lawnote:"Under the EU Instant Payments Regulation, Verification of Payee has been mandatory for euro credit transfers since October 2025. A provider that skips the check can be liable for the resulting loss."},
    gaming:{platform:"Mobile game", law:"Brazil's Digital Statute of Children and Adolescents (ECA Digital)", duty:"stop offering paid loot boxes to minors, add parental supervision tools and verify ages beyond self-declaration", change:"removing loot boxes for younger players", regulator:"Brazilian authorities",
      lawnote:"Brazil's ECA Digital, enacted in 2025, bans loot boxes in games aimed at or likely to be accessed by children and requires age verification beyond self-declaration."},
    dating:{platform:"Dating app", law:"the UK Online Safety Act's illegal harms duties", duty:"assess and reduce the risk of priority offences such as fraud on your service, and act quickly on illegal content", change:"scam detection and blurred images by default", regulator:"Ofcom",
      lawnote:"Ofcom's illegal harms codes have applied since March 2025. Fraud is a priority offence, cyberflashing is a criminal offence, and breaches can be fined up to £18 million or 10% of qualifying worldwide revenue."},
    genai:{platform:"AI assistant", law:"the EU AI Act's transparency rules", duty:"tell people when they're talking to an AI and mark AI-generated content in a machine-readable way", change:"AI disclosure labels and content marking", regulator:"AI regulators",
      lawnote:"The EU AI Act's transparency obligations (Article 50) apply from August 2026. Breaches can be fined up to €15 million or 3% of global turnover."},
    gig:{platform:"Delivery platform", law:"the EU Platform Work Directive", duty:"give workers human review of significant automated decisions such as deactivations, and explain how algorithms affect their work", change:"human review before deactivations", regulator:"Labour authorities",
      lawnote:"EU countries must apply the Platform Work Directive by December 2026. It bars platforms from deactivating workers based solely on automated decisions."},
    kids:{platform:"Kids' learning app", law:"the updated US COPPA Rule", duty:"get separate parental consent before sharing children's data for advertising, and keep a written data-retention policy", change:"new parental consent steps", regulator:"The FTC",
      lawnote:"The FTC's updated COPPA Rule required compliance by April 2026. Each violation can bring a civil penalty of more than $50,000."}
  },
  steps:[
    { t:"Day 1", h:"90 days to comply",
      s:"You launch in a market covered by {law} in 90 days. You'll need to {duty}. Nobody has started.",
      o:[ op("Wait for the regulator to publish more detailed guidance.", "Guidance arrives with 30 days to go, and everything is rushed.", [0,-3,-8,-5]),
          op("Ask engineering to build whatever seems necessary.", "They build the wrong things, and the real gaps remain.", [0,0,-5,-8]),
          op("Run a gap assessment against each requirement, give every gap an owner, and set a delivery plan with milestones.", "By week two you know exactly what's missing.", [5,3,10,-3], true) ],
      lesson:"Compliance starts with a gap assessment against specific requirements, each with a named owner.",
      law:"{lawnote}" },
    { t:"Day 30", h:"The product trade-off",
      s:"Product says {change} will cut engagement by 5% and asks to do the bare minimum.",
      o:[ op("Design it to meet the law's intent, measure the impact honestly, and look for ways to reduce friction.", "The impact ends up at 2%, and the design holds up to review.", [8,5,8,-3], true),
          op("Do the minimum that technically complies.", "The regulator's first review finds it doesn't meet the law's intent.", [-3,-5,-8,3]),
          op("Delay the launch in that market.", "Competitors who complied take the market.", [0,-5,0,0]) ],
      lesson:"Regulators judge whether you meet a law's purpose, not just its wording. Good design reduces the cost.",
      law:"Regulators increasingly assess outcomes. The UK Online Safety Act, the EU DSA and the EU AI Act all expect measures to be effective in practice, not only present on paper." },
    { t:"Day 70", h:"The paper trail",
      s:"{regulator} can ask for evidence of how you comply.",
      o:[ op("Rely on the product itself as evidence.", "When asked, you can't show how decisions were made.", [0,0,-8,3]),
          op("Document your risk assessment, decisions, testing and results in a form you could hand to a regulator.", "A later information request is answered in days.", [3,3,12,-5], true),
          op("Have consultants write documentation after launch.", "It doesn't match what you built.", [0,-3,-5,-3]) ],
      lesson:"If it isn't documented, regulators will assume it wasn't done.",
      law:"Record-keeping is built into most of these laws: the Online Safety Act requires written risk assessments, and the EU AI Act and GPSR require technical documentation." },
    { t:"Day 90+", h:"After the deadline",
      s:"You've launched. What keeps you compliant from here?",
      o:[ op("Treat the project as finished.", "Six months later, product changes have quietly broken compliance.", [-5,-3,-10,3]),
          op("Freeze the product in that market.", "You fall behind competitors.", [0,-5,0,0]),
          op("Build compliance checks into product reviews, monitor key metrics, and review the risk assessment at least once a year.", "Compliance holds as the product changes.", [5,5,10,-3], true) ],
      lesson:"Compliance is an ongoing program tied to product change, not a one-off project.",
      law:"Several of these laws require reassessment when your service changes significantly, not only on a fixed schedule." }
  ]}
);
