NEW_SCENARIOS.push(
/* ===== Marketplace (more) ===== */
{ id:"recall", types:["marketplace"], title:"The recalled toy", platform:"Online marketplace", severity:"Sev 1",
  blurb:"A toddler is hospitalized after swallowing magnets from a toy bought on your marketplace. The toy was recalled months ago.",
  steps:[
    { t:"Thu 08:00", h:"A child is hurt",
      s:"A parent reports their toddler was hospitalized after swallowing small, powerful magnets from a toy bought on your marketplace. Regulators recalled the toy four months ago, and 300 listings from 40 sellers are still live.",
      o:[ op("Remove the one listing the parent bought from.", "The other 299 listings keep selling.", [-12,-8,-8,3]),
          op("Remove every listing matching the recalled product, stop pending orders, and contact the parent to offer support.", "Every matching listing is down by noon, and 60 pending orders are stopped before shipping.", [15,8,8,-5], true),
          op("Ask sellers to confirm their stock isn't the recalled version.", "Most don't reply, and sales continue for a week.", [-8,-5,-5,0]) ],
      lesson:"When a product can hurt children, remove first and verify later. One report usually points to many listings." },
    { t:"Thu 14:00", h:"Buyers who already have it",
      s:"2,100 people bought the toy in the past four months. Many are parents of young children.",
      o:[ op("Email past buyers directly with the recall notice, how to get a refund, and what to do if a child may have swallowed a magnet.", "Parents return the toy, and a poison-control center thanks you for the clear guidance.", [15,10,8,-3], true),
          op("Post the recall notice in your help center.", "Almost none of the buyers see it.", [-5,-3,-5,0]),
          op("Leave it to the manufacturer to contact buyers.", "The manufacturer doesn't have buyers' contact details. You do.", [-10,-8,-5,3]) ],
      lesson:"Marketplaces often hold the only contact details for buyers. Use them to reach people when there's a safety recall." },
    { t:"Fri 10:00", h:"Why didn't you catch it?",
      s:"The consumer-safety regulator asks why recalled products were still listed four months after the recall.",
      o:[ op("Say sellers are responsible for what they list.", "The regulator reminds you of your own obligations and opens an inquiry.", [0,-8,-12,0]),
          op("Explain honestly, and commit to checking listings against official recall databases daily, with automatic removal of matches.", "The regulator accepts the plan and schedules a follow-up.", [10,5,10,-5], true),
          op("Promise to review every listing by hand.", "It's impossible at your scale, and the regulator knows it.", [0,-5,-5,-8]) ],
      lesson:"Checking listings against official recall databases is a basic control for any marketplace selling physical goods." },
    { t:"Month 2", h:"High-risk categories",
      s:"Children's products, electronics and cosmetics account for most of your safety incidents.",
      o:[ op("Treat all categories the same.", "The next incident is another children's product.", [-8,-5,-5,3]),
          op("Stop selling children's products entirely.", "Legitimate sellers leave, and buyers go elsewhere.", [5,-8,0,0]),
          op("Require safety certificates from sellers in high-risk categories, and screen new listings in those categories before they go live.", "Unsafe listings in those categories drop sharply.", [12,5,8,-5], true) ],
      lesson:"Put your strongest controls on the categories where products can physically hurt people." }
  ]},
{ id:"reviews", types:["marketplace"], title:"The review factory", platform:"Online marketplace", severity:"Sev 2",
  blurb:"A competitor sends proof that a rival seller is paying for thousands of five-star reviews through a private group.",
  steps:[
    { t:"Mon 10:00", h:"A competitor's evidence",
      s:"A seller sends screenshots of a private group where people are paid $10, refunded after posting, for each five-star review of a rival seller's products. About 3,000 reviews look connected.",
      o:[ op("Ignore it: competitors complain about each other all the time.", "The scheme grows, and a consumer group publishes the same screenshots.", [-8,-10,-8,3]),
          op("Investigate the reviews using purchase patterns, refunds and reviewer networks, and freeze the rival's ratings while you do.", "Within two days you confirm 2,600 paid reviews.", [8,5,8,-5], true),
          op("Suspend the rival seller immediately on the competitor's word.", "Some screenshots turn out to be fabricated, and the seller sues.", [0,-8,-3,-3]) ],
      lesson:"Tips from competitors are useful but aren't proof. Investigate with your own data before acting." },
    { t:"Wed 11:00", h:"Confirmed",
      s:"The evidence is clear: 2,600 reviews were paid for, and the seller made $400,000 from the boosted sales.",
      o:[ op("Remove the fake reviews, suspend the seller, and hold their payouts while you decide on refunds.", "The listings drop out of the rankings, and money is held back for affected buyers.", [10,8,8,-3], true),
          op("Remove the fake reviews but keep the seller.", "The seller buys a new batch of reviews next month.", [-5,-5,-5,0]),
          op("Leave the reviews up and warn the seller.", "Buyers keep relying on fake ratings.", [-8,-8,-8,0]) ],
      lesson:"Paid reviews defraud buyers. Remove them and act against the account that paid for them." },
    { t:"Thu 09:00", h:"The reviewers",
      s:"Most of the 900 reviewers are real people who were paid. Some post paid reviews for many sellers.",
      o:[ op("Ban all 900 reviewers.", "Many were one-off participants, and you lose real customers.", [3,-5,0,-3]),
          op("Remove their reviews, ban the repeat reviewers who work for many sellers, and warn one-time participants.", "The professional reviewers are gone, and most one-time participants stop.", [10,3,5,-3], true),
          op("Take no action against reviewers.", "The same reviewers are hired by other sellers next week.", [-8,-3,-3,3]) ],
      lesson:"Tell professional review farms apart from one-off participants, and act in proportion." },
    { t:"Month 2", h:"Preventing the next scheme",
      s:"Fake reviews are now banned by consumer-protection law in the US, UK and EU, with fines attached.",
      o:[ op("Let only verified buyers review, detect review bursts and refund patterns, and publish your review policy.", "Paid-review schemes become much harder, and regulators see a documented program.", [10,8,10,-3], true),
          op("Hide review counts.", "Buyers trust the ratings even less.", [0,-8,0,0]),
          op("Rely on buyers to report fake reviews.", "Most fake reviews are never reported.", [-5,-3,-5,3]) ],
      lesson:"Review integrity is now a legal requirement in many markets, not only a quality issue." }
  ]},
/* ===== Fintech (more) ===== */
{ id:"sanctions", types:["fintech"], title:"The sanctions near-miss", platform:"Payments and crypto app", severity:"Sev 2",
  blurb:"Customers have been sending money to crypto wallets that were just added to a sanctions list, and three transfers are pending.",
  steps:[
    { t:"Tue 08:00", h:"A new sanctions listing",
      s:"Twelve crypto wallets were added to the US sanctions list overnight. Customers sent $2.4 million to two of them in the past month, and three transfers to them are pending right now.",
      o:[ op("Block the pending transfers, freeze the accounts involved while you review, and escalate to your compliance officer.", "No new money reaches the sanctioned wallets, and compliance begins its review within the hour.", [10,3,12,-5], true),
          op("Let the pending transfers go through: they started before the listing.", "They complete after the listing took effect, which is itself a violation.", [-5,-5,-15,0]),
          op("Close every account that has ever sent crypto.", "Thousands of legitimate customers lose access, and complaints flood in.", [3,-12,0,-8]) ],
      lesson:"Sanctions apply from the moment of listing. Screen against updates in near real time and stop pending payments." },
    { t:"Tue 13:00", h:"Do you report it?",
      s:"Compliance confirms the earlier transfers happened before the listing, but the pending ones were blocked after it.",
      o:[ op("File the required reports on the blocked transfers within the deadline, with a clear timeline.", "The regulator acknowledges the report and takes no further action.", [5,5,12,-3], true),
          op("Say nothing, because no money reached the wallets.", "A later audit finds the unreported blocks, and the penalty is worse for the silence.", [0,-5,-12,0]),
          op("Report everything to every regulator worldwide.", "It creates confusion and extra work with no benefit.", [0,0,0,-5]) ],
      lesson:"Blocked sanctioned transactions often have to be reported too. Know the reporting duties everywhere you operate." },
    { t:"Wed 10:00", h:"The customers",
      s:"Two of the frozen customers look like legitimate small businesses, and one was a victim of a scam run through the sanctioned wallet.",
      o:[ op("Keep everyone frozen indefinitely.", "Legitimate businesses can't pay staff, and complaints reach the regulator.", [0,-10,-3,0]),
          op("Review each case quickly, unfreeze clearly legitimate customers, and help the scam victim report to police.", "Legitimate customers are back within days, and the scam victim thanks you.", [5,10,5,-5], true),
          op("Unfreeze everyone to reduce complaints.", "One of them turns out to be linked to the sanctioned network.", [-8,0,-10,3]) ],
      lesson:"Sanctions freezes need fast case-by-case review, so legitimate customers aren't punished for a match." },
    { t:"Month 2", h:"The screening gap",
      s:"Your screening checked customers at sign-up, but never the addresses they send money to.",
      o:[ op("Keep screening customers only at sign-up.", "The same gap is exploited again.", [-5,0,-10,3]),
          op("Screen every outgoing payment against updated sanctions lists, and use blockchain analytics for crypto addresses.", "The next listing is caught automatically within minutes.", [10,3,12,-5], true),
          op("Stop supporting crypto transfers.", "Customers leave for competitors.", [3,-8,0,0]) ],
      lesson:"Sanctions screening has to cover transactions and counterparties, not just customers at sign-up." }
  ]},
{ id:"coerced", types:["fintech"], title:"The coerced customer", platform:"Retail bank app", severity:"Sev 2",
  blurb:"A live-in carer appears to be draining an 84-year-old customer's account, and she insists everything is fine.",
  steps:[
    { t:"Mon 11:00", h:"A worrying pattern",
      s:"An 84-year-old customer's account shows $38,000 in new cash withdrawals and transfers to a new payee over six weeks. A new phone number and email were added last month. The payee is her live-in carer.",
      o:[ op("Do nothing: she authorized the payments.", "The account is nearly empty two weeks later.", [-12,-8,-5,3]),
          op("Pause large transfers to the new payee, and have a trained specialist call her alone on her original phone number.", "On the call, she mentions being frightened of the carer.", [12,8,5,-5], true),
          op("Close the account to stop the losses.", "She loses access to her pension and bills, and the carer opens a new account elsewhere.", [3,-10,-3,0]) ],
      lesson:"Financial abuse of older people often hides behind “authorized” payments. Talk to the customer alone, through a channel you trust." },
    { t:"Mon 16:00", h:"She won't make a complaint",
      s:"She's frightened, but won't report the carer, who is her only help at home.",
      o:[ op("With her consent, involve adult protective services, add extra checks on large payments, and give her a named contact at the bank.", "Social services arrange other care, and the transfers stop.", [12,10,8,-5], true),
          op("Respect her decision and do nothing more.", "The abuse continues.", [-10,-5,-3,0]),
          op("Report the carer to police without telling her.", "She feels betrayed and stops talking to you.", [3,-8,0,0]) ],
      lesson:"Respect the customer's choices while reducing harm: involve safeguarding services and add protections with her agreement." },
    { t:"Tue 10:00", h:"The carer calls",
      s:"The carer calls, angry that payments are blocked, and says he has power of attorney.",
      o:[ op("Take his word for it and unblock the payments.", "He has no such document.", [-10,-5,-5,0]),
          op("Tell him you suspect abuse.", "He becomes aggressive toward her at home.", [-8,-5,0,0]),
          op("Ask for the legal document and have your legal team verify it before changing anything.", "The document doesn't exist.", [10,5,5,-3], true) ],
      lesson:"Verify any claimed legal authority, and never share your suspicions with a suspected abuser." },
    { t:"Month 2", h:"A vulnerable-customer policy",
      s:"Your team realizes there's no process for spotting or handling financial abuse.",
      o:[ op("Rely on staff judgment.", "The next case goes unnoticed.", [-5,0,-3,3]),
          op("Create a vulnerable-customer policy with abuse indicators, trained specialists, trusted-contact options and links to local safeguarding services.", "The team spots three more cases the following quarter.", [10,8,8,-5], true),
          op("Block all transfers for customers over 80.", "It's discriminatory, and customers complain.", [0,-10,-5,0]) ],
      lesson:"Financial abuse needs a defined process: warning signs, trained staff and trusted contacts the customer chooses." }
  ]}
);
