NEW_SCENARIOS.push(
{ id:"vendor", types:ALL_TYPES, tailored:true, title:"The vendor goes dark", platform:"{platform}", severity:"Sev 2",
  blurb:"A typhoon takes your moderation vendor's main site offline. 60% of your reviewers are gone for a week and {queue} are piling up.",
  vars:{
    all:{platform:"Any platform", queue:"reports of harmful content", urgent:"the most urgent reports"},
    social:{platform:"Social network", queue:"reports of harassment, hate and graphic content", urgent:"child-safety and threat reports"},
    marketplace:{platform:"Online marketplace", queue:"flagged listings and buyer disputes", urgent:"dangerous-product and fraud reports"},
    fintech:{platform:"Payments app", queue:"fraud alerts and account reviews", urgent:"live fraud and scam alerts"},
    gaming:{platform:"Online game", queue:"player reports of cheating, harassment and grooming", urgent:"grooming and threat reports"},
    dating:{platform:"Dating app", queue:"profile reviews and harassment reports", urgent:"assault and threat reports"},
    genai:{platform:"AI platform", queue:"flagged generations and abuse reports", urgent:"child-safety and weapons-related flags"},
    gig:{platform:"Rides and delivery platform", queue:"safety reports from riders, customers and couriers", urgent:"assault and physical-safety reports"},
    kids:{platform:"Kids' learning platform", queue:"reports about messages sent to children", urgent:"reports of adults contacting children"}
  },
  steps:[
    { t:"Mon 07:00", h:"Your vendor goes dark",
      s:"A typhoon has shut your moderation vendor's main site. 60% of your reviewers are offline for at least a week, and {queue} are piling up.",
      o:[ op("Keep working through reports in the order they arrive.", "Some {urgent} wait two days behind low-risk reports.", [-15,-5,-8,0]),
          op("Switch on automatic removal for everything flagged.", "Thousands of wrongful removals, and appeals flood in.", [3,-12,-3,-5]),
          op("Triage by severity: move your in-house team and remaining vendor staff onto {urgent}, and pause low-severity work.", "Serious cases are still handled within hours while low-risk queues build up.", [12,3,5,-5], true) ],
      lesson:"In a capacity crisis, severity triage matters more than throughput. Agree your priority tiers before you need them." },
    { t:"Mon 12:00", h:"The vendor's people",
      s:"The vendor's staff are safe, but many have lost power or their homes. The vendor asks whether you'll keep paying during the shutdown.",
      o:[ op("Keep paying the contract and ask how you can support the staff.", "Staff return sooner, and more of them stay afterwards.", [0,8,0,5], true),
          op("Stop payment: no work, no pay.", "The vendor lays off experienced reviewers you'll need when it reopens.", [0,-8,0,-10]),
          op("Ask the vendor to move its staff to another city right away.", "Staff can't travel, and the request damages the relationship.", [0,-5,0,-5]) ],
      lesson:"Your vendor's reviewers are part of your safety system. How you treat them in a crisis shapes quality afterwards." },
    { t:"Wed 09:00", h:"The backlog grows",
      s:"The low-severity backlog has reached 400,000 items, and people are complaining that their reports go unanswered.",
      o:[ op("Close all old reports without action.", "People feel ignored, and some harmful content stays up.", [-8,-10,-5,5]),
          op("Automate clear-cut, low-severity cases with high-accuracy models, spot-check the results, and tell people about the delays.", "The backlog halves in two days, and accuracy holds on the spot checks.", [8,5,3,3], true),
          op("Pull engineers and product managers onto the queue.", "They make many mistakes, and product work stops.", [0,-3,0,-8]) ],
      lesson:"Automation is safest on clear-cut, low-harm cases, with spot checks for accuracy and honest messages about delays." },
    { t:"Week 3", h:"Never again",
      s:"Leadership asks how to stop depending on a single site.",
      o:[ op("Bring all moderation in-house immediately.", "Costs triple, and hiring takes a year.", [0,0,0,-10]),
          op("Negotiate a discount for the outage.", "Nothing changes about the risk.", [0,0,0,0]),
          op("Split review across two vendors in different regions, keep an in-house core for high-severity work, and test the continuity plan twice a year.", "The next regional outage barely affects response times.", [10,5,5,-3], true) ],
      lesson:"Moderation needs business continuity like any critical system: geographic spread, an in-house core and tested plans." }
  ]},
{ id:"bias", types:ALL_TYPES, tailored:true, title:"The biased-enforcement story", platform:"{platform}", severity:"Sev 2",
  blurb:"A journalist's analysis suggests {group} are three times more likely to {action}.",
  vars:{
    all:{platform:"Any platform", group:"users from one minority community", action:"have their content removed"},
    social:{platform:"Social network", group:"Black creators discussing racism", action:"have posts removed as hate speech"},
    marketplace:{platform:"Online marketplace", group:"sellers from one country", action:"have listings suspended as counterfeit"},
    fintech:{platform:"Digital bank", group:"customers with non-Western names", action:"have accounts frozen for fraud checks"},
    gaming:{platform:"Online game", group:"players who chat in Arabic", action:"be muted or banned for toxicity"},
    dating:{platform:"Dating app", group:"trans members", action:"have their profiles removed as fake"},
    genai:{platform:"AI assistant", group:"users writing in African American English", action:"have prompts refused as toxic"},
    gig:{platform:"Rides and delivery platform", group:"drivers with darker skin", action:"fail automated selfie checks and be deactivated"},
    kids:{platform:"Kids' learning platform", group:"students who write in Spanish", action:"be flagged for bullying"}
  },
  steps:[
    { t:"Tue 09:00", h:"A journalist's analysis",
      s:"A journalist shares an analysis suggesting {group} are three times more likely than others to {action}. They want comment by Thursday.",
      o:[ op("Take it seriously: reproduce the analysis with your own data, involve policy, data science and people with lived experience, and tell the journalist you're looking into it.", "Within two days you confirm a real gap and can explain it honestly.", [5,8,5,-5], true),
          op("Deny it: your systems don't consider identity.", "Your own data later shows the gap is real.", [0,-15,-5,0]),
          op("Pause all automated enforcement.", "Harmful content and fraud rise across the board.", [-12,-5,-3,-3]) ],
      lesson:"Treat claims of biased enforcement seriously, and test them with your own data before responding." },
    { t:"Wed 15:00", h:"The cause",
      s:"Your analysis confirms it: a model trained on skewed labels is wrongly flagging {group} far more often than others.",
      o:[ op("Quietly retrain the model and say nothing.", "The journalist publishes anyway and notes you didn't engage.", [3,-12,-3,0]),
          op("Add human review for these flags, retrain on corrected labels, and restore wrongly actioned accounts.", "Wrongful actions drop sharply, and affected people get their accounts back.", [8,10,5,-5], true),
          op("Keep the model: overall accuracy is fine.", "Averages hide the harm to one group, and it gets worse.", [-5,-12,-5,0]) ],
      lesson:"Overall accuracy can hide unfair outcomes for particular groups. Measure errors by group and fix the cause." },
    { t:"Thu 12:00", h:"The response",
      s:"The story is ready to publish.",
      o:[ op("Question the journalist's methods.", "It looks defensive, and your own data supports them.", [0,-12,-3,0]),
          op("Decline to comment.", "The story runs without your side.", [0,-10,-3,0]),
          op("Confirm the finding, explain the cause and the fix, and commit to publishing fairness metrics.", "The story includes your fix, and advocates call it a model response.", [3,12,8,-3], true) ],
      lesson:"When the data shows you got it wrong, say so and show the fix." },
    { t:"Month 2", h:"Catching it first",
      s:"The board asks how you'll catch this before a journalist does.",
      o:[ op("Test enforcement outcomes by group before launching models and regularly afterwards, and involve affected communities in policy design.", "The next model is caught with a gap before launch, and fixed.", [5,8,8,-3], true),
          op("Remove all automated enforcement.", "Costs soar, and response times collapse.", [-8,0,0,-12]),
          op("Rely on appeals to catch mistakes.", "Most affected people never appeal.", [-3,-5,-3,3]) ],
      lesson:"Fairness testing belongs in the launch process, not the crisis response." }
  ]}
);
