/* ---------- Scenarios added from a gap check against public data (October 2026) ---------- */
// Each fills a common, well-documented incident type the library didn't cover. They are appended after the
// existing scenarios so saved progress, which is keyed by scenario index, still points at the same scenarios.
SCENARIOS.push(
{ id:"sextortion", types:["social","gaming","kids"], title:"The gift card ultimatum", platform:"Teen social app", severity:"Sev 1",
  blurb:"Fake accounts posing as teenage girls target boys at one high school, get an image, then demand gift cards. Within hours, one boy posts that he wants to die.",
  steps:[
    // Law note source: https://www.law.cornell.edu/uscode/text/18/2258A
    { t:"Mon 21:00", h:"Scripted accounts swarm one school",
      s:"In two hours, 40 new accounts posing as teenage girls follow hundreds of students at one high school. Three boys report the same script: a friendly opener in a game chat or comment thread, a move to direct messages, then a demand for gift cards and a threat to send an image to everyone they know.",
      o:[ op("Ban the three reported accounts now and send each boy your standard guide to blocking and reporting.", "The three accounts are gone in minutes. The other 37 keep messaging students, and new reports arrive all night.", [-8,-5,-5,3]),
          op("Link the accounts by device, sign-up pattern, scripts and payment handles, remove the whole network, preserve evidence, file mandatory reports and alert every student they contacted.", "One sweep removes 52 linked accounts, including 12 no one had reported. Targeted students get a safety notice and reports are filed by morning.", [14,6,10,-6], true),
          op("Pause direct messages from all accounts under seven days old, platform-wide, until the morning review.", "The campaign stalls overnight, but so do thousands of real new users. By morning, the offenders switch to older accounts.", [5,-6,-2,-3]) ],
      lesson:"Sextortion is usually run as an organized campaign. Remove the whole network on shared signals, warn the people it targeted, and preserve and report as you go.",
      law:"In the US, 18 U.S.C. 2258A requires providers to report apparent child sexual abuse material and enticement of minors to NCMEC's CyberTipline as soon as reasonably possible. The 2024 REPORT Act extended preservation of reported content from 90 days to one year." },
    { t:"Tue 01:15", h:"A target says he wants to die",
      s:"Earlier tonight, one 15-year-old target paid $50 in gift cards, and the demand doubled. Now he posts a story saying he wants to die and that everyone will see the image. Your classifier flags the post while he is online.",
      o:[ op("Remove the story under your self-harm policy and send him the standard automated support message.", "The story is gone in seconds, but the message reads like a rule warning. He goes quiet, and you don't know if he is safe.", [-6,-4,-2,3]),
          op("Lock his account to protect him and email the parent address on file to explain what happened.", "The email reaches an address he set up himself. Locked out, he loses the friends who were reaching out and still fears the image will spread.", [-8,-6,-3,-1]),
          op("Have a trained specialist message him now: connect him to a crisis line, tell him it's not his fault and not to pay, and request an emergency welfare check.", "He replies to the specialist and agrees to call the crisis line. Police confirm he is safe at home with a parent within the hour.", [15,6,4,-6], true) ],
      lesson:"When a target says he wants to die, a fast, human response matters most. Tell him it isn't his fault and not to pay, and connect him to crisis support now." },
    // Law note source: https://www.ftc.gov/business-guidance/resources/complying-take-it-down-act
    { t:"Tue 10:00", h:"His family, police and school call",
      s:"Last night, the offender sent the image to three of the boy's followers. His parents want it gone for good, here and elsewhere. A detective asks what you have. The principal wants to warn every family and asks for the names of all targeted students.",
      o:[ op("Hash and remove every copy, help the family use a cross-platform hash service, route police to your preserved evidence, and help the school warn families without names.", "Copies come down within hours and are blocked on participating platforms. The detective has what she needs, and the school's warning names no one.", [12,10,8,-5], true),
          op("Remove the copies your team finds and tell the family to report anything on other sites to police.", "Your platform is clean by evening, but a copy surfaces on another site and the family feels left on their own.", [3,-8,-2,3]),
          op("Send the principal the list of targeted students so the school can call each family today.", "Families hear fast, but the list leaks to a student group chat and the targeted boys are named and teased.", [3,-10,-8,0]) ],
      lesson:"Victims need the image gone everywhere, not just on your platform. Use hashing and shared hash lists, work with police through your preserved evidence, and keep every target's identity private.",
      law:"Under the US TAKE IT DOWN Act, enforced by the FTC since May 19, 2026, covered platforms must remove non-consensual intimate images and known identical copies within 48 hours of a valid removal request." },
    { t:"Week 3", h:"Closing the door on strangers",
      s:"The campaign is over. Your review finds offenders used public follower lists to find targets and make their threats credible, and messaged teens freely from accounts made that day. Leadership wants changes before next term but worries about growth.",
      o:[ op("Add a sextortion warning banner to teens' inboxes and leave messaging and privacy settings as they are.", "Teens stop noticing the banner within a week, and the next campaign uses the same public follower lists.", [-3,2,-2,4]),
          op("By default for teens, limit messages from accounts they don't follow, hide friend and follower lists from strangers, and blur suspected nudity behind a warning.", "Unwanted messages to teens drop sharply, and the next campaign struggles to find targets. Some teens complain about the limits, and growth dips slightly.", [13,8,8,-5], true),
          op("Require a government ID check for every new account before it can send any message.", "Fake accounts slow down, but sign-ups fall, privacy groups object to collecting teens' IDs, and offenders buy older accounts instead.", [4,-8,-3,-6]) ],
      lesson:"Sextortion depends on easy access to teens and their friend lists. Default protections that limit what strangers can see and send work better than warnings alone or blanket ID checks." }
  ]},
{ id:"aiimages", types:["genai","social"], title:"The school photo edits", platform:"AI photo app", severity:"Sev 1",
  blurb:"A school says your AI editing feature is being used to turn students' photos into sexualized images. Copies are already spreading beyond your app.",
  steps:[
    { t:"Mon 08:30", h:"A school reports edited student photos",
      s:"A school and three parents report that students' school photos, copied from public profiles, have been turned into sexualized images with your AI editing feature. Your logs confirm the edits were made in your app. The feature drives 35% of daily sessions and anchors this month's ad campaign.",
      o:[ op("Add the wording from the reported requests to your blocklist and keep the feature live while you investigate.", "Within hours, logs show users rephrasing requests to get past the list. The school asks why the feature is still on.", [-10,-8,-5,0]),
          op("Take the whole app offline until the investigation is complete.", "No new edits are made, but millions of users lose access to their photos, support is swamped and the outage becomes the headline.", [10,-8,0,-12]),
          op("Switch off the AI editing feature for everyone now, keep the rest of the app running, and preserve the generation logs.", "Daily sessions fall by a third and the ad campaign is paused, but no new edits can be made and the evidence is intact.", [12,6,6,-4], true) ],
      lesson:"Engagement can recover; harm to a child can't. Switch off the smallest thing that fully stops the harm, and keep the evidence." },
    // Law note source: https://www.govinfo.gov/content/pkg/USCODE-2024-title18/html/USCODE-2024-title18-partI-chap110-sec2258A.htm
    { t:"Mon 16:00", h:"A hotline finds copies elsewhere",
      s:"A child-protection hotline tells you images carrying your app's watermark are circulating in group chats and on another platform. Your team has traced 212 edited images to nine accounts. An engineer proposes deleting every image and account today so nothing can leak again.",
      o:[ op("Suspend the nine accounts, report each case to the national child-abuse reporting center, preserve the evidence with restricted access, and share hashes through an industry hash-sharing program.", "Reports go in within hours. The other platform blocks matching copies the same day, and investigators later use your preserved logs to identify the account holders.", [12,6,10,-5], true),
          op("Delete every edited image and the nine accounts today so the material can never leak from your systems.", "Your systems are clean, but the evidence investigators need is gone, and you have nothing to hash so other platforms can block copies.", [-5,-5,-15,3]),
          op("Suspend the accounts, but hold off reporting until legal confirms whether AI-edited images are covered by the reporting law.", "Legal confirms four days later that they are. Meanwhile copies keep spreading, and your late reports draw questions from investigators.", [-8,-3,-10,2]) ],
      lesson:"Never delete first. Images altered to show a real child count as abuse material: report them, preserve the evidence, and share hashes so other platforms can block copies.",
      law:"Under 18 U.S.C. 2258A, US providers must report apparent child sexual abuse material to NCMEC's CyberTipline as soon as reasonably possible. A completed report is treated as a request to preserve its contents for one year." },
    // Law note source: https://www.ftc.gov/business-guidance/resources/complying-take-it-down-act
    { t:"Tue 11:00", h:"Families, the regulator and the press",
      s:"Worried parents are forwarding copies they found to the school as proof. The school wants your help writing to families, the regulator has asked for a call today, and a local reporter knows which school is involved.",
      o:[ op("Ask the school to collect copies parents have found and send them to your team so you can find every match.", "You find a few more copies, but the images pass through more inboxes, and the school's lawyer warns that forwarding them is itself illegal.", [-10,-5,-8,0]),
          op("Ask families to stop forwarding copies, give them a named contact and a way to report without sharing images, and brief the regulator before a short public statement.", "Families stop circulating copies and use the reporting route. The regulator credits your early briefing, and your statement names no school or child.", [10,10,10,-6], true),
          op("Issue a holding statement that your safeguards are robust and this was isolated misuse, and route the regulator's questions through your press team.", "The reporter learns copies are on another platform and 'isolated' falls apart. The regulator, kept at arm's length, opens a formal inquiry.", [0,-12,-10,3]) ],
      lesson:"Every forward exposes the child again. Give families a way to act without sharing images, and brief the regulator before the press does.",
      law:"Since May 2026, the US TAKE IT DOWN Act requires covered platforms to remove reported intimate images, including AI-made 'digital forgeries', and known identical copies within 48 hours of a valid request." },
    { t:"Week 3", h:"Bringing the feature back",
      s:"Engagement is down 30%, and leadership wants the editing feature back before the holidays. Your review finds it never checked whether an uploaded photo showed a real person or a child, and was never red-teamed for this misuse.",
      o:[ op("Relaunch only once the feature blocks sexualized edits of real people, refuses edits to photos that appear to show minors, and passes an external red-team review.", "Relaunch slips four weeks and some family-photo edits are refused, but red-team attempts to repeat the misuse fail and the regulator accepts your plan.", [12,8,10,-6], true),
          op("Relaunch next week with a longer blocked-words list and a new terms-of-use rule against sexualized edits of real people.", "Engagement recovers, but within days users find wording the list misses, and the hotline sends a new batch of reports.", [-12,-6,-8,3]),
          op("Relaunch only for paying users who verify they are adults, keeping the current filters.", "Misuse dips at first, but checking the uploader's age does nothing for the child in the photo, and reports resume from verified accounts.", [-3,-5,-3,-2]) ],
      lesson:"Safeguards must protect the person in the photo, not just check the person using the app. Block sexualized edits of real people, detect minors, and red-team for abuse before launch." }
  ]},
{ id:"investscam", types:["fintech"], title:"The guaranteed returns club", platform:"Payments app", severity:"Sev 2",
  blurb:"Hundreds of customers are paying the same new accounts after a celebrity video ad promised guaranteed returns. The celebrity never made it, and the platform is fake.",
  steps:[
    { t:"Mon 09:00", h:"Many customers, the same new payees",
      s:"Your fraud team spots 340 customers making first-time payments, averaging £3,500, to six accounts at two other banks, all opened last month. Most chose \"paying a friend\" as the reason. Support chats mention a trading platform found through a celebrity video ad and an investment \"club\" on a messaging app.",
      o:[ op("Hold new payments to the six accounts for a scam warning and a call, contact customers who already paid, and alert the two receiving banks.", "Calls confirm a fake trading platform. Most customers stop paying, and the receiving banks freeze two accounts that still hold £180,000.", [12,6,6,-6], true),
          op("Block all payments to the six accounts and restrict the 340 customers to small payments until each customer is reviewed.", "Payments to the six stop, but customers can't pay rent or bills, complaints spike, and the scammers send victims new account details within hours.", [6,-10,-2,-10]),
          op("Add the six accounts to a watchlist and wait for confirmed fraud reports before stepping in.", "It avoids false alarms, but 120 more customers pay over two days, and by the first reports the money has left the receiving banks.", [-12,-5,-5,3]) ],
      lesson:"Many customers paying the same new accounts, with reasons that don't fit, is a strong scam signal. Interrupt the payments, talk to customers and alert the receiving banks the same day." },
    // Law note source: https://www.legislation.gov.uk/uksi/2024/1013/body/made
    { t:"Wed 11:00", h:"Scammers adapt and coach their victims",
      s:"The scammers now switch payee accounts every few days and coach victims on what to tell your staff. Your product lead asks how much friction to add. One customer, called twice, says \"I know what I'm doing\" and threatens to close his account if you block another payment.",
      o:[ op("Hold every first-time payment over £1,000 for 48 hours, for all customers, until the scam wave passes.", "Scam payments drop, but house deposits, rent and invoices stall for thousands of genuine customers, and support calls triple.", [8,-8,-4,-10]),
          op("Target friction by risk: a warning describing this exact scam, a hold and specialist call for high-risk payments, and a second conversation for customers who insist.", "Most genuine payments go through untouched. On the second call, the insistent customer hears how the fake platform works and stops paying.", [12,5,7,-6], true),
          op("Show a stronger warning on all transfers and let customers proceed once they confirm they understand the risk.", "Coached customers tap through it in seconds. Losses continue, and the insistent customer sends another £15,000.", [-10,-4,-5,5]) ],
      lesson:"Friction works when it is targeted: generic warnings get tapped through, blanket holds punish genuine customers, and a customer under a scammer's influence often needs a real conversation.",
      law:"Since 30 October 2024, the UK Payment Services (Amendment) Regulations 2024 let firms delay a payment by up to four business days when they have reasonable grounds to suspect the customer is being scammed. They must tell the customer why." },
    // Law note source: https://www.psr.org.uk/information-for-consumers/app-fraud-reimbursement-protections/
    { t:"Fri 10:00", h:"Victims want their money back",
      s:"About 400 customers have lost a total of £1.4 million, and a few ignored your warnings. Some are now getting calls offering to recover their money for a fee. The receiving banks have frozen part of the funds, and a local newspaper is preparing a story.",
      o:[ op("Reimburse customers who never saw a warning, and decline everyone who tapped through one as grossly negligent.", "It looks consistent, but gross negligence is a high bar. The ombudsman overturns many declines, and the newspaper leads with refused victims.", [-5,-10,-8,-2]),
          op("Ask victims to wait while the receiving banks recover what they can, then reimburse the shortfall.", "Recovery takes months. Victims wait well past the reimbursement deadline, complaints reach the regulator, and the newspaper runs their stories.", [-6,-8,-10,2]),
          op("Reimburse eligible victims within the deadline, assess warning cases individually, claim the receiving banks' share, warn victims about recovery scams, and brief the newspaper on what you're doing.", "Most victims are repaid within days. The receiving banks pay their half and close linked accounts, and the story credits your fast response.", [10,10,8,-6], true) ],
      lesson:"Reimbursement is a cost you share with the banks that received the money. Repay victims promptly, treat gross negligence as a high bar, and warn victims that recovery offers are often a second scam.",
      law:"Under the UK Payment Systems Regulator's reimbursement requirement, since 7 October 2024 payment firms must reimburse most authorised push payment scam victims up to £85,000, with sending and receiving firms splitting the cost 50:50. The gross negligence exception is a high bar." },
    { t:"Week 3", h:"Stopping the next wave earlier",
      s:"Losses have fallen, but copycat trading platforms appear every week. Almost every victim first saw a deepfake celebrity ad on social media or joined an investment group on a messaging app. Your CEO asks what changes now.",
      o:[ op("Launch a customer awareness campaign about investment scams and keep your detection rules as they are.", "Awareness rises a little, but coached victims trust the scammers over your emails, and the next platform takes a week to spot.", [-3,3,-3,3]),
          op("Block payments to cryptocurrency exchanges and newly registered investment firms for all customers.", "Genuine investors complain and move their money elsewhere, while the scammers keep collecting payments through personal accounts at other banks.", [2,-10,-3,-2]),
          op("Report the ads and groups to the platforms with evidence, share payee details with other banks and police, and add alerts for many customers paying one new payee.", "Dozens of ads and groups come down, other banks close linked accounts faster, and the next copycat platform is caught within a day.", [10,8,7,-4], true) ],
      lesson:"Investment scams start on social media and messaging apps, not in your app. Reporting ads, sharing data with other banks and spotting payee clusters early stops each new wave sooner." }
  ]},
{ id:"ridehail", types:["gig"], title:"The fourth complaint", platform:"Ride-hailing app", severity:"Sev 1",
  blurb:"At 2 a.m., a rider calls your safety line to report that her driver sexually assaulted her. By morning, you learn he had three earlier complaints nobody connected.",
  steps:[
    { t:"Sat 02:10", h:"A rider calls the safety line",
      s:"A rider calls your in-app safety line to report that her driver sexually assaulted her on a trip that ended 30 minutes ago. She is home, shaken and alone. The driver is online and has just accepted another trip. Trip GPS and in-app messages auto-delete after 30 days.",
      o:[ op("Leave the driver active until an investigator reviews the case on Monday, and have the agent take her full written account tonight.", "The driver completes 40 more trips before Monday. She retells every detail to a generalist agent, then stops answering your messages.", [-12,-8,-4,2]),
          op("Put the driver on a temporary hold, connect her to a trained safety specialist who offers police and support contacts, and preserve the trip's GPS, messages and call logs.", "His pending pickup is reassigned and he can't drive while the case is open. She chooses next steps with a specialist, and the trip record is preserved.", [12,6,5,-4], true),
          op("Permanently deactivate the driver right away and tell her he has been removed from the platform for good.", "She feels believed tonight, but the case is closed with no evidence kept. When the driver appeals, your team has nothing to stand behind.", [8,-3,-4,-5]) ],
      lesson:"A temporary hold manages risk without deciding guilt. In the first hour, support the person reporting and preserve the evidence, because deletion schedules don't pause for investigations." },
    { t:"Sat 09:00", h:"Three complaints nobody connected",
      s:"Your investigator finds three earlier complaints about this driver in eight months: two for inappropriate comments, one for a long late-night route deviation. Each was closed by a different agent with a warning. The driver denies the report, says he relies on the income, and asks to be reinstated today.",
      o:[ op("Keep the hold, tell the driver the general nature of the report, hear his side, and decide within ten days using trip data and his full history.", "Within a week, trip GPS and the complaint pattern support her account. You deactivate him with a written reason and a right to appeal.", [12,6,6,-5], true),
          op("Reinstate the driver while police decide whether to act, since the earlier complaints were minor and none was ever upheld.", "He is back on the road within hours. Ten days later, another rider reports a late-night detour and unwanted comments from him.", [-14,-8,-5,3]),
          op("Keep him on hold with no explanation until police finish their investigation, however long that takes.", "Riders are protected, but months pass with no decision. The driver files repeated appeals, a drivers' group takes up his case, and your own review stalls.", [8,-5,-3,-6]) ],
      lesson:"Police timelines aren't yours. Run a fair process of your own on the evidence you hold, and review past complaints as a pattern, not one at a time." },
    { t:"Mon 11:00", h:"The detective and the rider",
      s:"A detective asks for the driver's identity, the trip's GPS and messages, and \"everything you have on both of them.\" Meanwhile, your automated systems have asked the rider to rate the trip. She writes back asking whether anyone is actually handling her case.",
      o:[ op("Send the detective everything on both accounts right away, including her full trip history, to show you are cooperating fully.", "The case moves, but two years of her unrelated trips end up in a file that the driver's defense lawyer can later see.", [2,-8,-5,0]),
          op("Insist on a warrant for any data, and route all contact with the rider through legal so nothing you say affects the case.", "The warrant takes three weeks. Her only messages from you are formal legal letters, and she tells the detective she feels abandoned.", [-6,-8,1,2]),
          op("Share the trip's GPS, messages and driver details once valid legal process arrives, switch off automated prompts to her, and assign her one named specialist.", "The detective has what the case needs within days. She hears from one person, is never asked to retell her account, and keeps working with police.", [10,8,6,-3], true) ],
      lesson:"Share what the case needs under proper legal process, not everything you hold. One trained contact, and never making her retell it, is what trauma-informed support looks like." },
    // Law note source: https://www.tdlr.texas.gov/tnc/drivers.htm
    { t:"Week 3", h:"Why the pattern was missed",
      s:"The driver is deactivated and the police case continues. Your review finds complaints are filed by trip, so no one ever saw a driver's history in one place. Criminal record checks rerun only once a year. Your CEO wants a plan by Friday.",
      o:[ op("Automatically deactivate any driver after a single complaint about inappropriate comments or route deviation.", "Hundreds of drivers lose their income over traffic detours and false reports. Appeals swamp your team, and drivers start refusing late-night trips.", [3,-8,-2,-12]),
          op("Link every complaint to the driver's full history with escalation rules, add continuous criminal-record monitoring, and build in-trip safety tools for riders and drivers alike.", "Patterns reach an investigator by the second complaint. Drivers, who face assaults from riders too, get the same emergency button and audio recording.", [12,8,7,-5], true),
          op("Launch a rider emergency button and a public safety report this month, and plan the complaint-system changes for next year.", "The launch gets good coverage. But complaints are still reviewed one trip at a time, and two months later another pattern slips through.", [2,3,-2,2]) ],
      lesson:"Low-level complaints are often early warnings, so review them as one history, not trip by trip. Build the same protections for drivers, who are assaulted by riders too.",
      law:"In Texas, the ride-hail law (Occupations Code Chapter 2402) requires companies to rerun criminal background and driving history checks on every driver at least once a year. Continuous monitoring goes beyond that minimum." }
  ]},
{ id:"datingsextortion", types:["dating"], title:"The video-call blackmail ring", platform:"Dating app", severity:"Sev 2",
  blurb:"A ring of fake profiles lures members to video chat, records them and demands money. One report leads to hundreds, and the network is still matching.",
  steps:[
    { t:"Mon 08:30", h:"A member reports blackmail",
      s:"A member reports that a match moved him to a video-chat app within an hour, secretly recorded an intimate call, and now demands money or the recording goes to his contacts. Your team searches and finds 340 similar reports in six weeks, most from members in their twenties. The profiles look different, but their opening messages are nearly identical.",
      o:[ op("Ban the 340 reported profiles today and send each reporter your standard harassment reply.", "The profiles are gone by evening, but new ones with the same scripts appear overnight. Reporters get no advice on the blackmail itself.", [3,-4,-2,-6]),
          op("Block video-chat links and phone numbers in all chats across the app while you investigate.", "Fast moves off the app slow down, but so do genuine dates. Members complain loudly, and the group switches to spelled-out usernames within two days.", [5,-8,0,-4]),
          op("Open an incident, give the reporter clear advice (don't pay, stop replying, keep evidence), preserve all reports, and map the linked profiles today.", "The reporter stops replying and doesn't pay. By evening, matching photos, scripts and devices link 1,100 profiles, far more than were reported.", [10,6,5,-5], true) ],
      lesson:"One sextortion report is often a window into a network. Support the victim first, preserve evidence, and map the network before you start banning." },
    { t:"Tue 09:00", h:"Deciding how wide to sweep",
      s:"Investigators link 1,100 profiles through AI-generated photos, copied scripts and 40 shared devices. About 900 match on several strong signals; 200 match on one weak signal, such as a photo flagged as possibly AI-edited. New fakes appear daily, and any sweep will tell the group you have found them.",
      o:[ op("Keep watching for another week so you can map every profile and device before acting.", "The map gets more complete, but about 70 more members are blackmailed that week, and the group starts moving to new devices.", [-12,-6,-3,0]),
          op("Remove the 900 in one coordinated sweep, block their devices, preserve evidence, and send the 200 borderline profiles to fast human review.", "The 900 go within an hour and new sign-ups from those devices fail. Review clears 130 real members and removes 70 more fakes.", [12,6,5,-5], true),
          op("Ban all 1,100 now, plus any account that shares a device or an opening line with them.", "The network is gone overnight, but so are about 400 real members. Appeals flood support, and a viral thread calls your bans random.", [8,-10,-3,-10]) ],
      lesson:"Remove networks in one coordinated sweep using several strong signals together. Waiting costs victims, and banning on one weak signal costs innocent members." },
    // Law note source: https://www.ftc.gov/news-events/news/press-releases/2026/05/ftc-begins-enforcing-take-it-down-act
    { t:"Wed 11:00", h:"Hundreds of members need help",
      s:"About 2,300 members chatted with the network, and 400 have reported blackmail. Some paid and were asked for more; several write that they feel desperate. A national police cybercrime unit asks what you can share.",
      o:[ op("Message all 2,300 with clear steps (don't pay, stop contact, keep evidence), offer takedown help and crisis support, and refer the network to police with preserved evidence.", "More victims come forward and fewer pay. Dozens use your takedown help, and police trace the payment accounts to a crime group abroad.", [12,10,8,-6], true),
          op("Contact only the 400 members who reported blackmail, so you don't alarm the 1,900 who may not have been targeted.", "Reporters get help, but many targeted members never reported out of shame. Some keep paying, and others learn about the network from the news.", [2,-8,-2,0]),
          op("Tell victims to report to police themselves, and wait for a formal legal request before engaging with the police unit.", "Victims bounce between your support team and the police. The legal request takes weeks, and by then the group's payment accounts have closed.", [-5,-6,-2,3]) ],
      lesson:"Paying rarely ends the threats, so tell everyone exposed, not just reporters, what to do, help with takedowns, and give police a case they can act on.",
      law:"Since May 19, 2026, the US TAKE IT DOWN Act requires covered platforms to offer a way to request removal of non-consensual intimate images, and to remove them and known identical copies within 48 hours of a valid request." },
    // Law note source: https://www.legislation.gov.uk/ukpga/2023/50/schedule/7
    { t:"Week 6", h:"Stopping the next network",
      s:"The sweep holds, but a smaller copy of the network appears a month later. Your data shows most blackmail cases moved off the app within an hour of matching. Your CEO asks what changes.",
      o:[ op("Warn members in chat when a new match pushes to move off the app, screen new photos for AI generation, and share network signals with other platforms.", "Many members pause after the warning, and blackmail reports fall by more than half. New copycat profiles are caught at sign-up.", [12,8,8,-5], true),
          op("Require every member to pass a live selfie video check before they can send any message.", "Fake profiles drop sharply, but sign-ups fall by a quarter, and within weeks the group buys verified accounts from real people.", [6,-4,2,-8]),
          op("Publish a sextortion safety guide in the help center and send it to all members in a one-off email.", "The guide gets good press, but few members read it, and the copycat network runs the same playbook.", [-5,3,-3,2]) ],
      lesson:"Sextortion follows a pattern: fast trust, a fast move off the app, then threats. Put warnings at that moment, and share signals so networks can't just move elsewhere.",
      law:"The UK Online Safety Act lists sharing or threatening to share intimate images as a priority offence. Platforms with UK users must take proportionate steps to reduce the risk of their service being used to commit or facilitate it." }
  ]},
{ id:"triangulation", types:["marketplace"], title:"The bargains bought with stolen cards", platform:"Online marketplace", severity:"Sev 2",
  blurb:"Buyers love the cheap headphones and consoles. Then a big retailer's fraud team calls: the goods were bought with stolen cards, and the orders trace back to your sellers.",
  steps:[
    // Law note source: https://www.ftc.gov/business-guidance/resources/informing-businesses-about-inform-consumers-act
    { t:"Mon 09:00", h:"A retailer's fraud team calls",
      s:"A large retailer's investigators say hundreds of its orders, paid with stolen cards, trace back to sellers on your marketplace. Your data points to 85 sellers who joined in the last eight weeks, most with hundreds of sales of consoles and headphones at 20-30% below market. Their tracking numbers come from that retailer, and buyers' photos show its boxes.",
      o:[ op("Hold payouts to the 85 sellers, confirm the pattern on a sample of orders, and set up a direct line with the retailer's investigators.", "By evening 46 of 50 sampled orders match the retailer's stolen-card list, and about $700,000 in pending payouts stays with you.", [10,5,8,-5], true),
          op("Ask the retailer to send a formal legal request with evidence before you act against any seller.", "It feels careful, but the request takes nine days. Meanwhile payouts go out and every new order triggers another stolen-card purchase.", [-10,-3,-5,3]),
          op("Log the report and leave it to the retailer, since your buyers paid and got their goods.", "Your metrics look fine for a week. Then the retailer starts canceling shipments to your buyers, and the sellers cash out and disappear.", [-12,-8,-8,5]) ],
      lesson:"Triangulation fraud hides behind happy buyers: new high-volume sellers, below-market prices and another retailer's tracking are the signal. Hold payouts while you confirm it.",
      law:"The US INFORM Consumers Act requires online marketplaces to collect and verify bank, tax ID and contact details from high-volume third-party sellers: those with 200 or more sales and $5,000 or more in revenue in a 12-month period." },
    { t:"Tue 09:00", h:"Thousands of paid orders in limbo",
      s:"The pattern is confirmed. The 85 sellers have 3,400 open orders from real buyers who have already paid. Every order these sellers fill means another purchase with a stolen card. Your marketplace team warns that canceling them all will flood support and anger loyal buyers.",
      o:[ op("Let the open orders complete so buyers get what they paid for, and block the sellers from taking new ones.", "Buyers stay happy, but about 3,400 more stolen-card purchases go through, and the retailer says it is weighing legal action.", [-15,-5,-8,5]),
          op("Ban all 85 sellers and cancel every open order now, using your standard seller-unavailable notice and refund timeline.", "The fraud stops, but buyers get a vague email and a 7-day refund wait. Support queues triple and buyers post that you took their money.", [10,-8,0,-10]),
          op("Remove the sellers, cancel their open orders, refund buyers in full today from held payouts, and tell buyers plainly what happened.", "Some buyers are annoyed to lose a bargain, but most accept the explanation, and the stolen-card purchases tied to your sellers stop.", [12,5,5,-6], true) ],
      lesson:"Every order a triangulation seller fills creates a new card-fraud victim. Stop the flow, then make buyers whole quickly and honestly; held payouts are what pay for it." },
    { t:"Thu 11:00", h:"Everyone wants answers at once",
      s:"Your payment processor warns that your dispute rate has doubled and is nearing card network limits, driven by buyers whose shipments the retailer canceled. The retailer wants every buyer's name and address, police have opened a case, and a consumer reporter asks what you knew.",
      o:[ op("Send the retailer your full buyer and seller records so it can recover its losses as fast as possible.", "The retailer is grateful, but buyers start getting demand letters, and your privacy team flags sharing innocent buyers' data in bulk as a likely privacy breach.", [0,-8,-10,3]),
          op("Refund buyers with canceled shipments, send the processor a written plan, share seller evidence with the retailer and police, and tell the reporter the facts.", "Disputes fall within two weeks and the processor holds off on penalties. Police link the sellers to a known fraud ring, and the story runs with your response.", [8,8,10,-6], true),
          op("Fight each dispute case by case and say nothing publicly until police finish their investigation.", "Your team loses most disputes, and the processor starts holding back a share of your funds. The reporter runs the story without your side.", [-3,-10,-6,-5]) ],
      lesson:"Share what each party needs, not everything you have. Fixing the cause of disputes and giving your processor a plan protects your ability to take payments." },
    // Law note source: https://digital-strategy.ec.europa.eu/en/policies/dsa-impact-platforms
    { t:"Week 3", h:"Fixing how sellers get in",
      s:"The network is gone. Its sellers needed only an email and a bank account to start, and reached hundreds of sales before anyone checked who they were. Leadership asks what changes before the holiday rush.",
      o:[ op("Block new sellers from listing consoles and headphones until they have six months of history.", "This network can't return in those categories, but genuine new sellers go elsewhere and the next ring moves into phones and laptops.", [4,-6,0,0]),
          op("Add an automatic rule that flags listings priced more than 20% below market for manual review.", "Reviewers drown in genuine clearance deals, and the next ring prices just 15% below market and slips through.", [3,0,0,-8]),
          op("Verify seller identity and bank details before first sale, hold early payouts for fast-growing sellers, flag other retailers' tracking numbers, and share signals with retailers.", "Sign-ups dip slightly. A copycat ring is caught in its first week with payouts still held, and the retailer joins a standing signal-sharing channel.", [10,6,10,-4], true) ],
      lesson:"Triangulation rings need fast access to payouts. Verifying who sellers are, slowing early payouts and sharing signals with retailers remove what makes the scheme pay.",
      law:"In the EU, the Digital Services Act requires online marketplaces to make sure sellers give verified identity information before they can start selling." }
  ]}
);
// Why each new scenario: one checked fact from a primary or authoritative source (see partS12.js)
Object.assign(TT_EVIDENCE, {
  sextortion:{claim:"NCMEC received an average of 137 financial sextortion reports a day in 2025, up 37% on 2024, and knows of at least three dozen US teenage boys who took their lives after being targeted.",
    source:"NCMEC, CyberTipline Data", url:"https://www.missingkids.org/gethelpnow/cybertipline/cybertiplinedata", published:"2026"},
  aiimages:{claim:"In 2025, more than 182,000 reports to NCMEC's CyberTipline involved offenders possessing, generating or attempting to generate AI-generated child sexual abuse material.",
    source:"NCMEC, CyberTipline Data", url:"https://www.missingkids.org/gethelpnow/cybertipline/cybertiplinedata", published:"2026"},
  investscam:{claim:"Investment scams made up 38% of all authorised push payment scam losses at UK banks in 2025, reaching a record £221.5 million, up 40% on 2024.",
    source:"UK Finance Annual Fraud Report", url:"https://www.ukfinance.org.uk/system/files/2026-06/UK%20Finance%20Fraud%20Report%202026.pdf", published:"2026-06"},
  ridehail:{claim:"In 2021 and 2022, two US ride-hail companies reported a combined 52 fatal assaults and 4,469 of the five most serious types of sexual assault, according to the US Government Accountability Office.",
    source:"US Government Accountability Office", url:"https://www.gao.gov/products/gao-26-108552", published:"2026-07"},
  datingsextortion:{claim:"People aged 20 to 29 filed 22,061 sextortion complaints with the FBI's Internet Crime Complaint Center in 2025, more than any other age group.",
    source:"FBI IC3 Annual Report", url:"https://www.ic3.gov/AnnualReport/Reports/2025_IC3Report.pdf", published:"2026-04"},
  triangulation:{claim:"Fraud using stolen card details to buy online, by phone or by mail order reached 3,196,962 UK cases in 2025, up 13%, with £423.5 million lost.",
    source:"UK Finance Annual Fraud Report", url:"https://www.ukfinance.org.uk/system/files/2026-06/UK%20Finance%20Fraud%20Report%202026.pdf", published:"2026-06"}
});
