NEW_SCENARIOS.push(
/* ===== Generative AI (more) ===== */
{ id:"jailbreak", types:["genai"], title:"The viral jailbreak", platform:"AI assistant", severity:"Sev 1",
  blurb:"A prompt that tricks your model into giving weapons instructions is spreading on social media.",
  steps:[
    { t:"Wed 09:00", h:"A jailbreak spreads",
      s:"A prompt that tricks your model into giving detailed instructions for improvised weapons is circulating on social media with screenshots of the output. It's been shared 20,000 times.",
      o:[ op("Block the exact prompt text.", "Users paraphrase it within minutes.", [3,-3,0,0]),
          op("Deploy an output classifier for weapons instructions as an emergency patch, and red-team variations of the jailbreak.", "The technique and its variations stop working by the afternoon.", [12,5,8,-5], true),
          op("Take the model offline until it's retrained.", "Millions of users lose service for weeks.", [5,-12,0,-8]) ],
      lesson:"Fix the harmful output, not just the prompt. Jailbreaks change faster than blocklists." },
    { t:"Wed 15:00", h:"Who used it?",
      s:"30,000 accounts tried the prompt. A few hundred went on to ask follow-up questions about targets and materials.",
      o:[ op("Review the small group with concerning follow-ups, suspend where warranted, and refer credible threats to law enforcement.", "Two accounts with credible threats are referred, and police act on one.", [12,5,8,-5], true),
          op("Ban all 30,000 accounts.", "Most were curious people testing a viral prompt, and the bans cause a backlash.", [3,-10,0,-3]),
          op("Take no action on accounts.", "One of the concerning accounts is later linked to an attack plot.", [-15,-10,-8,3]) ],
      lesson:"Separate the curious from the concerning. Focus enforcement on behavior that suggests real intent." },
    { t:"Thu 10:00", h:"Press and policymakers",
      s:"A newspaper asks how safe your model is, and policymakers cite the incident in AI safety debates.",
      o:[ op("Say every AI model can be jailbroken.", "It's true, but it sounds like an excuse.", [0,-8,-3,0]),
          op("Decline to comment.", "The story runs with the screenshots and no response.", [0,-10,-3,0]),
          op("Explain what happened and what you fixed, and publish your red-teaming approach and results.", "Coverage notes the quick fix, and experts cite your disclosure.", [5,10,8,-3], true) ],
      lesson:"Being open about safety testing builds credibility when failures happen." },
    { t:"Month 2", h:"A standing process",
      s:"Leadership wants to catch the next jailbreak before it goes viral.",
      o:[ op("Rely on user reports.", "The next jailbreak is found on social media first.", [-8,-5,-5,3]),
          op("Run continuous red-teaming, watch live traffic and jailbreak communities for known patterns, and track the jailbreak success rate as a key metric.", "The next jailbreak is caught internally within a day.", [12,5,8,-5], true),
          op("Make the model refuse anything about chemistry or weapons.", "Students and researchers can't use it, and complaints soar.", [3,-10,0,0]) ],
      lesson:"Treat jailbreak defense as an ongoing program with metrics, not a one-off fix." }
  ]},
{ id:"voiceclone", types:["genai"], title:"The cloned voice", platform:"AI voice tool", severity:"Sev 1",
  blurb:"Your voice tool was used to clone a teenager's voice for a fake kidnapping call to her parents.",
  steps:[
    { t:"Sat 14:00", h:"A fake kidnapping call",
      s:"Police contact you: a family received a call in their daughter's cloned voice, crying for help, followed by a ransom demand. The clone was made with your tool from a video on her social media.",
      o:[ op("Suspend the account that made the clone, preserve all logs and audio, and give police what they need through your legal process.", "Police trace the payment account linked to the user.", [15,8,10,-5], true),
          op("Point out that your terms forbid impersonation.", "Police get nothing useful, and the family goes to the press.", [-10,-12,-5,0]),
          op("Delete the cloned voice.", "Evidence is lost.", [3,0,-10,0]) ],
      lesson:"When your tool is used in a crime, preserve evidence and support the investigation quickly." },
    { t:"Sun 10:00", h:"How easy was it?",
      s:"Your tool can clone any voice from 30 seconds of audio, with no check that the speaker agreed.",
      o:[ op("Add a checkbox saying “I have permission”.", "Everyone ticks it.", [0,-3,-3,0]),
          op("Shut down voice cloning permanently.", "Legitimate uses, such as preserving the voices of people losing their speech, disappear.", [5,-8,0,0]),
          op("Require consent from the speaker: a live recorded statement from the person being cloned, matched against the sample.", "Cloning other people's voices becomes much harder.", [15,5,8,-5], true) ],
      lesson:"Verifying the speaker's consent is the key safeguard for voice cloning. A checkbox isn't consent." },
    { t:"Mon 11:00", h:"Other misuse",
      s:"A review finds cloned voices of politicians and CEOs being used in scam calls and fake endorsements.",
      o:[ op("Remove the specific clones you found.", "New ones are made the same day.", [0,-3,0,-3]),
          op("Block cloning of known public figures, add inaudible watermarks to all generated audio, and give banks and platforms a detection tool.", "Banks start flagging cloned audio in fraud calls.", [12,8,8,-5], true),
          op("Publish a warning about voice scams.", "It helps a little.", [3,3,0,0]) ],
      lesson:"Watermarking and detection help the whole ecosystem, not only your platform." },
    { t:"Month 2", h:"Regulation",
      s:"Lawmakers are proposing rules on voice cloning and AI impersonation.",
      o:[ op("Lobby against any regulation.", "Your company becomes the example lawmakers point to.", [0,-10,-8,0]),
          op("Share your consent and watermarking approach with lawmakers, and meet disclosure rules early.", "Your approach is cited in the draft rules.", [5,8,10,-3], true),
          op("Wait and see.", "Rules arrive that are harder to meet at short notice.", [0,0,-8,3]) ],
      lesson:"Helping shape sensible rules with working safeguards beats reacting to rules written after an incident." }
  ]},
/* ===== Gig, delivery & rentals (more) ===== */
{ id:"partyhouse", types:["gig"], title:"The party house", platform:"Short-term rental platform", severity:"Sev 1",
  blurb:"A house booked for “a quiet family weekend” hosts a 200-person party that ends in a shooting.",
  steps:[
    { t:"Sat 01:30", h:"A shooting at a rental",
      s:"Police report a shooting at a 200-person party at a house booked through your platform for “a quiet family weekend”. Two people are injured. The booking was made yesterday by a 19-year-old with a new account.",
      o:[ op("Activate incident response: cooperate with police, preserve booking data, support the host and neighbors, and suspend the guest's account.", "Police get the booking details quickly, and the host feels supported.", [15,8,8,-5], true),
          op("Wait for police to contact you.", "Police struggle to identify who booked the house.", [-10,-8,-5,3]),
          op("Issue a statement blaming the host for not supervising.", "The host goes to the press, and other hosts lose trust in you.", [0,-12,0,0]) ],
      lesson:"Violence linked to your platform needs a ready incident response: cooperate, preserve evidence, support those affected." },
    { t:"Sat 12:00", h:"The warning signs",
      s:"The booking had classic warning signs: a new account, a young guest, a one-night Saturday stay, and a large house in the guest's own city.",
      o:[ op("Ban all guests under 25.", "It's discriminatory and hurts legitimate young travelers.", [5,-10,-5,0]),
          op("Remind hosts to check their guests.", "Hosts can't see the signals you can.", [-5,0,0,0]),
          op("Flag bookings with party-risk signals, and block or add checks to the riskiest ones.", "High-risk bookings drop sharply the next weekend.", [12,5,5,-5], true) ],
      lesson:"Platforms can see risk signals individual hosts can't. Use them before the booking is confirmed." },
    { t:"Sun 10:00", h:"The neighbors",
      s:"Neighbors are angry and say the house has had parties before. Local officials are considering restricting short-term rentals.",
      o:[ op("Say the platform isn't responsible for how guests behave.", "The city passes restrictions.", [0,-10,-8,0]),
          op("Set up a neighbor hotline that responds within an hour, and share party-enforcement data with officials.", "Officials hold off on restrictions and work with you instead.", [8,10,8,-5], true),
          op("Offer the neighbors vouchers.", "It seems tone-deaf after a shooting.", [0,-8,0,0]) ],
      lesson:"Communities around rentals are stakeholders. A responsive channel for neighbors reduces harm and regulatory risk." },
    { t:"Month 2", h:"A party policy",
      s:"Leadership asks for a lasting approach.",
      o:[ op("Keep the current policy and handle incidents case by case.", "Another party incident happens on a holiday weekend.", [-10,-5,-5,3]),
          op("Ban parties, enforce the ban with risk-based booking checks and extra holiday-weekend measures, and remove guests who break it.", "Party reports fall significantly.", [12,8,5,-3], true),
          op("Require every guest to pay a large deposit.", "Legitimate guests book elsewhere, and organized party-planners pay the deposit.", [3,-8,0,0]) ],
      lesson:"Pair clear rules with risk-based enforcement, especially on predictable high-risk dates." }
  ]},
{ id:"fakelisting", types:["gig"], title:"The listing that didn't exist", platform:"Short-term rental platform", severity:"Sev 2",
  blurb:"Holiday travelers arrive at rentals that don't exist, after being talked into paying outside your platform.",
  steps:[
    { t:"Fri 18:00", h:"Guests arrive at empty lots",
      s:"Twelve families arrive for holiday stays to find the addresses are empty lots or someone else's home. Each booking started on your platform, but the “host” offered a discount for paying by bank transfer.",
      o:[ op("Tell the families they broke the rules by paying off-platform.", "Families are stranded, and the story trends.", [-10,-15,-5,0]),
          op("Find emergency accommodation for the families tonight, and remove the fake listings and linked accounts.", "Every family has somewhere to stay by midnight.", [12,10,5,-8], true),
          op("Remove the listings and deal with the families on Monday.", "Families sleep in their cars.", [-8,-12,-3,3]) ],
      lesson:"People in immediate need come first, even when they broke your rules." },
    { t:"Sat 10:00", h:"How many more?",
      s:"The fake listings used stolen photos of real properties, and the same bank details appear in messages across 80 listings.",
      o:[ op("Remove only the listings that get reported.", "Holiday travelers keep arriving at empty addresses.", [-10,-8,-3,0]),
          op("Suspend all new listings until after the holidays.", "Real hosts lose bookings in peak season.", [5,-8,0,-3]),
          op("Search for listings with reused photos and the same payment details in messages, remove them, and warn guests with upcoming bookings.", "You remove 80 listings and warn 300 guests before they pay.", [12,8,5,-5], true) ],
      lesson:"Scam listings share fingerprints such as reused photos and payment details. Hunt for them proactively." },
    { t:"Sun 11:00", h:"The money",
      s:"The families paid a total of $60,000 by bank transfer.",
      o:[ op("Reimburse the families from a goodwill fund, and share the scammers' bank details with banks and police.", "Banks freeze two of the scammers' accounts.", [5,10,8,-5], true),
          op("Tell the families to contact their banks.", "Most recover nothing.", [0,-10,-3,0]),
          op("Reimburse only families who complain publicly.", "Word gets out, and trust falls.", [0,-8,0,0]) ],
      lesson:"Supporting victims of scams that start on your platform is part of your trust promise." },
    { t:"Month 2", h:"Stopping fake listings",
      s:"Leadership asks how to prevent fake listings.",
      o:[ op("Add “never pay outside the app” to booking confirmations.", "Some guests notice it; most don't.", [3,0,0,0]),
          op("Require every host to meet staff in person.", "It's too costly to scale.", [5,-3,0,-10]),
          op("Verify that new hosts own or manage the property, detect reused photos, and warn guests when messages mention paying elsewhere.", "Fake listings and off-platform payment scams drop sharply.", [12,8,5,-5], true) ],
      lesson:"Verify property control for new hosts, and step into conversations at the moment of risk." }
  ]}
);
