/* ---------- Tabletop scenario library, by company type ---------- */
// op(label, result, [safety, trust, regulatory, team], isStrongest)
const op = (l, r, d, best) => ({l, r, d:{safety:d[0], trust:d[1], reg:d[2], team:d[3]}, best:!!best});
const NEW_SCENARIOS = [
/* ===== Marketplace & e-commerce ===== */
{ id:"counterfeit", types:["marketplace"], title:"The counterfeit flood", platform:"Online resale marketplace", severity:"Sev 2",
  blurb:"A luxury brand's lawyers demand that 1,400 listings come down in 48 hours, days before your biggest sales event.",
  steps:[
    { t:"Mon 09:00", h:"A brand's legal team sends a demand",
      s:"A luxury brand has listed 1,400 listings it says are counterfeit and threatens to sue if they aren't removed in 48 hours. Your Black Friday sale starts Thursday. Spot checks suggest about 70% are clear fakes; the rest are genuine resale or unclear.",
      o:[ op("Remove all 1,400 immediately to make the problem go away.", "The brand is satisfied, but hundreds of legitimate resellers lose sales, flood support and post about it.", [5,-10,0,-10]),
          op("Remove clear fakes now, hold unclear listings for joint review with the brand, and tell sellers why.", "Most fakes are down within a day. The brand's counsel accepts the plan and genuine resellers keep selling.", [10,8,8,-5], true),
          op("Ask the brand to file individual notices through your standard IP form.", "It's defensible, but the brand goes public and the fakes stay up through the sale.", [-10,-10,-5,5]) ],
      lesson:"Pressure from a rights holder doesn't remove the need for accuracy. Act fast on clear cases, review the unclear ones, and explain decisions to sellers." },
    { t:"Tue 14:00", h:"The same sellers keep coming back",
      s:"Removed sellers are relisting within hours under new accounts, with the same photos and shipping addresses. Your seller checks only verify an email address.",
      o:[ op("Ban each new account as reports come in.", "Reviewers spend the day chasing relists while new ones appear.", [0,-3,0,-10]),
          op("Pause all new listings in the affected categories for the week.", "The fakes stop, and so do legitimate new sellers in the biggest sales week of the year.", [8,-5,0,3]),
          op("Link accounts by photo hashes, shipping addresses and payout details, and remove the whole network.", "One sweep removes 60 linked accounts, and relisting slows sharply.", [12,5,5,0], true) ],
      lesson:"Counterfeiters operate as networks. Remove the network using shared signals instead of chasing single listings." },
    { t:"Wed 11:00", h:"Buyers want their money back",
      s:"About 900 buyers have already received fakes. Some want refunds, and a consumer group says you're profiting from counterfeits.",
      o:[ op("Refund affected buyers proactively and recover the money from held seller payouts.", "Held payouts cover most refunds, and the consumer group acknowledges the response.", [5,12,8,-5], true),
          op("Tell buyers to take it up with the sellers directly.", "The sellers have vanished. Buyers go to their banks and chargebacks pile up.", [0,-12,-5,-3]),
          op("Refund only buyers who complain publicly.", "It quiets the loudest voices, until a screenshot of the policy leaks.", [0,-10,-3,0]) ],
      lesson:"Buyer protection is part of your promise. Holding payouts for new sellers is what makes it affordable to make buyers whole." },
    { t:"Following Mon", h:"After the sale",
      s:"The sale is over. The brand wants a standing agreement, and your CEO wants to know why this happened.",
      o:[ op("Give the brand direct takedown access to your listings.", "Takedowns are fast, but the brand starts removing legitimate resale and you face complaints and legal risk.", [0,-8,-3,5]),
          op("Launch a brand protection program: a verified rights-holder portal, a repeat-infringer policy and stronger checks in high-risk categories.", "Takedowns get faster and more accurate, and fakes drop before the holidays.", [8,8,8,-3], true),
          op("Treat it as a one-off and move on.", "The same networks return for the next sale.", [-10,-5,-5,5]) ],
      lesson:"Rights holders are partners, not moderators. A structured program with accuracy checks protects both brands and legitimate sellers." }
  ]},
{ id:"offplatform", types:["marketplace"], title:"The too-good-to-be-true listings", platform:"General marketplace", severity:"Sev 2",
  blurb:"Scammers post cheap consoles and phones, then move buyers off the platform to pay by bank transfer.",
  steps:[
    { t:"Thu 10:00", h:"A new scam pattern",
      s:"Support has 200 reports this week: buyers paid by bank transfer for consoles that never arrived. The listings are new, priced 40% below market, and the seller's first message asks buyers to “pay outside the app to avoid fees”.",
      o:[ op("Warn buyers when a message mentions bank transfers or other apps, and hold new sellers' high-value listings for review.", "Reports fall by half within two days.", [12,5,5,-5], true),
          op("Publish a blog post about staying safe from scams.", "A few people read it. The scams continue.", [0,3,0,0]),
          op("Block every mention of payment methods in messages.", "Scammers switch to code words within hours, and legitimate users are confused by blocked messages.", [3,-5,0,-3]) ],
      lesson:"Intervene in the conversation, at the moment of risk, and add friction where the pattern concentrates: new sellers with cheap high-value items." },
    { t:"Thu 18:00", h:"Victims want their money back",
      s:"Victims paid outside your checkout, so buyer protection doesn't technically apply. Several are older users who lost more than $1,000.",
      o:[ op("Refuse: they paid off-platform, against your terms.", "Victims share their stories, and the headline is about your refusal.", [0,-15,-5,0]),
          op("Refund everyone who claims to be a victim.", "It's costly, and fraudsters start filing fake victim claims.", [0,5,0,-8]),
          op("Make one-time goodwill payments to clearly deceived victims, help them report to their bank and police, and share evidence with law enforcement.", "Victims feel supported, and police link dozens of cases.", [5,10,8,-5], true) ],
      lesson:"“They broke our terms” is rarely a good public answer. Targeted goodwill plus help recovering funds builds trust without inviting fraud." },
    { t:"Fri 12:00", h:"The scammers adapt",
      s:"The same group now uses established accounts with good reviews, hijacked and bought on a forum.",
      o:[ op("Require ID verification for every seller, starting today.", "Fraud drops, but thousands of legitimate sellers abandon verification.", [5,-8,3,-8]),
          op("Detect sudden changes on established accounts: new devices, new payout details, a burst of cheap high-value listings.", "You catch 30 hijacked accounts in a day and return many to their real owners.", [10,5,3,-3], true),
          op("Keep reviewing reports manually.", "The queue grows and scams keep landing.", [-8,-5,0,-8]) ],
      lesson:"Account takeover turns your trust signals against you. Watch for behavior changes on trusted accounts, not only on new ones." },
    { t:"Week 2", h:"Preventing the next wave",
      s:"Leadership asks what should change for good.",
      o:[ op("Remove messaging between buyers and sellers.", "Scams drop, and so do sales. Product reverses it within a month.", [5,-10,0,0]),
          op("Add a line to the terms of service.", "Nothing changes.", [-5,-3,0,3]),
          op("Make protected in-app checkout the default for high-value items, with a clear warning on anything off-platform.", "Most high-value sales move into protected checkout, and scam losses fall sharply.", [10,8,5,0], true) ],
      lesson:"Safe defaults built into the transaction beat warnings and terms. Make the protected path the easy one." }
  ]},
/* ===== Fintech & payments ===== */
{ id:"mules", types:["fintech"], title:"The money mule network", platform:"P2P payments app", severity:"Sev 2",
  blurb:"Young customers are receiving and instantly forwarding stolen money. Many were recruited on social media.",
  steps:[
    { t:"Mon 08:30", h:"An unusual pattern",
      s:"180 accounts opened last month share a pattern: many incoming payments from strangers, forwarded within minutes to a few crypto exchanges. Most holders are 18 to 21. Two banks have flagged payments to these accounts as fraud.",
      o:[ op("Watch for another week to gather more evidence.", "Another $600,000 of victims' money moves through before you act.", [-15,-5,-10,3]),
          op("Freeze all 180 accounts and file suspicious activity reports.", "The flow of stolen money stops. Some innocent customers are caught up and need a fast review path.", [10,0,10,-8], true),
          op("Close the accounts quietly and send the money back to the senders.", "Returning funds without investigation sends some of it straight to the fraudsters' other accounts.", [3,0,-5,-3]) ],
      lesson:"Stop the flow first, then investigate. Freezing and reporting is both a legal duty and the fastest way to protect victims." },
    { t:"Mon 15:00", h:"Some mules are victims too",
      s:"Interviews show many account holders were promised “easy money” online and didn't know the money was stolen. Parents are calling support.",
      o:[ op("Separate recruiters from recruits: offboard the organizers, and give recruits a warning, education and a monitored way back.", "Most recruits cooperate, and a few identify the recruiters.", [5,8,5,-5], true),
          op("Close every account holder's account permanently.", "It's allowed, but students lose access to banking and the press calls it cruel.", [0,-10,0,0]),
          op("Unfreeze anyone who says they didn't know.", "Recruiters coach their mules to say exactly that.", [-10,0,-8,3]) ],
      lesson:"Money-mule networks exploit young people. Tell organizers apart from recruits, and pair enforcement with education." },
    { t:"Tue 10:00", h:"Recruitment is happening elsewhere",
      s:"The recruitment posts are on a large social platform and a messaging app, using your brand name: “get paid through [your app]”.",
      o:[ op("Report the posts with each platform's public report button.", "A few come down after a week. Most stay up.", [3,0,0,0]),
          op("Threaten legal action against the platforms.", "Their legal teams respond slowly and nothing changes this month.", [0,-3,0,-3]),
          op("Share indicators with the platforms' trust & safety teams and your banking partners, and warn your customers.", "The platforms remove hundreds of posts, and banks block linked accounts.", [10,5,5,-3], true) ],
      lesson:"Fraud crosses platforms. Relationships for sharing intelligence, built before a crisis, are what make cross-platform takedowns fast." },
    { t:"Week 2", h:"Preventing the next network",
      s:"Your regulator asks how you'll stop this happening again.",
      o:[ op("Add velocity rules for new accounts that receive from many senders and forward money quickly, with extra checks when they trigger.", "New mule accounts are caught within days instead of weeks.", [10,3,10,-3], true),
          op("Stop letting under-21s open accounts.", "Fraud drops a little. Young customers go elsewhere, and you face age-discrimination questions.", [3,-8,-3,0]),
          op("Rely on your bank partners to catch it.", "The regulator is unimpressed: mule monitoring is your job.", [-5,0,-12,3]) ],
      lesson:"Mule detection is behavioral: money in from many people, money out fast. Build it into monitoring rather than targeting demographics." }
  ]},
{ id:"impersonation", types:["fintech"], title:"The fake fraud team", platform:"Digital bank", severity:"Sev 1",
  blurb:"Scammers are calling customers pretending to be your fraud team and persuading them to move savings to a “safe account”.",
  steps:[
    { t:"Fri 16:00", h:"Customers are losing their savings",
      s:"In two days, 60 customers sent their savings to “safe accounts” after calls from people claiming to be your fraud team, using a spoofed version of your phone number. Losses average $8,000.",
      o:[ op("Wait until Monday to agree a statement with Comms.", "Another 90 customers lose money over the weekend.", [-15,-10,-5,3]),
          op("Block all transfers over $1,000 temporarily.", "Scam losses stop, but thousands of customers can't pay rent or bills.", [5,-12,0,-8]),
          op("Send an urgent in-app alert to every customer: “We will never ask you to move money to a safe account.”", "Calls continue, but many customers hang up. Reported losses drop by two-thirds over the weekend.", [12,8,5,-3], true) ],
      lesson:"In an active scam wave, speed of warning matters most. Tell customers exactly what you will never ask them to do." },
    { t:"Sat 11:00", h:"A scam in progress",
      s:"A customer is trying to send their entire balance to a new payee, minutes after an incoming call. They insist it's urgent.",
      o:[ op("Let it go through: it's the customer's money.", "It's a scam. The customer loses $22,000, and reimbursement rules may make you pay.", [-15,-5,-8,0]),
          op("Pause the payment and have a trained agent call back on a verified number, asking questions designed to break the scammer's script.", "The customer realizes it's a scam and thanks you.", [12,10,5,-3], true),
          op("Freeze the whole account.", "The scam is stopped, but so are the customer's real bills, and they're angry.", [8,-5,0,-3]) ],
      lesson:"Targeted friction at the riskiest moment works best, especially friction that breaks the social-engineering script." },
    { t:"Mon 09:00", h:"Who pays?",
      s:"150 victims want reimbursement. Some were careless; others were elderly and fooled by a spoofed number.",
      o:[ op("Reimburse using a clear policy based on vulnerability and how convincing the scam was, and recover a share from the receiving banks.", "Most victims are reimbursed quickly, and receiving banks share the cost.", [3,10,10,-5], true),
          op("Refuse all claims because customers authorized the payments.", "In the UK this breaks reimbursement rules; elsewhere it becomes a headline.", [0,-15,-12,0]),
          op("Reimburse everyone in full, no questions asked.", "Victims are grateful. Within a month, fraudsters start staging fake scam claims.", [0,5,0,-5]) ],
      lesson:"Reimbursement needs a consistent, documented policy that protects vulnerable customers without rewarding fake claims." },
    { t:"Week 2", h:"Closing the gap",
      s:"The scammers spoofed your number and used customer details from an old data breach.",
      o:[ op("Change your support phone number.", "Scammers spoof the new one within a week.", [0,-3,0,-3]),
          op("Work with phone carriers to block spoofing of your numbers, and show in the app when a call really is from you.", "Impersonation calls drop sharply.", [10,8,5,-3], true),
          op("Tell customers to be more careful in your newsletter.", "Few people read it.", [-3,0,-3,0]) ],
      lesson:"Impersonation scams need channel fixes: authenticated calls, carrier partnerships and in-app confirmation." }
  ]},
/* ===== Gaming ===== */
{ id:"gifting", types:["gaming","kids"], title:"The gifts that weren't gifts", platform:"Kids' multiplayer game", severity:"Sev 1",
  blurb:"A parent reports an adult who befriended their 11-year-old in your game with in-game gifts, then moved the chat to another app.",
  steps:[
    { t:"Tue 19:00", h:"A parent's report",
      s:"A parent emails that an adult player gifted their 11-year-old in-game currency for weeks, then asked them to chat on another app and send photos. They have screenshots. The adult's account is still active.",
      o:[ op("Reply that you'll look into it within your standard three-day review time.", "The account keeps messaging children for three more days.", [-15,-10,-8,3]),
          op("Escalate now: suspend the account, preserve chats and gift records, and report to NCMEC or the police.", "The account is stopped within the hour, and evidence is preserved for investigators.", [15,8,10,-5], true),
          op("Ban the account and delete its data.", "The account is stopped, but the evidence police need is gone.", [8,0,-10,0]) ],
      lesson:"Child-safety reports need their own fast lane. Suspend, preserve evidence and report. Never delete evidence." },
    { t:"Wed 10:00", h:"There are more",
      s:"The account's gift history shows currency sent to 40 other child accounts, and it's linked by device to six other adult accounts.",
      o:[ op("Ban the linked accounts and close the case.", "The other children who were contacted never get support.", [5,-5,-3,0]),
          op("Wait for other parents to report.", "Few children report. The harm stays hidden.", [-10,-5,-5,3]),
          op("Review all 40 conversations and the six linked accounts, and contact the affected families through their parent accounts.", "You find two more children who were asked for images, and their families can act.", [12,8,8,-8], true) ],
      lesson:"One report is often the tip of a pattern. Follow the network and reach the other children affected." },
    { t:"Wed 16:00", h:"Should gifting continue?",
      s:"Your data shows adults gifting currency to children they aren't connected to is rare, but strongly linked to confirmed grooming cases.",
      o:[ op("Block gifts from adults to children they aren't connected to, and flag attempts for review.", "The lure is closed with little effect on normal play.", [12,5,5,-3], true),
          op("Turn off gifting for everyone.", "The lure is gone, but so is a feature families love, and revenue dips.", [8,-5,0,0]),
          op("Keep gifting as it is: it's core to the game.", "Two months later, the pattern appears again.", [-10,-5,-5,3]) ],
      lesson:"Remove the specific mechanics predators exploit, targeting risky combinations rather than whole features." },
    { t:"Week 3", h:"Talking to parents",
      s:"Parents are worried, and a news outlet asks whether your game is safe for children.",
      o:[ op("Say you have “zero tolerance” and decline to give details.", "The reporter notes you didn't describe any changes.", [0,-8,0,0]),
          op("Say the incident was isolated and rare.", "Two more parents come forward the next day.", [-5,-12,-3,0]),
          op("Launch parental controls (chat off by default for under-13s, gift limits, activity summaries) and explain them clearly.", "Parents adopt the controls, and the coverage mentions them.", [10,12,8,-5], true) ],
      lesson:"Give parents real controls and honest explanations. Reassurance without action backfires." }
  ]},
{ id:"swatting", types:["gaming","social"], title:"The swatting threat", platform:"Online multiplayer game", severity:"Sev 1",
  blurb:"A popular streamer is hit by a coordinated harassment campaign that escalates to posting their home address.",
  steps:[
    { t:"Sat 21:00", h:"A harassment campaign",
      s:"A streamer with 500,000 followers is being flooded with slurs in voice and text chat across dozens of matches. Hundreds of brand-new accounts are involved.",
      o:[ op("Limit new accounts from joining the streamer's matches, tighten chat filters in those lobbies, and ban the organizing accounts.", "The flood slows within the hour.", [10,8,3,-5], true),
          op("Tell the streamer to use the block button.", "They can't block hundreds of accounts mid-match. The campaign continues.", [-8,-10,0,3]),
          op("Turn off chat across the whole game for the night.", "The harassment stops, and so does everyone else's game.", [5,-8,0,0]) ],
      lesson:"Coordinated harassment needs coordinated defenses: limits on new accounts, targeted filtering and action against organizers." },
    { t:"Sat 23:30", h:"The address is posted",
      s:"Someone posts the streamer's home address in match chat and on a forum, saying they'll “send a SWAT team”.",
      o:[ op("Remove the post and ban the account.", "The post is gone, but police aren't warned.", [3,0,-3,0]),
          op("Wait until Monday for your legal team.", "A SWAT team arrives at the streamer's home at 3 a.m.", [-20,-15,-8,0]),
          op("Remove the content, preserve evidence, warn local police about a possible swatting call, and tell the streamer.", "Police flag the address, and a hoax call later that night is handled calmly.", [15,10,8,-5], true) ],
      lesson:"Threats to physical safety need a 24/7 emergency path to law enforcement." },
    { t:"Sun 12:00", h:"Where did it come from?",
      s:"The attackers organized in a server on another chat platform and used your game's party system to coordinate.",
      o:[ op("Ban only the accounts that sent slurs.", "The organizers regroup under new accounts.", [0,-3,0,0]),
          op("Share the organizing accounts with the other platform's trust & safety team and ban the linked accounts in your game.", "The other platform removes the server, and the campaign collapses.", [10,5,5,-3], true),
          op("Name the organizers publicly.", "The feud escalates, and the organizers gain followers.", [-5,-8,-3,0]) ],
      lesson:"Harassment is usually organized somewhere else. Cross-platform cooperation and action against organizers break campaigns." },
    { t:"Week 2", h:"Protecting creators",
      s:"Other streamers ask what you'll do to protect them.",
      o:[ op("Say harassment comes with being online.", "Creators leave for a competitor.", [-5,-12,0,0]),
          op("Pay creators to keep streaming.", "Some stay, but they're still unprotected.", [0,-3,0,0]),
          op("Start a creator safety program: priority escalation, lobby protections and private support.", "Creators feel supported, and several who planned to leave stay.", [8,10,3,-3], true) ],
      lesson:"Highly visible users attract concentrated abuse. A dedicated escalation path costs little and builds a lot of trust." }
  ]},
/* ===== Dating ===== */
{ id:"assault", types:["dating"], title:"The date that went wrong", platform:"Dating app", severity:"Sev 1",
  blurb:"A user reports being sexually assaulted by a match. The accused is still active and has more dates lined up.",
  steps:[
    { t:"Sun 10:00", h:"A report of assault",
      s:"A user reports that a match sexually assaulted her on a first date last night. She has told the police. The accused's account is active, and he has three dates arranged this week.",
      o:[ op("Ask her for proof before you act.", "She stops responding. The accused goes on his dates.", [-15,-12,-5,0]),
          op("Warn his upcoming matches that someone has reported him.", "It may breach privacy and defamation law, and the warning leaks.", [5,-5,-8,-3]),
          op("Suspend the accused while you investigate, support the reporter with resources, and preserve evidence for police.", "No further dates happen, and police ask for the preserved data.", [15,8,8,-5], true) ],
      lesson:"For serious offline-harm reports, suspend during the investigation, support the person who reported, and preserve evidence." },
    { t:"Mon 14:00", h:"The accused appeals",
      s:"The accused says it was consensual and threatens to sue. Police are investigating but won't share details.",
      o:[ op("Keep the suspension under your safety policy, which allows action on credible reports without a criminal conviction.", "His lawyer backs off after reading your policy.", [10,5,5,-3], true),
          op("Reinstate him until the police finish.", "He matches with more users, and a second report arrives.", [-15,-10,-5,0]),
          op("Delete his account and data immediately.", "The police investigation loses important evidence.", [5,0,-10,0]) ],
      lesson:"Your safety standard isn't a criminal court's. A clear policy lets you act on credible risk while preserving evidence." },
    { t:"Tue 09:00", h:"He's back",
      s:"A new account with different photos, but the same phone number and device, starts matching in the same area.",
      o:[ op("Require ID checks for everyone in that city.", "He's blocked, but so are many real users, who drop off.", [8,-8,0,-5]),
          op("Ban the new account and link it to the original case.", "You block him again within hours, and the case record stays complete.", [12,5,5,-3], true),
          op("Wait for a new report.", "He goes on a date before anyone reports him.", [-15,-10,-5,0]) ],
      lesson:"Ban evasion is predictable after serious bans. Device, phone and payment signals make repeat offenders catchable." },
    { t:"Week 3", h:"A reporter calls",
      s:"A journalist investigating assaults linked to dating apps asks what you do to prevent them.",
      o:[ op("Explain your safety features (photo verification, date check-ins, how reports are handled) and publish safety numbers.", "The article names you as one of the more responsive apps.", [5,12,5,-3], true),
          op("Point them to your community guidelines.", "The story says you “declined to explain”.", [0,-10,0,0]),
          op("Offer an exclusive on a new feature launch instead.", "The reporter sees it as deflection.", [0,-8,0,0]) ],
      lesson:"Offline harm is the defining risk for dating apps. Be ready to explain prevention and response in specifics." }
  ]}
];
