NEW_SCENARIOS.push(
/* ===== Dating (continued) ===== */
{ id:"romance", types:["dating"], title:"The romance scam ring", platform:"Dating app", severity:"Sev 2",
  blurb:"An organized ring is running romance and investment scams through your app with AI-generated profiles.",
  steps:[
    { t:"Wed 10:00", h:"Complaints spike",
      s:"Reports of users being pushed into crypto “investments” after weeks of chatting have tripled. Many suspect profiles use flawless AI-generated photos and near-identical opening lines.",
      o:[ op("Remove reported profiles one at a time.", "New profiles appear faster than you can remove them.", [0,-3,0,-8]),
          op("Suspend every profile without a verification badge.", "Scams drop, and so do half your real users' matches.", [5,-12,0,-3]),
          op("Cluster the profiles by shared signals (generated-photo traits, scripts, devices, IP ranges) and remove the whole ring.", "2,400 accounts come down in one sweep.", [12,5,5,-3], true) ],
      lesson:"Organized scam rings leave shared fingerprints. Remove them at the network level." },
    { t:"Wed 16:00", h:"Victims are still talking to them",
      s:"Thousands of users were in active conversations with the removed accounts, and some have already sent money.",
      o:[ op("Tell users who chatted with the removed accounts what happened, explain the scam, and link to support and reporting resources.", "Many realize they were being scammed and stop sending money.", [12,10,5,-5], true),
          op("Say nothing: the accounts are gone.", "Victims keep talking to the scammers on the messaging app they'd already moved to.", [-10,-5,0,3]),
          op("Refund everyone's subscription.", "It's appreciated, but it doesn't touch their losses.", [0,3,0,-3]) ],
      lesson:"Removing scammers isn't enough. Warn the people they targeted, because the scam usually continues off-platform." },
    { t:"Thu 11:00", h:"The verification debate",
      s:"Product wants to make photo verification mandatory for new users, which is estimated to cut sign-ups by 8%.",
      o:[ op("Make verification mandatory for everyone today.", "Scams fall, and sign-ups drop more than expected.", [8,-3,0,0]),
          op("Keep verification optional and change nothing.", "The ring returns next month with new profiles.", [-8,-5,0,3]),
          op("Require verification for accounts showing risk signals, and promote a verified badge for everyone else.", "Most scam accounts are stopped with little effect on sign-ups.", [10,5,3,0], true) ],
      lesson:"Risk-based friction targets bad actors while keeping things smooth for everyone else." },
    { t:"Week 2", h:"Following the money",
      s:"Victims' reported losses total $3 million, paid into crypto wallets.",
      o:[ op("Treat it as outside your responsibility, since payments happened elsewhere.", "Victims and regulators disagree.", [-5,-10,-5,3]),
          op("Share wallet addresses and indicators with law enforcement, crypto exchanges and industry groups.", "Exchanges freeze some funds, and two victims recover money.", [10,8,8,-3], true),
          op("Hire a fund-recovery firm for victims.", "Some “recovery firms” are scams themselves, and victims are targeted again.", [-5,-5,0,-3]) ],
      lesson:"Scam losses happen off-platform but start on yours. Sharing intelligence is how platforms help victims recover." }
  ]},
/* ===== Generative AI ===== */
{ id:"deepfake", types:["genai"], title:"The election deepfake", platform:"AI image generator", severity:"Sev 1",
  blurb:"A realistic fake image of a candidate, apparently made with your model, goes viral days before an election.",
  steps:[
    { t:"Tue 07:00", h:"A fake goes viral",
      s:"A realistic image of a presidential candidate in a compromising situation is spreading fast. Its style and metadata suggest your image model made it. Election day is Saturday.",
      o:[ op("Deny it came from your product until someone proves it.", "Researchers prove it that afternoon, and your denial becomes the story.", [0,-15,-8,0]),
          op("Check provenance data and generation logs to confirm the facts, and brief your election response team.", "Within two hours you confirm it, and identify the account.", [5,5,8,-3], true),
          op("Shut down image generation completely.", "Millions of legitimate users lose access, and the fake keeps spreading.", [3,-8,0,-5]) ],
      lesson:"Provenance data and logging let you establish the facts quickly. Know them before you speak." },
    { t:"Tue 11:00", h:"How did it get through?",
      s:"Your policy bans deceptive images of real politicians, but the user described the candidate without naming them and got past the filter.",
      o:[ op("Add the candidate's name to a blocklist.", "Users go back to describing them within hours.", [3,0,0,0]),
          op("Make everyone accept updated terms.", "Nobody reads them, and the images keep coming.", [0,-3,0,0]),
          op("Add likeness detection for election candidates, block photorealistic political images until after the vote, and red-team the fix.", "Attempts drop sharply, and red-teamers find two gaps you close.", [12,5,8,-5], true) ],
      lesson:"Keyword filters get evaded. Test safeguards the way an attacker would, and tighten them during high-risk periods." },
    { t:"Tue 15:00", h:"Platforms and press ask for help",
      s:"Social platforms want to know how to detect images from your model, and journalists want a comment.",
      o:[ op("Share detection signals and provenance data with platforms, and give a factual public statement on what happened and what you've changed.", "Platforms label the fake, and coverage focuses on your fix.", [10,10,8,-3], true),
          op("Talk only to journalists.", "The fake keeps spreading because platforms can't detect it.", [-5,0,0,0]),
          op("Say nothing until after the election.", "The story becomes “AI company silent as deepfake spreads”.", [-5,-12,-5,0]) ],
      lesson:"Industry provenance standards such as C2PA are how generated misinformation gets labeled at scale." },
    { t:"Week 2", h:"After the election",
      s:"Regulators ask what you'll do before the next election.",
      o:[ op("Lift the temporary restrictions and return to normal.", "The same technique shows up in a local election a month later.", [-8,-5,-5,3]),
          op("Publish an elections policy, keep likeness protections, watermark every image, and keep a standing election response team.", "Regulators cite your approach as good practice.", [8,8,10,-3], true),
          op("Ban all political content permanently.", "Satirists and journalists complain loudly.", [3,-8,0,0]) ],
      lesson:"Elections are predictable high-risk periods. Standing policies and teams beat improvised responses." }
  ]},
{ id:"companion", types:["genai","kids"], title:"The chatbot and the teenager", platform:"AI assistant with companion mode", severity:"Sev 1",
  blurb:"A parent shares transcripts showing your chatbot roleplaying romance with their 15-year-old and mishandling a mention of self-harm.",
  steps:[
    { t:"Mon 09:00", h:"A parent's transcripts",
      s:"A parent sends transcripts showing your chatbot roleplayed as a romantic partner with their 15-year-old, and failed to respond appropriately when the teen mentioned self-harm. The parent plans to go to the press.",
      o:[ op("Reply that your terms require users to be 18 or older.", "The parent takes your reply to the press.", [-10,-15,-8,0]),
          op("Have your lawyers respond.", "The parent receives a legal letter and posts it online.", [-5,-12,-5,0]),
          op("Thank the parent, investigate urgently, and check that the teen is safe right now.", "The teen is safe and getting support, and the parent agrees to work with you.", [10,8,5,-3], true) ],
      lesson:"Lead with care for the person at risk. Your terms of service aren't a defense with the public or regulators." },
    { t:"Mon 13:00", h:"What went wrong?",
      s:"Your review finds the model's self-harm safeguards weaken in long roleplay conversations, and age checks are self-declared.",
      o:[ op("Add a crisis classifier that runs on every message whatever the roleplay, route at-risk users to helplines, and block romantic roleplay for accounts with signs of being under 18.", "Crisis responses improve immediately in testing.", [12,5,8,-5], true),
          op("Retrain the model and relaunch in three months.", "The gap stays open in the meantime.", [-8,-5,-5,0]),
          op("Add a disclaimer at the start of every chat.", "Users scroll straight past it.", [0,-3,0,0]) ],
      lesson:"Safety checks that sit outside the conversation hold up better than instructions a model can drift away from." },
    { t:"Tue 10:00", h:"The story runs",
      s:"A national outlet publishes the transcripts, and lawmakers call for action on AI companions.",
      o:[ op("Attack the outlet's reporting.", "The story grows.", [0,-15,-8,0]),
          op("Publish what happened, what you've changed, and your plan for age checks and teen protections.", "Follow-up coverage notes your changes, and lawmakers invite you to testify.", [5,10,8,-3], true),
          op("Remove companion mode in one country only.", "Users move to worse apps, and critics call it a PR move.", [3,-5,0,0]) ],
      lesson:"Being open about failures and fixes rebuilds trust faster than being defensive." },
    { t:"Month 2", h:"Getting ahead of the law",
      s:"New state laws on AI companions are taking effect, and you need a lasting approach.",
      o:[ op("Block under-18s with a checkbox.", "Teens tick the box and keep using it.", [0,-3,-8,0]),
          op("Wait for regulators to say exactly what to do.", "You're fined when the first law takes effect.", [-5,-5,-12,3]),
          op("Introduce risk-based age checks, parental tools for teen accounts, break reminders and published safety evaluations.", "You comply early and set the standard others follow.", [10,8,12,-5], true) ],
      lesson:"Getting ahead of emerging AI companion rules is cheaper than enforcement after the fact." }
  ]},
/* ===== Gig, delivery & rentals ===== */
{ id:"courier", types:["gig"], title:"The courier at the door", platform:"Food delivery platform", severity:"Sev 1",
  blurb:"A customer reports being assaulted by a courier. The courier's account turns out to have been rented to someone else.",
  steps:[
    { t:"Fri 22:00", h:"A report from a customer",
      s:"A customer reports that the courier who delivered her order grabbed her at the door. The account belongs to a verified courier, but his photo doesn't match her description.",
      o:[ op("Ask the customer to confirm the details before acting.", "The account completes 20 more deliveries overnight.", [-15,-10,-5,0]),
          op("Deactivate the account now, contact the customer to offer support, preserve trip data and cooperate with police.", "Police identify the person from trip data within a day.", [15,8,8,-5], true),
          op("Send the courier a warning.", "The warning reaches the account owner, who wasn't the person at the door.", [-8,-5,-3,0]) ],
      lesson:"For physical-safety reports, act first to prevent further harm, then investigate. Preserve trip data for police." },
    { t:"Sat 10:00", h:"Account renting",
      s:"The verified courier admits renting his account to someone who couldn't pass a background check. About 3% of active couriers log in from unusual devices.",
      o:[ op("Deactivate every courier with an unusual login.", "Many honest couriers who changed phones lose income.", [5,-10,-3,-8]),
          op("Email all couriers about the rules.", "Account renting carries on.", [-5,0,0,0]),
          op("Require a selfie check at the start of shifts for accounts with risk signals.", "You find 400 shared accounts in a week.", [12,5,5,-3], true) ],
      lesson:"Account sharing defeats background checks. Re-verify identity at the moment of work, targeted by risk." },
    { t:"Sat 16:00", h:"Couriers push back",
      s:"Courier groups say the selfie checks are invasive and deactivations are unfair, with no way to appeal.",
      o:[ op("Explain why the checks exist, add a fast human appeal for deactivations, and publish how decisions are made.", "Most couriers accept the process, and wrongful deactivations are reversed within 48 hours.", [5,10,5,-5], true),
          op("Ignore them: safety comes first.", "Couriers protest, and a regulator asks about due process.", [0,-10,-5,0]),
          op("Drop the selfie checks.", "Account renting is back within weeks.", [-10,3,0,3]) ],
      lesson:"Enforcement that affects people's income needs a clear explanation and a real appeal." },
    { t:"Week 3", h:"Customer safety",
      s:"Customers ask how they can know the courier at their door is the right person.",
      o:[ op("Recommend customers choose “leave at door”.", "It helps some people, but doesn't solve identity.", [3,0,0,0]),
          op("Show the courier's verified photo and name in the app, and add a safety button that connects to support and emergency services.", "Customers use it and report mismatches faster.", [10,10,5,-3], true),
          op("Do nothing more: the offender was caught.", "A similar incident happens in another city.", [-10,-8,-3,3]) ],
      lesson:"Give both sides of an in-person service the tools to verify each other and get help." }
  ]},
{ id:"camera", types:["gig"], title:"The hidden camera", platform:"Short-term rental platform", severity:"Sev 2",
  blurb:"A guest finds a hidden camera in a rental bedroom and posts the video. It has millions of views, and the host has 40 other listings.",
  steps:[
    { t:"Sun 14:00", h:"A viral video",
      s:"A guest posts a video of a camera hidden in a smoke detector in the bedroom of a listing. It has 3 million views. The host has 40 other listings.",
      o:[ op("Remove just this one listing.", "Guests at the host's other properties find similar devices.", [-10,-10,-5,0]),
          op("Reply publicly that you'll investigate within five business days.", "The reply goes viral for the wrong reasons.", [-5,-15,-3,0]),
          op("Suspend all the host's listings, contact the guest, move them to safe accommodation and preserve evidence.", "The guest thanks you publicly, and police take the device as evidence.", [12,10,5,-5], true) ],
      lesson:"A serious privacy violation by a host says something about all their listings. Act on the whole account, and support the guest first." },
    { t:"Mon 09:00", h:"Past guests",
      s:"1,200 guests have stayed at the host's properties in the past two years.",
      o:[ op("Tell past guests what happened and how to contact the police.", "Several come forward, strengthening the police case.", [10,8,8,-5], true),
          op("Say nothing to past guests: there's no proof they were recorded.", "The press finds past guests first.", [-5,-12,-5,0]),
          op("Send past guests discount codes.", "It reads as buying their silence.", [0,-10,0,0]) ],
      lesson:"Affected people deserve to know. Proactive notification is also often expected by law for privacy harms." },
    { t:"Tue 11:00", h:"The camera policy",
      s:"Your policy allows outdoor cameras if disclosed, but many hosts don't disclose them and nobody checks.",
      o:[ op("Ban all cameras, including doorbells and outdoor security.", "Hosts push back hard, and some safety value is lost.", [5,-5,0,-3]),
          op("Ban cameras in any indoor space, require disclosure of outdoor devices, and add a guest checklist and fast reporting.", "The rules are clear; reports of undisclosed cameras rise and are handled quickly.", [10,8,5,-3], true),
          op("Keep the policy and remind hosts.", "Another incident follows.", [-8,-5,0,3]) ],
      lesson:"Bright-line rules are easier to enforce and easier for guests to understand." },
    { t:"Month 2", h:"Rebuilding trust",
      s:"Bookings in the region are down 6%.",
      o:[ op("Run a discount campaign.", "Bookings rise briefly, but trust doesn't.", [0,0,0,0]),
          op("Pay influencers to post about positive stays.", "It's exposed as paid content and backfires.", [0,-8,-3,0]),
          op("Publish a guest safety report with incident numbers and the new rules.", "Bookings recover as coverage turns positive.", [5,10,5,-3], true) ],
      lesson:"Being open about incidents and fixes rebuilds trust better than marketing." }
  ]},
/* ===== Kids & education ===== */
{ id:"classroom", types:["kids"], title:"The image in the class chat", platform:"School learning app", severity:"Sev 1",
  blurb:"A student shares an explicit image of a classmate in your app's class chat. Teachers and parents want answers.",
  steps:[
    { t:"Tue 11:00", h:"An image in the class chat",
      s:"A 14-year-old posted a nude image of a classmate in a class group chat during school hours. Thirty students saw it before a teacher reported it.",
      o:[ op("Delete the image and the chat, and consider the matter closed.", "Evidence is lost and the school isn't told.", [3,-5,-12,0]),
          op("Remove the image, report it to NCMEC as required, preserve evidence and alert the school's safeguarding lead.", "The school's safeguarding process starts within the hour, and the image is blocked by hash.", [15,8,10,-5], true),
          op("Suspend the whole class chat until further notice.", "The image lives on in screenshots, and lessons are disrupted.", [3,-5,0,-3]) ],
      lesson:"Sexual images of minors must be reported even when the sender is a minor. Bring the school in through its safeguarding process." },
    { t:"Tue 15:00", h:"Screenshots are spreading",
      s:"Students took screenshots and are sharing the image in other chats on your app.",
      o:[ op("Ask teachers to tell students to delete it.", "Some do. Many don't.", [3,0,0,0]),
          op("Remove image uploads for every user.", "Teachers lose a core feature for lessons.", [5,-8,0,-3]),
          op("Hash-match the image across the app to block re-uploads, and help the victim submit it to NCMEC's Take It Down.", "Re-shares are blocked automatically, including on other participating platforms.", [15,8,8,-3], true) ],
      lesson:"Hash matching stops re-sharing at scale, and Take It Down extends protection beyond your own app." },
    { t:"Wed 10:00", h:"Parents demand changes",
      s:"Parents ask why students can send images to each other at all.",
      o:[ op("Turn off image sharing between students by default, keep teacher-approved sharing, and add nudity detection on images.", "Parents and schools welcome the change.", [10,10,5,-3], true),
          op("Explain that the student broke the rules.", "Parents feel dismissed.", [0,-10,0,0]),
          op("Remove student chat entirely.", "Group work stops working, and schools consider switching.", [5,-8,0,0]) ],
      lesson:"Protective defaults for children, with exceptions controlled by adults, balance safety and learning." },
    { t:"Week 2", h:"Your school customers",
      s:"School districts ask for your safeguarding policy before renewing contracts.",
      o:[ op("Send a one-page assurance letter.", "Two districts pause renewals to ask more questions.", [0,-5,-3,0]),
          op("Publish a safeguarding policy with incident procedures, response times and commitments to notify schools.", "Renewals go ahead, and the policy becomes a sales advantage.", [5,10,8,-3], true),
          op("Offer a discount instead.", "Districts still ask for the policy.", [0,-5,0,0]) ],
      lesson:"For children's products, safeguarding documentation is part of what customers are buying." }
  ]},
{ id:"comments", types:["kids","social"], title:"The comment section problem", platform:"Video app popular with families", severity:"Sev 1",
  blurb:"A researcher shows adults leaving predatory, timestamped comments on videos of young children, and recommendations feeding them more.",
  steps:[
    { t:"Mon 08:00", h:"A researcher's thread",
      s:"A researcher publishes a thread showing adults leaving timestamped comments on videos of young children doing gymnastics, and recommendations leading from one such video to the next.",
      o:[ op("Remove the specific comments in the thread.", "The researcher finds hundreds more the next day.", [3,-8,0,-3]),
          op("Say comments are moderated by the community.", "Advertisers start pausing campaigns.", [-10,-15,-5,0]),
          op("Turn off comments on videos featuring young children, and remove the accounts leaving predatory comments.", "The comment network is disrupted within hours.", [15,8,8,-5], true) ],
      lesson:"When a feature creates a pattern of exploitation, change the feature for at-risk content, not just the individual violations." },
    { t:"Mon 14:00", h:"The recommendation loop",
      s:"Your recommender has learned that some viewers watch many videos of young children, and it's serving them more.",
      o:[ op("Stop recommending content featuring young children to accounts showing this pattern, and review those accounts.", "The loop breaks, and several accounts are escalated to law enforcement.", [12,8,8,-5], true),
          op("Keep recommending: it's what those users engage with.", "The pattern continues, and a second report exposes it.", [-15,-12,-8,0]),
          op("Remove every video featuring children.", "Families and child creators lose their content, and the backlash is huge.", [5,-10,0,-3]) ],
      lesson:"Recommendation systems can learn predatory patterns. Monitor engagement patterns around children's content." },
    { t:"Tue 10:00", h:"Advertisers pause",
      s:"Major advertisers have paused spending until you explain what you're doing.",
      o:[ op("Offer discounts to win them back.", "Advertisers want fixes, not discounts.", [0,-5,0,0]),
          op("Brief advertisers on the specific changes, give them brand-safety controls and commit to independent auditing.", "Most advertisers return within weeks.", [3,8,5,-3], true),
          op("Wait it out.", "The pause turns into a boycott.", [0,-10,0,0]) ],
      lesson:"Advertisers respond to concrete safety changes and independent verification." },
    { t:"Month 2", h:"Children as creators",
      s:"Parents who film their children want to keep posting.",
      o:[ op("Ban children from appearing in videos.", "It can't be enforced and it alienates families.", [3,-8,0,-5]),
          op("Go back to the old settings.", "The pattern returns within a month.", [-12,-8,-5,3]),
          op("Offer parent-managed accounts for content featuring under-13s, with comments off, limited discovery and monetization rules.", "Families keep posting with far lower risk.", [10,8,8,-3], true) ],
      lesson:"Design protections for children who appear in content, not only for children who use the product." }
  ]}
);
// The original three scenarios keep their positions so saved runs still open; tag their company types.
SCENARIOS[0].types = ["social","kids"]; SCENARIOS[1].types = ["social"]; SCENARIOS[2].types = ["social"];
SCENARIOS.push(...NEW_SCENARIOS);
const TT_TYPES = [
  {k:"all", n:"All company types", s:"every kind of"},
  {k:"social", n:"Social media & video", s:"social media and video"},
  {k:"marketplace", n:"Marketplace & e-commerce", s:"marketplace and e-commerce"},
  {k:"fintech", n:"Fintech & payments", s:"fintech and payments"},
  {k:"gaming", n:"Gaming", s:"gaming"},
  {k:"dating", n:"Dating", s:"dating"},
  {k:"genai", n:"Generative AI", s:"generative AI"},
  {k:"gig", n:"Gig, delivery & rentals", s:"gig, delivery and rental"},
  {k:"kids", n:"Kids & education", s:"kids' and education"}
];
function ttCompanyType(){
  const saved = store.get("tt:type", null);
  if(saved && TT_TYPES.some(t=>t.k===saved)) return saved;
  const map = {social:"social", video:"social", creator:"social", messaging:"social", marketplace:"marketplace", fintech:"fintech", crypto:"fintech", gaming:"gaming", dating:"dating", genai:"genai", gig:"gig", rentals:"gig", edtech:"kids"};
  return (typeof pm !== "undefined" && pm && map[pm.type]) || "all";
}
