/* =========================================================
   BY COMPANY TYPE: the same questions, in the words of your platform
   Coverage asks about the harms as they show up on your kind of service; Maturity says what each area means there.
   ========================================================= */
// How each kind of harm shows up, by company type. Coverage's questions use these instead of the generic noun
const TYPE_HARM = {
  social:{child:"grooming and child sexual abuse material in feeds, comments and DMs", sexual:"unwanted sexual content and intimate images shared without consent", harass:"pile-ons, hate and targeted harassment in comments and replies", violent:"graphic violence, self-harm content and threats", ai:"AI-generated fakes and impersonation", privacy:"doxxing and location leaks", integrity:"spam, fake accounts and coordinated manipulation", fraud:"scams in DMs and fake giveaways"},
  marketplace:{child:"listings or messages that put children at risk", sexual:"sexual services, adult items and explicit listings", harass:"abusive messages between buyers and sellers", violent:"weapons, violent items and threats in messages", ai:"AI-generated fake product photos and reviews", privacy:"buyer and seller personal data exposed in listings or messages", integrity:"fake reviews, bot listings and shill bidding", fraud:"scam listings, fake sellers and payment fraud"},
  fintech:{child:"accounts opened by or for minors", sexual:"sextortion payments and adult-service transactions", harass:"abusive payment notes and harassment through transfers", violent:"payments tied to threats or extortion", ai:"AI-driven synthetic identities and voice-clone social engineering", privacy:"account takeover and data exposure", integrity:"mule accounts, fake merchants and money laundering", fraud:"scam payments, phishing and chargeback fraud"},
  gaming:{child:"grooming and predatory contact in chat and voice", sexual:"sexual content in chat, usernames and user-made content", harass:"toxicity, hate speech and harassment in voice and text chat", violent:"real-world threats and self-harm talk in chat", ai:"AI-generated cheats, deepfakes and impersonation", privacy:"doxxing and swatting", integrity:"cheating, bots and account trading", fraud:"account theft, skin scams and payment fraud"},
  dating:{child:"minors on the platform and adults seeking them", sexual:"unsolicited sexual images and sexual coercion", harass:"abusive messages after rejection", violent:"threats, stalking and violence at in-person meetings", ai:"AI-generated profile photos and chatbot romance scams", privacy:"real names, workplaces and locations exposed to matches", integrity:"fake profiles and catfishing", fraud:"romance scams and investment pitches from matches"},
  genai:{child:"prompts for sexual content involving minors", sexual:"non-consensual intimate imagery and sexual deepfakes", harass:"harassing or hateful content generated on request", violent:"instructions for violence and self-harm content", ai:"jailbreaks, deepfakes and impersonation at scale", privacy:"personal data leaked in outputs and voice cloning", integrity:"automated spam and disinformation at scale", fraud:"generated phishing and scam scripts"},
  gig:{child:"underage workers and children present at jobs or rentals", sexual:"sexual harassment between workers, customers and hosts", harass:"abusive ratings, messages and in-person abuse", violent:"assaults and threats during jobs, rides or stays", ai:"AI-faked identity documents and profile photos", privacy:"home addresses and phone numbers exposed to the other party", integrity:"fake accounts, rating manipulation and account sharing", fraud:"payment scams, fake bookings and chargeback abuse"},
  kids:{child:"predatory contact and inappropriate content reaching children", sexual:"sexual content reaching children and adults soliciting them", harass:"bullying between children", violent:"violent or frightening content and self-harm talk", ai:"AI-generated content reaching children unchecked", privacy:"children's data collected or shared without consent", integrity:"adults posing as children and spam aimed at kids", fraud:"in-app purchase tricks and scams aimed at children"}
};
// What each program area means on each kind of platform, shown under the maturity question and on the roadmap
const TYPE_AREA = {
  social:{policy:"Rules for comments, DMs, live streams and creator content, with examples reviewers can apply.", detection:"Classifiers on uploads and comments, hash matching for known abuse imagery, and signals for coordinated behaviour.", operations:"Queues by severity, with live content and DMs handled fastest.", quality:"Appeals on removals and account actions, with overturn rates fed back to policy.", crisis:"A playbook for viral harmful content, a creator incident or a press story about the platform.", measurement:"Prevalence from sampled views, time to action on reports, and appeal overturn rates.", compliance:"DSA statements of reasons, transparency reports and UK Online Safety Act duties.", wellbeing:"Exposure limits for reviewers of graphic and sexual content, with counselling available."},
  marketplace:{policy:"Prohibited-item rules, seller standards and messaging rules, with examples for reviewers.", detection:"Listing classifiers, image matching for prohibited items, and seller-behaviour signals.", operations:"Listing review before and after publication, and seller-dispute handling with time targets.", quality:"Seller appeals on removals and suspensions, with a second reviewer.", crisis:"A playbook for a recalled or dangerous item, a scam wave or a seller-data leak.", measurement:"Prohibited-listing prevalence, fraud loss rate and time to remove reported listings.", compliance:"DSA trader-traceability duties, product-safety obligations and consumer law.", wellbeing:"Support for reviewers handling abusive messages and disturbing listings."},
  fintech:{policy:"Acceptable-use, scam and mule-account rules that fraud, compliance and support all apply the same way.", detection:"Transaction monitoring, device and identity signals, and scam-pattern detection before money moves.", operations:"Alert queues with time targets, and a path from support to fraud specialists.", quality:"A fair way to contest frozen funds or closed accounts, reviewed by someone new.", crisis:"A playbook for a scam wave, an account-takeover spike or a regulator inquiry.", measurement:"Fraud loss rate, scam reports per thousand users and time to freeze.", compliance:"AML and KYC duties, consumer-protection rules and payment-scheme requirements.", wellbeing:"Support for staff who talk to scam victims every day."},
  gaming:{policy:"Chat, username and user-content rules, with examples from real matches.", detection:"Text and voice moderation, cheat detection and signals for grooming patterns.", operations:"In-game reports triaged by severity, with fast handling for child-safety and threats.", quality:"Appeals on bans and mutes, with a second look at contested calls.", crisis:"A playbook for a child-safety incident, a swatting threat or a toxic community event.", measurement:"Toxicity per thousand match-hours, report handling time and repeat-offender rate.", compliance:"Age-appropriate design duties, loot-box rules and platform-holder requirements.", wellbeing:"Rotation and support for reviewers of voice chat and abusive content."},
  dating:{policy:"Rules for profiles, messages and conduct at meetings, with examples reviewers can apply.", detection:"Photo verification, fake-profile signals, and detection of scam and sexual-image patterns in messages.", operations:"Reports on unmatched users still handled, with fast action on safety threats.", quality:"Appeals on bans, with care for users reporting harm.", crisis:"A playbook for an assault report, a romance-scam ring or a data exposure.", measurement:"Fake-profile prevalence, romance-scam reports and time to act on safety reports.", compliance:"Consumer law, data-protection duties and local dating-safety rules.", wellbeing:"Support for reviewers handling sexual content and assault reports."},
  genai:{policy:"Usage policies for prompts and outputs, with examples of what to refuse and what to allow.", detection:"Input and output classifiers, hash matching for known abuse imagery, and red-teaming for jailbreaks.", operations:"Review of flagged generations and abuse reports, with fast handling for child-safety content.", quality:"A way to contest refusals and account actions, with a second reviewer.", crisis:"A playbook for a viral harmful generation, a jailbreak in the wild or a deepfake incident.", measurement:"Refusal accuracy, harmful-output rate in sampled generations and time to patch a jailbreak.", compliance:"AI Act transparency duties, DSA obligations where you host content, and child-safety law.", wellbeing:"Exposure limits and support for red-teamers and reviewers of generated abuse content."},
  gig:{policy:"Conduct rules for workers, customers and hosts, with examples for both sides of a job.", detection:"Identity checks, fake-account signals and detection of abusive messages.", operations:"Safety reports from jobs, rides and stays handled fast, with a path to the police where needed.", quality:"Appeals on deactivations, reviewed by someone who wasn't involved.", crisis:"A playbook for an assault, a fatality or a worker-data leak.", measurement:"Safety incidents per thousand jobs, time to act on safety reports and deactivation appeal rates.", compliance:"Worker-classification law, background-check rules and local licensing.", wellbeing:"Support for staff who handle assault and accident reports."},
  kids:{policy:"Rules written for children and parents, with examples of what's allowed at each age.", detection:"Classifiers tuned for content reaching children, and signals for adults posing as children.", operations:"Reports from children and parents handled fast, with child-safety escalations first.", quality:"A way for parents to contest decisions, in plain language.", crisis:"A playbook for a predator incident, a data breach involving children or a harmful viral trend.", measurement:"Inappropriate-content prevalence in what children see, and time to act on reports.", compliance:"COPPA, age-appropriate design codes and school-data rules.", wellbeing:"Support for reviewers of content involving children."}
};
// One line for the home, before the first step is done: where programs like yours usually start
const TYPE_TIP = {
  social:"Programs like yours usually find their first gap in proactive detection: most harm is still found by user reports.",
  marketplace:"Marketplaces usually find their first gap in fraud and prohibited listings, where loss shows up in the P&L before it shows up in reports.",
  fintech:"Fintech programs usually find their first gap in scam response: detection is strong, but victims wait too long for a person.",
  gaming:"Gaming programs usually find their first gap in voice and chat moderation, where child-safety risk hides in plain sight.",
  dating:"Dating programs usually find their first gap in what happens after a match: off-platform contact and in-person safety.",
  genai:"AI programs usually find their first gap in output monitoring: refusals are tested, but what gets through isn't measured.",
  gig:"Gig and rental programs usually find their first gap in incident response: safety reports from jobs and stays reach the wrong queue.",
  kids:"Children's services usually find their first gap in parental consent and data handling, which COPPA now checks closely."
};
const typeKey = () => (typeof orgGet === "function" && orgGet().type) || "";
const typeHarm = (k, fallback) => (TYPE_HARM[typeKey()] || {})[k] || fallback;
const typeArea = k => (TYPE_AREA[typeKey()] || {})[k] || "";
const typeName = () => { const t = typeof TT_TYPES !== "undefined" && TT_TYPES.find(x => x.k === typeKey()); return t ? t.s : ""; };
