NEW_SCENARIOS.push(
/* ===== Gaming (more) ===== */
{ id:"ugcextremism", types:["gaming"], title:"The recreated attack", platform:"Game with user-built worlds", severity:"Sev 1",
  blurb:"A user-built world recreating a real mass shooting is trending among teenage players.",
  steps:[
    { t:"Fri 16:00", h:"A trending world",
      s:"A user-built world recreating last month's mass shooting, with the attacker's manifesto on the walls, has 80,000 visits, mostly from teenagers. A news outlet has just noticed.",
      o:[ op("Take the world down, preserve it as evidence, and ban the creator's account.", "It's gone within minutes, and copies are blocked by matching the world's assets.", [15,8,8,-5], true),
          op("Add an age warning to the world.", "Visits double, and the story is about your warning label.", [-12,-12,-5,0]),
          op("Review it on Monday with the policy team.", "Copies spread across the weekend.", [-12,-8,-5,3]) ],
      lesson:"Content glorifying real attacks should come down immediately, with evidence preserved and copies blocked." },
    { t:"Fri 20:00", h:"Copies and a network",
      s:"Twelve copies have appeared. The creator belongs to a group that has built other extremist worlds and recruits players into a private chat server.",
      o:[ op("Remove copies as they're reported.", "New copies appear faster than the reports.", [-5,-5,0,-8]),
          op("Match copies by shared assets and scripts, remove the group's other worlds, and refer the recruitment to law enforcement and industry partners.", "The group's presence is removed in one sweep, and industry partners are alerted.", [12,5,8,-5], true),
          op("Shut down world-building for everyone this weekend.", "Millions of legitimate creators are blocked.", [5,-10,0,-3]) ],
      lesson:"Extremist content comes from networks. Match copies by their parts and act against the whole network." },
    { t:"Sat 11:00", h:"Players who visited",
      s:"80,000 players visited, many of them young, and some joined the recruitment server.",
      o:[ op("Do nothing more: the content is gone.", "Some young players are drawn further into the group elsewhere.", [-10,-5,-3,3]),
          op("Show visitors a message with counter-extremism resources, and redirect searches about the attack to credible information.", "Several parents contact counter-extremism services for help.", [8,8,5,-3], true),
          op("Ban all 80,000 visitors.", "Curious teenagers are punished, and parents are furious.", [0,-12,0,-5]) ],
      lesson:"People exposed to extremist content may need redirection and support, not punishment." },
    { t:"Week 2", h:"Prevention",
      s:"Leadership asks how to catch the next one before it trends.",
      o:[ op("Require approval for every new world.", "Reviews take weeks, and creators leave.", [5,-10,0,-10]),
          op("Rely on player reports.", "The next world reaches 50,000 visits first.", [-8,-5,-5,3]),
          op("Check new worlds' names, text and assets against extremist indicators, and review fast-rising worlds before they reach recommendations.", "Two similar worlds are caught before they trend.", [12,5,8,-5], true) ],
      lesson:"Proactive detection plus a check before content is amplified catches harm before it spreads." }
  ]},
{ id:"lootbox", types:["gaming"], title:"The $3,000 bill", platform:"Mobile game", severity:"Sev 2",
  blurb:"A 12-year-old spends $3,000 on loot boxes in two weeks, the parent's post goes viral, and a regulator starts asking questions.",
  steps:[
    { t:"Mon 09:00", h:"A parent's complaint",
      s:"A parent's card statement shows their 12-year-old spent $3,000 on randomized item packs in two weeks, using a saved card. The parent posts it online and it goes viral.",
      o:[ op("Refuse: the purchases were made with a saved card.", "The story spreads, and a regulator takes notice.", [0,-15,-8,0]),
          op("Refund the purchases, contact the parent, and add a spending limit to the child's account.", "The parent posts an update thanking you.", [5,10,3,-3], true),
          op("Refund quietly and ask the parent to delete the post.", "The parent posts your request too.", [0,-10,0,0]) ],
      lesson:"When children overspend, generous refunds and immediate controls cost far less than the damage to your reputation." },
    { t:"Tue 10:00", h:"Why was it possible?",
      s:"Your data shows 4% of under-16 players spent more than $500 last year, and purchases don't require a password.",
      o:[ op("Leave it to parents to set up controls.", "Few parents know the controls exist.", [-5,-5,-5,3]),
          op("Stop selling to under-18s entirely.", "Children lie about their age, and revenue falls without solving the problem.", [3,-5,0,0]),
          op("Require a password or parent approval for every purchase by under-18s, with monthly spending limits on by default.", "Big spends by children drop sharply, with little effect on adult revenue.", [10,8,8,-5], true) ],
      lesson:"Protections that are on by default work better than controls parents don't know about." },
    { t:"Week 2", h:"The regulator's letter",
      s:"A consumer regulator asks whether your randomized packs are designed to pressure children into buying, and whether the odds are disclosed.",
      o:[ op("Answer openly, publish drop odds, remove countdown timers and “last chance” prompts for children, and show purchase history clearly.", "The regulator closes the inquiry with recommendations.", [8,8,12,-3], true),
          op("Argue that loot boxes aren't gambling.", "The regulator notes you didn't answer its questions.", [0,-5,-10,0]),
          op("Remove randomized packs in that one country.", "Regulators elsewhere take note.", [3,0,-3,-3]) ],
      lesson:"Regulators focus on design that pressures children. Disclose odds and remove manipulative prompts." },
    { t:"Month 3", h:"The next season",
      s:"Product is planning a new season with a limited-time pack.",
      o:[ op("Launch it as planned.", "Complaints from parents spike again.", [-8,-8,-5,3]),
          op("Review the design for manipulative patterns before launch, and build in child protections.", "The season launches with fewer complaints and steady revenue.", [8,8,8,-3], true),
          op("Cancel the season.", "Players are disappointed and revenue falls.", [0,-5,0,0]) ],
      lesson:"Build a design and safety review into every launch aimed at young players." }
  ]},
/* ===== Dating (more) ===== */
{ id:"minor", types:["dating"], title:"The 15-year-old on the app", platform:"Dating app (18+)", severity:"Sev 1",
  blurb:"A member reports that their match says she's 15. The account has matched with 40 adults.",
  steps:[
    { t:"Thu 20:00", h:"A report about age",
      s:"A member reports that their match said she's 15 and in high school. Your app is 18+ with self-declared ages. The account has matched with 40 adults and is chatting with several.",
      o:[ op("Ask the user to confirm her age.", "She says she's 18 and keeps chatting.", [-12,-5,-5,0]),
          op("Suspend the account right away, and review its conversations for adults who carried on after learning her age.", "You find two adults who kept pursuing her after she said she was 15.", [15,8,8,-5], true),
          op("Ignore it: users must be 18 under your terms.", "An adult arranges to meet her.", [-20,-15,-10,3]) ],
      lesson:"Treat reports of minors on adult platforms as urgent child-safety cases." },
    { t:"Thu 22:00", h:"The adults",
      s:"Two adult members kept pursuing her after she said she was 15, and one asked to meet.",
      o:[ op("Warn the adults.", "One of them contacts her on another app.", [-10,-5,-8,0]),
          op("Ban both and delete their data.", "The evidence police need is gone.", [5,0,-10,0]),
          op("Ban both, preserve the evidence, and report them to NCMEC or the police.", "Police open an investigation into the adult who asked to meet.", [15,5,10,-5], true) ],
      lesson:"Adults who pursue someone they know is a minor must be reported, with evidence preserved." },
    { t:"Fri 10:00", h:"Supporting her",
      s:"Her account is suspended, and you can reach her by email.",
      o:[ op("Send a kind message explaining why the account was closed, with links to support services for young people.", "She replies that she hadn't realized the danger.", [8,8,3,-3], true),
          op("Send a standard terms-violation notice.", "She opens a new account with a different birthday.", [-5,-5,0,0]),
          op("Try to contact her parents directly.", "You don't know who they are, and you risk exposing her.", [0,-5,-5,0]) ],
      lesson:"Communicate with care when minors break age rules. The goal is their safety, not punishment." },
    { t:"Week 2", h:"Keeping minors off",
      s:"Your data suggests about 0.5% of new sign-ups may be under 18.",
      o:[ op("Add a stronger warning to the sign-up form.", "Minors click straight past it.", [0,0,-3,0]),
          op("Require ID uploads from every user.", "Many adults drop out, and minors borrow adults' IDs.", [5,-8,0,-5]),
          op("Add age estimation at sign-up when risk signals appear, detect language suggesting a user is a minor, and add “may be under 18” as a report reason.", "Suspected minors are caught much earlier.", [12,5,8,-5], true) ],
      lesson:"Age assurance works best in layers, with extra checks where risk signals appear." }
  ]},
{ id:"location", types:["dating"], title:"The location leak", platform:"Dating app popular with LGBTQ people", severity:"Sev 1",
  blurb:"A researcher shows your “distance away” feature can pinpoint members' homes, including in countries where being gay is a crime.",
  steps:[
    { t:"Mon 08:00", h:"A researcher's disclosure",
      s:"A security researcher shows that by checking the “distance away” figure from three fake locations, anyone can pinpoint a member's home to within 10 meters. Your app is widely used by LGBTQ people, including in countries where same-sex relationships are criminalized.",
      o:[ op("Ask the researcher not to publish while you fix it next quarter.", "The researcher publishes in 30 days as planned, with the flaw still open.", [-10,-10,-5,0]),
          op("Thank the researcher, round and blur distances today, and block the rapid location changes the attack relies on.", "The attack stops working the same day.", [15,8,8,-5], true),
          op("Threaten legal action against the researcher.", "The story becomes about you silencing a researcher.", [-5,-15,-5,0]) ],
      lesson:"Location data can put lives at risk. Fix precision flaws immediately and work with the researcher." },
    { t:"Mon 15:00", h:"The members most at risk",
      s:"Members in countries that criminalize same-sex relationships face the greatest danger if they're located.",
      o:[ op("Keep the same settings for everyone.", "Advocacy groups warn members to stop using the app.", [-12,-10,0,3]),
          op("Pull out of those countries overnight.", "Members lose a lifeline, often with no warning.", [0,-10,0,0]),
          op("Turn off distance display by default in those countries, offer a hidden-location mode, and add a discreet app icon option.", "Advocacy groups praise the changes.", [15,10,5,-5], true) ],
      lesson:"Protect members in the most dangerous places by default, working with local advocacy groups." },
    { t:"Tue 11:00", h:"Was it used?",
      s:"Logs suggest the technique may have been used against some members in the past year.",
      o:[ op("Say there's no evidence of harm.", "Researchers later show it was used.", [-5,-12,-8,0]),
          op("Investigate the logs, notify members who may have been targeted with safety advice, and inform data-protection regulators.", "Members can take precautions, and regulators note the prompt notification.", [10,8,10,-5], true),
          op("Delete the logs to limit liability.", "That's destruction of evidence.", [-5,-10,-15,0]) ],
      lesson:"When a flaw may have been exploited, investigate and notify. People need to know if their safety was at risk." },
    { t:"Month 2", h:"Safety by design",
      s:"Leadership asks how to stop location features creating risks in future.",
      o:[ op("Add a privacy and safety review for every location feature, with threat modeling for stalking and for targeting of marginalized groups.", "The next location feature ships with protections built in.", [10,8,8,-3], true),
          op("Remove all location features.", "Matching gets worse, and members leave.", [5,-8,0,0]),
          op("Rely on bug-bounty reports.", "An attacker finds the next flaw first.", [-8,-5,-5,3]) ],
      lesson:"Threat-model location features for stalking and persecution before they ship." }
  ]}
);
