/* =========================================================
   ABUSE PRE-MORTEM: HARM LIBRARY
   sev: 1 Limited, 2 Serious, 3 Severe, 4 Critical (inherent harm)
   base + drivers - reducers = likelihood (1 Rare to 4 Expected)
   up: conditions that raise severity by one level
   ========================================================= */
const HARMS = [
/* Child safety */
{id:"csam", cat:"child", n:"Child sexual abuse material (CSAM)", sev:4, base:2,
 d:"Imagery of child sexual abuse is uploaded, stored or traded. Any service that hosts images or video will be targeted, whatever its intended audience.",
 req:c=>c.hostsMedia,
 drv:c=>[[(c.anon&&c.F("signup"))||c.guest,1,c.guest?"Guests can upload without an account":"Accounts can be created without verified identity"],[c.F("dm")||c.F("files")||c.F("groups"),1,"Private sharing spaces are preferred for trading abuse material"],[c.big,1,"Offenders target large platforms"]],
 red:c=>[[c.verified,1,"Verified identity deters offenders"]],
 sg:c=>["csam_hash","csam_reporting","csam_review","report_btn","moderator_wellness"]},
{id:"grooming", cat:"child", n:"Grooming and online enticement", sev:4, base:2,
 d:"Adults build trust with children in private, then push for images, meetings or a move to another app.",
 req:c=>c.minors&&(c.F("dm")||c.F("voice")||c.F("groups")||c.F("live"))&&!c.noContact,
 drv:c=>[[c.strangers,1,"Adults can find and contact young users they don't know"],[c.realtime,1,"Voice and live video are hard to monitor"],[c.kids,1,"The product is built for children"],[c.M("wallet"),1,"Gifts and virtual currency are common grooming lures"],[c.guest,1,"Guests can chat without any account to trace"]],
 red:c=>[[c.p.youth==="adult_self",1,"Adults-only by terms, so fewer minors are present"],[c.limited,1,"Contact requires a connection first"]],
 sg:c=>["minor_contact","teen_defaults","age_assurance","grooming_signals","report_btn","block_mute","csam_reporting","csam_review",c.kids&&"parental_tools"]},
{id:"age_content", cat:"child", n:"Children exposed to age-inappropriate content", sev:3, base:1,
 d:"Young users see sexual, violent or otherwise mature content, often pushed to them by recommendations or generated on request.",
 req:c=>c.minors&&(c.F("posts")||c.F("media")||c.F("discovery")||c.F("live")||c.F("ai_chat")||c.F("ai_gen")),
 drv:c=>[[c.F("discovery"),1,"Recommendations can push mature content to young users"],[c.p.youth==="adult_self",1,"No age checks, so under-18s get the adult experience"],[c.adult,2,"Nudity or sexual content is allowed"],[c.F("ai_chat")||c.F("ai_gen"),1,"AI can produce mature content on request"]],
 sg:c=>["age_assurance","teen_defaults","media_classifier","rec_safety"]},
{id:"underage", cat:"child", n:"Under-age users on an adult-only service", sev:3, base:3,
 d:"Self-declared age is easy to lie about. Children end up in spaces designed for adults.",
 req:c=>c.p.youth==="adult_self",
 drv:c=>[[c.explicit||c.T("dating","creator"),1,"Adult content or adult contact makes under-18 access especially harmful"]],
 up:c=>[[c.explicit,"Children could reach sexually explicit content"]],
 sg:c=>["age_assurance","underage_removal"]},
{id:"kids_data", cat:"child", n:"Unlawful collection or use of children's data", sev:3, base:2,
 d:"Children's personal data is collected, profiled or shared without the consent and protections the law requires.",
 req:c=>c.youth,
 drv:c=>[[c.kids,1,"Under-13s are a core audience"],[c.F("ads"),1,"Advertising relies on profiling that is restricted for children"],[c.F("location"),1,"Location data about children is especially sensitive"]],
 sg:c=>[c.kids&&"parental_consent","data_minimization","no_minor_ads","teen_defaults"]},
{id:"compulsive", cat:"child", n:"Manipulative design and compulsive use by young users", sev:2, base:2,
 d:"Streaks, endless feeds and spending mechanics exploit young users' developing self-control.",
 req:c=>c.youth&&(c.F("discovery")||c.M("wallet")||c.F("live")||c.T("gaming","social","video")),
 drv:c=>[[c.M("wallet"),1,"Virtual currency and randomized rewards encourage spending"],[c.F("discovery"),1,"Endless feeds and autoplay encourage compulsive use"]],
 sg:c=>["design_review_minors",c.M("wallet")&&"spending_controls","teen_defaults"]},
/* Sexual exploitation */
{id:"sextortion", cat:"sexual", n:"Sextortion", sev:3, base:1,
 d:"Victims are pressured into sharing intimate images, then blackmailed for money or more images. Organized gangs run this at scale.",
 req:c=>(c.F("dm")||c.F("voice"))&&!c.noContact,
 drv:c=>[[c.strangers,1,"Strangers can start private conversations"],[c.T("dating","social","gaming","messaging"),1,"Sextortion gangs target dating, social and gaming apps"],[c.F("media")||c.F("voice"),1,"Images or video can be exchanged privately"]],
 red:c=>[[c.verified,1,"Verified identity makes extortion riskier for offenders"]],
 up:c=>[[c.minors,"Teenagers are the most common targets, and cases have ended in suicide"]],
 sg:c=>["dm_nudity_blur","sextortion_signals",c.minors&&"minor_contact","report_btn","takeitdown","crisis_resources"]},
{id:"ncii", cat:"sexual", n:"Intimate images shared without consent", sev:3, base:2,
 d:"Intimate images, including sexual deepfakes, are shared without the consent of the person shown.",
 req:c=>c.hostsMedia||c.F("ai_gen"),
 drv:c=>[[c.F("posts")||c.F("groups"),1,"Images can be shared publicly or to large groups"],[c.F("ai_gen"),1,"AI tools can create sexual deepfakes of real people"],[c.adult,1,"Sexual content is allowed, so abuse imagery is harder to spot"]],
 sg:c=>["ncii_process","takeitdown","report_btn","media_classifier",c.F("ai_gen")&&"likeness_policy"]},
{id:"trafficking", cat:"sexual", n:"Sex trafficking and commercial sexual exploitation", sev:4, base:1,
 d:"People, including minors, are advertised, recruited or coerced into commercial sex through the platform.",
 req:c=>c.F("listings")||c.F("ads")||c.F("meetups")||(c.adult&&c.moneyMoves),
 drv:c=>[[c.F("listings")||c.F("ads"),1,"Listings and ads can advertise commercial sex"],[c.adult&&c.moneyMoves,1,"Paid sexual content can involve coerced or trafficked people"],[c.anon,1,"Unverified accounts are hard to trace"],[c.T("rentals","gig","dating"),1,"Traffickers use in-person services and short-term rentals"]],
 red:c=>[[c.verified,1,"Verified identity"]],
 sg:c=>["trafficking_training",c.adult&&"creator_verification","prohibited_policy","le_process","report_btn"]},
{id:"cyberflash", cat:"sexual", n:"Unsolicited sexual images and messages", sev:2, base:2,
 d:"People receive explicit images or sexual messages they didn't ask for.",
 req:c=>(c.F("dm")||c.F("voice")||c.F("groups"))&&!c.noContact,
 drv:c=>[[c.strangers,1,"Strangers can message anyone"],[c.T("dating"),1,"Dating apps see high rates of unsolicited explicit images"]],
 up:c=>[[c.minors,"Under-18s may receive them"]],
 sg:c=>["dm_nudity_blur","block_mute","report_btn","new_account_limits"]},
/* Fraud and scams */
{id:"scams", cat:"fraud", n:"Scams targeting users", sev:3, base:2,
 d:"Romance, investment, fake job and fake support scams. Scammers build trust, then ask for money, often moving victims off the platform.",
 req:c=>c.F("dm")||c.F("posts")||c.F("listings")||c.F("groups")||c.F("ads"),
 drv:c=>[[c.strangers,1,"Scammers can cold-contact anyone"],[c.M("p2p")||c.M("crypto")||c.M("wallet"),1,"Money can move between users inside the product"],[c.T("dating","crypto","fintech","marketplace"),1,"Your sector is a top target for organized scam networks"],[c.F("ads"),1,"Scam ads can reach users at scale"]],
 red:c=>[[c.noContact,1,"Users can't contact each other directly"],[c.verified,1,"Verified identity"]],
 up:c=>[[c.A("older")||c.A("vulnerable"),"Many older or vulnerable users, who lose more to scams"],[c.M("crypto"),"Crypto payments can't be reversed"]],
 sg:c=>["scam_warnings","scam_detection","link_scanning","new_account_limits","report_btn","support_messaging"]},
{id:"app_fraud", cat:"fraud", n:"Authorised push payment (APP) fraud", sev:3, base:3,
 d:"Customers are tricked into sending money themselves, for example to someone posing as their bank, a seller or a romantic partner.",
 req:c=>c.M("p2p")&&c.T("fintech","crypto"),
 up:c=>[[c.A("older")||c.A("vulnerable"),"Older or vulnerable customers are targeted and lose more"]],
 sg:c=>["confirmation_payee","scam_warnings","scam_detection","support_messaging"]},
{id:"market_fraud", cat:"fraud", n:"Non-delivery, counterfeit and misrepresented goods or services", sev:2, base:2,
 d:"Buyers pay and receive nothing, receive fakes, or get something different from what was listed.",
 req:c=>c.F("listings"),
 drv:c=>[[c.M("p2p"),1,"Buyers pay sellers through the platform"],[c.anon,1,"Sellers aren't identity-verified"],[!c.M("p2p")&&!c.M("payouts"),1,"Payment happens off-platform with no buyer protection"]],
 sg:c=>["seller_verification","payout_holds","escrow_protection","listing_screening","ip_takedown"]},
{id:"payment_fraud", cat:"fraud", n:"Stolen cards and payment fraud", sev:2, base:2,
 d:"Stolen payment details are used to buy things or move money, leaving you with chargebacks, fees and processor penalties.",
 req:c=>c.M("subs")||c.M("p2p")||c.M("wallet")||c.M("payouts")||c.F("ads"),
 drv:c=>[[c.M("wallet"),1,"Stored value and gift cards are easy to cash out"],[c.anon,1,"Accounts are easy to create"],[c.M("payouts"),1,"Fraudsters can pay themselves out with stolen cards"],[c.guest&&(c.M("subs")||c.M("p2p")),1,"Guest checkout has no account history to score"]],
 sg:c=>["payment_risk",c.M("payouts")&&"payout_holds","device_signals"]},
{id:"promo", cat:"fraud", n:"Promotion, referral and incentive abuse", sev:1, base:3,
 d:"Fake accounts farm sign-up bonuses, referral rewards and promo codes.",
 req:c=>c.F("referrals"),
 drv:c=>[[c.moneyMoves,1,"Rewards can be converted into cash"]],
 up:c=>[[c.T("fintech","crypto"),"Cash sign-up bonuses in financial products attract organized farming"]],
 sg:c=>["promo_caps","device_signals","phone_email_verify"]},
{id:"impersonation", cat:"fraud", n:"Impersonation of people, brands or your staff", sev:2, base:2,
 d:"Accounts pose as real people, popular creators, brands or your own support team to deceive users.",
 req:c=>c.F("profiles"),
 drv:c=>[[c.A("creators")||c.T("social","video","creator"),1,"Popular creators and brands get cloned"],[c.moneyMoves,1,"Impersonators ask victims for money"]],
 red:c=>[[c.verified,1,"Verified identities"]],
 up:c=>[[c.A("older")||c.A("vulnerable"),"Older and vulnerable users are more easily deceived"]],
 sg:c=>["impersonation_flow","support_messaging","report_btn"]},
{id:"ad_abuse", cat:"fraud", n:"Scam, prohibited and discriminatory ads", sev:3, base:3,
 d:"Self-serve ads promote scams, prohibited products, or target people in discriminatory ways.",
 req:c=>c.F("ads"),
 drv:c=>[[c.anon,1,"Advertisers aren't verified"]],
 sg:c=>["ad_review",c.minors&&"no_minor_ads","anti_discrimination"]},
/* Financial crime */
{id:"aml", cat:"fincrime", n:"Money laundering and terrorist financing", sev:4, base:2,
 d:"Criminal proceeds are moved and disguised through accounts, transactions, stored value or items on your platform.",
 req:c=>c.M("p2p")||c.M("payouts")||c.M("crypto")||c.M("credit")||(c.M("wallet")&&c.T("fintech","crypto")),
 drv:c=>[[c.M("crypto"),1,"Crypto moves value across borders quickly"],[c.anon,1,"Users aren't identity-verified"],[c.T("fintech","crypto"),1,"Moving money is the core product"],[c.M("wallet")&&c.T("gaming"),1,"In-game currency and items are used to launder money"]],
 red:c=>[[c.verified,1,"Identity is verified (KYC)"]],
 sg:c=>["kyc","aml_monitoring","sanctions","payout_holds"]},
{id:"mules", cat:"fincrime", n:"Money mules and rented accounts", sev:3, base:2,
 d:"Criminals recruit people, often young, to receive and pass on stolen money, or rent their verified accounts.",
 req:c=>c.M("p2p")||c.M("payouts"),
 drv:c=>[[c.T("fintech","crypto","gig"),1,"Accounts that receive money are valuable to criminals"],[c.youth,1,"Young people are often recruited as money mules"],[c.F("posts")||c.F("groups")||c.F("dm"),1,"Recruitment happens through posts and messages"]],
 sg:c=>["mule_detection","kyc",c.T("gig")&&"reverify","text_screening"]},
{id:"sanctions", cat:"fincrime", n:"Sanctions violations", sev:3, base:2,
 d:"Money or services reach sanctioned people, organizations or countries.",
 req:c=>(c.M("p2p")||c.M("payouts")||c.M("crypto"))&&(c.p.regions.length>1||c.T("fintech","crypto")),
 drv:c=>[[c.M("crypto"),1,"Crypto can reach sanctioned parties directly"]],
 sg:c=>["sanctions","kyc"]},
{id:"fin_vulnerable", cat:"fincrime", n:"Financial harm to vulnerable customers", sev:3, base:1,
 d:"Customers in difficult circumstances take on unaffordable debt, lose savings to speculation or are financially abused by others.",
 req:c=>(c.T("fintech","crypto","gaming")&&(c.M("credit")||c.M("wallet")||c.M("crypto")))||(c.A("vulnerable")&&c.moneyMoves),
 drv:c=>[[c.A("vulnerable"),1,"Many users are in vulnerable circumstances"],[c.M("credit"),1,"Credit products can create unaffordable debt"],[c.M("crypto"),1,"Speculative assets can cause severe losses"],[c.A("older"),1,"Older customers are more exposed to coercion and financial abuse"]],
 sg:c=>["vulnerable_customers",c.M("credit")&&"affordability","spending_controls"]},
/* Account security */
{id:"ato", cat:"security", n:"Account takeover", sev:2, base:2,
 d:"Attackers take over accounts through stolen passwords, phishing, SIM swaps or weak recovery flows.",
 req:c=>c.F("login"),
 drv:c=>[[c.moneyMoves,1,"Accounts hold money or valuable items"],[c.big,1,"Large user bases attract credential stuffing"],[c.A("creators"),1,"Creator and seller accounts carry income and audiences"]],
 up:c=>[[c.moneyMoves||c.T("fintech","crypto"),"Compromised accounts can be drained"],[c.T("health","workplace"),"Accounts hold sensitive personal or company data"]],
 sg:c=>["mfa","breached_pw","account_recovery"]},
{id:"malware", cat:"security", n:"Malware and phishing", sev:2, base:2,
 d:"Users are sent malicious files or phishing links through your product.",
 req:c=>c.F("files")||c.F("links")||c.F("dm"),
 drv:c=>[[c.F("files"),1,"Users can share files"]],
 sg:c=>[c.F("files")&&"file_scanning","link_scanning"]},
/* Harassment and hate */
{id:"harassment", cat:"harass", n:"Harassment, bullying and pile-ons", sev:2, base:2,
 d:"Individuals are targeted with abuse, threats or coordinated pile-ons.",
 req:c=>c.F("dm")||c.F("posts")||c.F("groups")||c.F("voice")||c.F("live")||c.F("reviews"),
 drv:c=>[[c.strangers,1,"Strangers can reach anyone"],[c.F("posts")&&c.F("discovery"),1,"Public posts can go viral and attract pile-ons"],[c.A("creators"),1,"Visible creators attract targeted abuse"]],
 red:c=>[[c.noContact,1,"Users can't contact each other directly"],[c.biz,1,"Users are accountable to their employer"]],
 up:c=>[[c.youth,"Bullying of young people has severe consequences"]],
 sg:c=>["block_mute","report_btn","comment_controls","text_screening","review_queue","policies"]},
{id:"hate", cat:"harass", n:"Hate speech", sev:2, base:2,
 d:"Content that attacks people for protected characteristics such as race, religion, gender, sexuality or disability.",
 req:c=>c.F("posts")||c.F("groups")||c.F("live")||c.F("voice")||c.F("dm"),
 drv:c=>[[c.anon,1,"Anonymity lowers the cost of abuse"],[c.F("groups"),1,"Groups can organize around hate"],[c.realtime,1,"Real-time voice and video are hard to moderate"]],
 red:c=>[[c.biz,1,"Users are accountable to their employer"]],
 sg:c=>["policies","text_screening","review_queue","appeals"]},
{id:"discrimination", cat:"harass", n:"Discrimination by hosts, providers or algorithms", sev:2, base:2,
 d:"People are refused service, charged more or shown different opportunities because of who they are.",
 req:c=>(c.T("rentals","gig","marketplace","fintech")&&(c.F("listings")||c.F("meetups")||c.M("credit")))||c.F("ads"),
 sg:c=>["anti_discrimination"]},
/* Violent content */
{id:"terror", cat:"violent", n:"Terrorist and violent extremist content", sev:4, base:1,
 d:"Propaganda, recruitment and attack footage from terrorist and violent extremist groups.",
 req:c=>c.F("posts")||c.F("media")||c.F("live")||c.F("groups")||c.F("files"),
 drv:c=>[[c.F("live"),1,"Attacks have been livestreamed"],[c.F("groups")||c.F("files"),1,"Private groups and files are used for recruitment and propaganda"],[c.big,1,"Large reach attracts propaganda"]],
 sg:c=>["terror_hash",c.F("live")&&"live_controls",c.R("eu")&&"tco_removal","policies","review_queue"]},
{id:"graphic", cat:"violent", n:"Graphic violence and gore", sev:2, base:2,
 d:"Shocking imagery reaches people who didn't choose to see it.",
 req:c=>c.F("media")||c.F("live"),
 up:c=>[[c.youth,"Young users may see it"]],
 sg:c=>["media_classifier","moderator_wellness","report_btn"]},
{id:"threats", cat:"violent", n:"Credible threats of violence", sev:3, base:1,
 d:"Threats against individuals, schools or places that may be carried out.",
 req:c=>c.F("dm")||c.F("posts")||c.F("groups")||c.F("voice"),
 drv:c=>[[c.F("location")||c.F("meetups"),1,"Threats can be carried out offline"],[c.strangers,1,"Strangers can reach anyone"]],
 sg:c=>["threat_escalation","le_process","safety_owner"]},
/* Self-harm and wellbeing */
{id:"selfharm", cat:"selfharm", n:"Suicide, self-harm and eating-disorder content", sev:4, base:1,
 d:"Content or conversations that encourage, instruct or glamorize suicide, self-harm or disordered eating.",
 req:c=>c.F("posts")||c.F("media")||c.F("groups")||c.F("live")||c.F("discovery")||c.F("ai_chat"),
 drv:c=>[[c.minors,1,"Young people are most at risk"],[c.F("discovery"),1,"Recommendations can create harmful rabbit holes"],[c.T("health")||c.A("vulnerable"),1,"Many users are struggling or in crisis"],[c.F("live"),1,"Self-harm can be broadcast live"]],
 sg:c=>["crisis_resources","search_interventions","rec_safety","crisis_escalation","policies"]},
{id:"challenges", cat:"selfharm", n:"Dangerous challenges and viral stunts", sev:3, base:2,
 d:"Trends that encourage young people to do risky things on camera.",
 req:c=>c.youth&&(c.F("media")||c.F("live"))&&(c.F("posts")||c.F("discovery")),
 drv:c=>[[c.F("discovery"),1,"Recommendations spread trends fast"],[c.T("video","social"),1,"Short video drives challenge trends"]],
 sg:c=>["trend_monitoring","search_interventions","rec_safety"]},
{id:"health_misinfo", cat:"selfharm", n:"Harmful health misinformation", sev:3, base:1,
 d:"False medical claims, dangerous treatments or bad advice presented as fact.",
 req:c=>c.F("posts")||c.F("groups")||c.F("ai_chat")||c.F("ai_gen")||c.F("ads"),
 drv:c=>[[c.T("health"),2,"Health is the core subject of your product"],[c.F("ai_chat"),1,"AI answers can sound authoritative"],[c.F("ads"),1,"Unproven treatments get advertised"]],
 sg:c=>["health_info","policies",c.F("ads")&&"ad_review"]},
/* Privacy */
{id:"doxxing", cat:"privacy", n:"Doxxing and exposure of personal information", sev:3, base:1,
 d:"Someone's home address, phone number, workplace or other private details are published to target them.",
 req:c=>c.F("posts")||c.F("dm")||c.F("groups")||c.F("profiles"),
 drv:c=>[[c.F("location")||c.F("media"),1,"Location or photos can reveal where someone lives"],[c.p.identity==="real",1,"Real names make people easier to find offline"],[c.A("creators"),1,"Public figures and creators are frequent targets"]],
 sg:c=>["pii_policy",c.F("media")&&"exif_strip","report_btn"]},
{id:"scraping", cat:"privacy", n:"Scraping and bulk harvesting of user data", sev:2, base:2,
 d:"Bots collect profiles and content at scale for spam, fraud, surveillance or resale.",
 req:c=>c.F("profiles")||c.F("api")||c.F("discovery"),
 drv:c=>[[c.F("api"),1,"A public API exists"],[c.big,1,"Large datasets are valuable"]],
 up:c=>[[c.T("health","dating","fintech"),"The data is sensitive (health, sexuality or finances)"]],
 sg:c=>["anti_scraping",c.F("api")&&"api_governance","rate_limits"]},
{id:"insider", cat:"privacy", n:"Staff or contractor misuse of user data", sev:3, base:1,
 d:"People with internal access look up, leak or misuse private data.",
 req:c=>c.F("dm")||c.T("health","fintech","dating","crypto","edtech","workplace")||c.youth,
 drv:c=>[[c.F("dm"),1,"Staff tools may expose private messages"],[c.T("health","fintech","dating","crypto"),1,"You hold sensitive personal data"]],
 sg:c=>["access_controls"]},
{id:"cameras", cat:"privacy", n:"Hidden cameras and privacy violations in rentals", sev:3, base:2,
 d:"Guests are recorded without their knowledge.",
 req:c=>c.T("rentals")&&c.F("listings"),
 sg:c=>["camera_policy","report_btn","offline_incidents"]},
/* Physical safety */
{id:"stalking", cat:"physical", n:"Stalking and location tracking", sev:4, base:1,
 d:"Someone's location is used to follow, find or harm them.",
 req:c=>c.F("location")||c.F("meetups"),
 drv:c=>[[c.F("location"),1,"Location is shared in the product"],[c.strangers,1,"Strangers can see or contact users"],[c.T("dating","gig","rentals"),1,"People meet or visit each other in person"],[c.minors&&c.F("location"),1,"Young users' location could be exposed"]],
 sg:c=>["approx_location","block_mute","safety_features",c.F("media")&&"exif_strip"]},
{id:"offline", cat:"physical", n:"Assault or harm during in-person meetings", sev:4, base:2,
 d:"Physical or sexual violence when people meet, visit or provide services face to face.",
 req:c=>c.F("meetups"),
 drv:c=>[[c.T("dating","gig","rentals"),1,"Your product brings strangers together in person"],[c.anon,1,"People can meet without verified identities"],[c.minors&&c.T("dating","social","gaming"),1,"Adults could arrange to meet minors"]],
 red:c=>[[c.verified,1,"Everyone is identity-verified"]],
 sg:c=>["provider_verification","safety_features","offline_incidents","two_way_ratings","le_process"]},
{id:"worker_safety", cat:"physical", n:"Harm to workers and service providers", sev:3, base:2,
 d:"Drivers, couriers, hosts and freelancers face assault, harassment or unsafe situations from customers.",
 req:c=>c.T("gig","rentals")&&c.F("meetups"),
 drv:c=>[[c.anon,1,"Customers aren't verified"]],
 sg:c=>["two_way_ratings","safety_features","offline_incidents"]},
{id:"acct_sharing", cat:"physical", n:"Unvetted people working under someone else's account", sev:3, base:3,
 d:"Verified workers rent or share their accounts, so the person who shows up hasn't been checked.",
 req:c=>c.T("gig")&&c.M("payouts"),
 sg:c=>["reverify","provider_verification"]},
/* Platform integrity */
{id:"fake_accounts", cat:"integrity", n:"Fake and bot accounts at scale", sev:2, base:2,
 d:"Automated or mass-created accounts used for spam, fraud, manipulation or reward farming.",
 req:c=>c.F("signup"),
 drv:c=>[[c.anon,1,"Sign-up needs only an email, or nothing"],[c.F("referrals")||c.M("payouts"),1,"Fake accounts can earn rewards or payouts"],[c.big,1,"Scale makes you worth attacking"]],
 red:c=>[[c.verified,2,"Identity is verified at sign-up"]],
 sg:c=>["captcha","phone_email_verify","device_signals","new_account_limits"]},
{id:"spam", cat:"integrity", n:"Spam and malicious links", sev:1, base:3,
 d:"Unwanted promotional content and links flood conversations and feeds.",
 req:c=>c.F("posts")||c.F("dm")||c.F("groups")||c.F("reviews")||c.F("listings"),
 drv:c=>[[c.anon,1,"Accounts are cheap to create"]],
 sg:c=>["rate_limits","link_scanning","new_account_limits","text_screening"]},
{id:"fake_reviews", cat:"integrity", n:"Fake and manipulated reviews", sev:2, base:3,
 d:"Bought, swapped or self-written reviews mislead customers; honest reviews get suppressed.",
 req:c=>c.F("reviews"),
 drv:c=>[[c.F("listings"),1,"Rankings drive sales, so sellers have an incentive to cheat"]],
 sg:c=>["review_integrity","review_policy","device_signals"]},
{id:"cib", cat:"integrity", n:"Coordinated inauthentic behavior and disinformation", sev:3, base:1,
 d:"Networks of fake or coordinated accounts push narratives, products or political disinformation.",
 req:c=>c.F("posts")||c.F("groups")||c.F("ads")||c.F("discovery"),
 drv:c=>[[c.big,1,"Large reach attracts influence operations"],[c.F("ads"),1,"Ads can be used for political targeting"],[c.T("social","video","messaging"),1,"Social and video platforms are primary targets"],[c.F("ai_gen"),1,"AI makes fake content cheap"]],
 sg:c=>["cib_detection","election_plan","device_signals"]},
{id:"api_abuse", cat:"integrity", n:"Automation abuse through your API", sev:2, base:2,
 d:"Developers or bots use your API to spam, scrape or manipulate at scale.",
 req:c=>c.F("api"),
 sg:c=>["api_governance","rate_limits"]},
{id:"guest_abuse", cat:"integrity", n:"Untraceable abuse through guest access", sev:2, base:2,
 d:"Guests can't be warned, banned or held to account. Removed users come straight back, and reports lack evidence of who did what.",
 req:c=>c.guest,
 drv:c=>[[c.comms||c.F("posts"),1,"Guests can talk to or post for other people"],[c.hostsMedia,1,"Guests can upload media"],[c.minors,1,"Guest play is popular with children, and bad actors know it"]],
 up:c=>[[c.minors&&c.comms,"Guests can reach minors with no identity trail"]],
 sg:c=>["guest_limits","guest_signals","guest_evidence","device_signals"]},
/* Illegal goods */
{id:"illegal_goods", cat:"illegal", n:"Drugs, weapons and other prohibited goods", sev:3, base:1,
 d:"Sale or promotion of illegal drugs, weapons, counterfeit documents and other prohibited items.",
 req:c=>c.F("listings")||c.F("groups")||c.F("posts")||(c.F("dm")&&c.moneyMoves),
 drv:c=>[[c.F("listings"),2,"Listings can advertise prohibited items"],[c.M("p2p")||c.M("crypto"),1,"Sales can be paid for inside the product"],[c.anon,1,"Sellers are anonymous"]],
 up:c=>[[c.youth,"Young users could buy drugs, vapes or weapons"]],
 sg:c=>["prohibited_policy",c.F("listings")&&"listing_screening","text_screening","le_process"]},
{id:"ip", cat:"illegal", n:"Counterfeits and copyright infringement", sev:2, base:2,
 d:"Counterfeit goods and pirated content expose you to rights-holder claims.",
 req:c=>c.F("listings")||c.F("media")||c.F("files")||c.F("live"),
 drv:c=>[[c.F("listings"),1,"Counterfeit goods can be listed"],[c.T("video","creator"),1,"Pirated content gets re-uploaded"]],
 sg:c=>["ip_takedown",c.F("listings")&&"listing_screening"]},
{id:"gambling", cat:"illegal", n:"Gambling and gambling-like mechanics", sev:2, base:2,
 d:"Loot boxes, skin betting or unlicensed gambling, including by minors.",
 req:c=>c.M("wallet")||(c.M("crypto")&&c.T("gaming")),
 drv:c=>[[c.T("gaming"),1,"Randomized items and skins can be gambled"]],
 up:c=>[[c.youth,"Minors are exposed to gambling-like spending"]],
 sg:c=>["spending_controls","prohibited_policy"]},
/* AI misuse */
{id:"ai_csam", cat:"ai", n:"AI-generated child sexual abuse material", sev:4, base:2,
 d:"The model is prompted to produce sexualized imagery or text involving children.",
 req:c=>c.F("ai_gen"),
 drv:c=>[[c.anon,1,"Unverified accounts can experiment freely"],[c.adult,1,"Adult content generation is allowed, which makes abuse harder to separate"]],
 sg:c=>["gen_filters","gen_training_data","csam_hash","csam_reporting","gen_redteam"]},
{id:"deepfakes", cat:"ai", n:"Deceptive or sexual deepfakes of real people", sev:3, base:2,
 d:"Synthetic media of real people used for harassment, fraud or disinformation.",
 req:c=>c.F("ai_gen"),
 drv:c=>[[c.T("genai"),1,"Generation is the core product"],[c.F("posts")||c.F("media"),1,"Generated media can be posted publicly"]],
 sg:c=>["likeness_policy","gen_provenance","gen_filters","ncii_process"]},
{id:"jailbreak", cat:"ai", n:"Jailbreaks for dangerous information", sev:3, base:3,
 d:"Users get around safeguards to obtain weapons, hacking or self-harm instructions.",
 req:c=>c.F("ai_gen")||c.F("ai_chat"),
 sg:c=>["gen_redteam","gen_filters","ai_abuse_monitoring"]},
{id:"companion", cat:"ai", n:"Emotional dependency and harmful AI companion responses", sev:3, base:2,
 d:"People form intense attachments to an AI that may encourage isolation, validate harmful ideas or mishandle a crisis.",
 req:c=>c.F("ai_chat"),
 drv:c=>[[c.minors,1,"Minors may use it"],[c.A("vulnerable")||c.T("health"),1,"Users may be lonely, unwell or in crisis"],[c.adult,1,"Romantic or sexual roleplay is allowed"]],
 up:c=>[[c.minors,"Chatbot harms to minors have led to lawsuits and new laws"]],
 sg:c=>["ai_disclosure","companion_safeguards","crisis_resources",c.minors&&"age_assurance"]},
{id:"prompt_injection", cat:"ai", n:"Prompt injection and AI agent misuse", sev:2, base:2,
 d:"Instructions hidden in content hijack the AI to leak data or take unwanted actions.",
 req:c=>c.F("ai_chat")&&(c.F("api")||c.F("links")||c.F("files")),
 sg:c=>["tool_permissions","ai_abuse_monitoring"]},
/* Operational readiness */
{id:"no_owner", cat:"readiness", n:"No one owns urgent safety escalations", sev:3, base:2,
 d:"A child-safety report, credible threat or live incident arrives and nobody is responsible for acting on it.",
 req:c=>c.p.team==="none"||c.p.team==="parttime",
 drv:c=>[[c.p.team==="none",1,"No one is responsible for trust and safety"],[c.minors,1,"Child-safety reports need a response within hours"]],
 sg:c=>["safety_owner","review_queue","le_process"]},
{id:"le", cat:"readiness", n:"Unprepared for law-enforcement and emergency requests", sev:2, base:1,
 d:"Police request data or an emergency disclosure, and there is no process to verify and respond.",
 req:c=>c.ugc||c.moneyMoves,
 drv:c=>[[c.F("dm"),1,"You hold private communications"],[c.p.team!=="mature",1,"There is no established legal-response process"],[c.moneyMoves,1,"Financial records are frequently requested"]],
 sg:c=>["le_process"]},
{id:"wellness", cat:"readiness", n:"Moderator exposure to traumatic content", sev:2, base:2,
 d:"Reviewers see graphic, sexual or violent material that harms their mental health.",
 req:c=>c.hostsMedia,
 drv:c=>[[c.mid,1,"Review volume will be significant"]],
 sg:c=>["moderator_wellness"]},
{id:"overenforce", cat:"readiness", n:"Wrongful enforcement without redress", sev:2, base:2,
 d:"Mistaken removals and bans with no explanation or appeal erode trust and breach some laws.",
 req:c=>c.ugc,
 drv:c=>[[c.A("creators"),1,"Mistakes cost creators, sellers or workers income"],[c.R("eu"),1,"EU law requires reasons and appeals"],[c.mid,1,"Automation at scale makes more mistakes"]],
 sg:c=>["appeals","sor","qa_program","enforcement_log"]}
];
